### ISSUE TITLE
add monarch-curated animal diseases for omia

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#10]
we have monarch-curated phenotypes for the animal diseases in our private repo:
https://subversion.crbs.ucsd.edu/Monarch/trunk/annotation/OMIA

i am not sure if these get added to a new Monarch graph, or to the OMIA (#9) graph?

**Comment by nlwashington** [comment]
For now, let's add these to a new resource, which is "Monarch".  Keep it local for now, but then we should add this to a public repo soon.

**Comment by nlwashington** [comment]
@nicolevasilevsky i notice that there are no phenotypes for http://omia.angis.org.au/OMIA001612/9031/.  can you add?

**Comment by nlwashington** [comment]
we will be testing these out in our next load.  will close when the parser is committed.

**Comment by jmcmurry** [comment]
These still have to be added to OwlSim at some point, but the dipper work is done, so closing it.
