### ISSUE TITLE
Where/how can I access ChemicalSubstance associations?

### ISSUE THREAD

**Issue by ehinderer** [monarch-initiative/dipper#1011]
I'm interested in accessing the associations like those parsed and defined in the MyChem.py source script in Dipper. In particular those like the ChemicalSubstance-[action]-Protein triple. I noticed that these associations are not present in Monarch's UI and the BioLink API returns no associations when I use "ChemicalSubstance" as a category. 

I'm assuming that the source scripts in Dipper serve as the baseline data ingestion to everything included in Monarch's SciGraph instance and that this SciGraph instance serves as the underlying data structure for Monarch's UI. Is this true? I've been trying to track and compare the definition of associations between the source code and what is displayed on Monarch. Some associations, like Reactome.py's "involved_in" does show up under "Pathways" on the UI. 

I see that the MyChem.py script does not call the add_association_to_graph function like some of the others do, could this be related? On the other hand, I see that CTD.py does call add_association_to_graph for making chemical-disease associations, yet I also have not seen chemical mentions in Monarch's UI, nor do I see any MESH: chemical curies in the results when I manually looked up a MESH disease ID in the BioLink API that I took from the CTD_chemicals_diseases.tsv file. 

Sorry if this is more of a long-winded discussion than an issue. I'd be happy to move this into discussions, or talk offline if it's too involved for here.

**Comment by kshefchek** [comment]
this was answered over slack - @ehinderer let us know if you have any additional questions
