### ISSUE TITLE
Modeling TALENs and CRISPRs

### ISSUE THREAD

**Issue by bryanlaraway** [monarch-initiative/dipper#103]
Need to determine the proper methods for modeling the involvement of TALENs and CRISPRs in genotypes. 

Current example is with ZFIN #12 , where we have the following files:
http://zfin.org/downloads/Morpholinos.txt
http://zfin.org/downloads/CRISPR.txt
http://zfin.org/downloads/TALEN.txt
http://zfin.org/Downloads/pheno_environment.txt

While morpholinos are a bit more straightforward in their use as gene knockdown reagents, TALENs and CRISPRs are more complicated in regards to the methods that they may be used to influence an intrinsic and extrinsic genotype.

**Comment by nlwashington** [comment]
@mbrush you can use this ticket if we need to deal with integrated CRISPR modeling issues for ZFIN.  otherwise, close, if a non-issue.

**Comment by nlwashington** [comment]
we can open a new ticket if we need to deal with talen/crispr as integrated parts of a genotype.
