### ISSUE TITLE
add data source panther orthologs

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#11]
the panther orthologs are here:
ftp://ftp.pantherdb.org/ortholog/current_release/

i have use both the refgenome orthologs and the HCOP file.  there are redundancies, but HCOP has more species than the refgenome one itself.

additional species might be necessary particularly for linking with the OMIA annotations to orthologous genes.  those are only available by querying for each protein family, for example:
http://pantherdata.usc.edu/PANTHER9.0/books/PTHR10000/cluster.ortholog 

The PTHRxxxxx is the family id. 
The server and directories were set up for Paint to access the PANTHER library. You can simply cat the ortholog files from each family to create one file.

**Comment by nlwashington** [comment]
@cmungall do we want to keep the non-metazoan and/or non-animal species?  (one thought would be to toss the arabidopsis calls....the yeast ones may be relevant.)

**Comment by cmungall** [comment]
We can ask Bryan in a few months if he thinks the arabidopsis ones are 
worth having around (or if he needs them for this analysis)

But as a first pass let's not confuse folks by throwing plants in there. 
Opisthokontes only.

**Comment by nlwashington** [comment]
this is basically finished, using the ortholog data model #20.  presently, taxon filters are embedded in the code, but this should be parameterized as in #25.
