### ISSUE TITLE
add data source AnimalQTL DB

### ISSUE THREAD

**Issue by bryanlaraway** [monarch-initiative/dipper#133]
Need to fetch the AnimalQTLdb data.
This the is website:
http://www.animalgenome.org/cgi-bin/QTLdb/index
QTL data is available in cM and bp format for pig, cattle, chicken, sheep (cM only), rainbow trout (cM only), and horse (cM only).

**Comment by bryanlaraway** [comment]
We will be needing chromosome assemblies for each of the species available in AnimalQTL DB:
-Cattle (Bos Taurus): We are using the [UMD 3.1](http://www.animalgenome.org/QTLdb/doc/genome_versions#UMD_3.1) assembly, but the data using the [Btau 4.6](http://www.animalgenome.org/QTLdb/doc/genome_versions#Btau_4.6) assembly is also available.
-Sheep (Ovis aries): Uses the [OAR 3.1](http://www.animalgenome.org/QTLdb/doc/genome_versions#OAR_3.1) assembly.
-Chicken (Gallus gallus): Uses the [GG 4.0](http://www.animalgenome.org/QTLdb/doc/genome_versions#GG_4.0) assembly.
-Pig (Sus scrofa): Uses the [SS 10.2](http://www.animalgenome.org/QTLdb/doc/genome_versions#SS_10.2) assembly.
-Horse (Equus caballus): Uses the [EquCab 2.0](http://www.animalgenome.org/QTLdb/doc/genome_versions#EquCab2.0) assembly.
-Rainbow Trout (Oncorhynchus mykiss): Currently QTL locations are only available in cM, so no assembly provided/indicated.

In addition, each species has the following breeds included in the source data:
-Cattle: Angus; Asturian Mountain; Asturian Valley; Australian Lowline; Ayrshire; Belgian Blue; Belmont Red; Blonde D'Aquitaine; Boran; Brahman; Brangus; Braunvieh; Brown Swiss; Canchim; Charolais; Danish Jersey; Danish Red; Fleckvieh; Gelbvieh; German Angus; Gir; Hanwoo; Hereford; Herens; Holstein (Holstein-Friesian); Icelandic; Israeli Holstein; Jersey; Jiaxian Red; Large White; Limousin; Luxi; Maine-Anjou; Marchigiana; Mongolian; Nanyang; N'Dama; Nelore; Norwegian Red; Piedmontese; Pinzgauer; Polish Red; Qinchuan; Red Angus; Reggiana; Retinta; Sahiwal; Sanhe; Santa Gertrudis; Shorthorn; Simmental; Swedish Friesian; Swedish Red-And-White; Tarentaise; Wagyu; Xinjiang Brown.

-Chicken: Barnevelders; Beijing You Chicken; Brillenschaf; Cornish; Duroc; Erhualian; Fayoumi; Houdan; Leghorn; New; North Holland Blue; Oh-Shamo; Plymouth; Red Junglefowl; Rhode; Silkie.

-Horse: Andean; Appaloosa; Arabian; Dales Pony; Dutch Warmblood; Fell Pony; Freiberger; French Trotter; German Warmblood; Hanoverian; Icelandic; Quarter Horse; Rhenish German Coldblood; Saddlebred; Schleswiger Heavy Draft; Shetland Pony; South German Coldblood; Standardbred; Swiss Warmblood; Thoroughbred

-Pig: Arabian; Asturian; Bama Xiang; Berkshire; Chester White; Danish Landrace; Duroc; Erhualian; German Landrace; Hampshire; Hang; Iberian; Italian Landrace; Jinhua; Korean Native Pig; Landrace;   Large White; Leicoma; Meishan; Minzhu; Norwegian Landrace; Norwegian Red; Pietran; Pulawska; Songliao Black; Sutai; Toncheng; Wild Boar; Yorkshire; Yushan Black.

-Sheep: Altamurana; Awassi; Baluchi; Berrichon Du Cher; Bluefaced Leicester; Charollais; Cheviot; Coopworth; Corriedale; Dorper; Dorset; Friesian Milk Sheep; Gentile Di Puglia; Han; Icelandic; Ile-De-France; Latxa; Leicester; Manchega; Masai; Mehraban; Merino Strains; Rasa Aragonesa; Romanov; Romney; Santa In&Ecirc; Sardinian; Scottish Blackface; Soay; Spanish Churra; Suffolk; Texel; White Suffolk.

**Comment by bryanlaraway** [comment]
I have a slew of different prefixes I'm using in the Animal QTL processing to link out to different pages around the Animal QTL database website. Let me know if these will work or another approach is preferred:

'AQTLCattle' : 'http://www.animalgenome.org/cgi-bin/QTLdb/BT/qdetails?QTL_ID='
'AQTLTraitCattle' : 'http://www.animalgenome.org/cgi-bin/QTLdb/BT/qtrait?trait_ID='
'AQTLChicken' : 'http://www.animalgenome.org/cgi-bin/QTLdb/GG/qdetails?QTL_ID='
'AQTLTraitChicken' : 'http://www.animalgenome.org/cgi-bin/QTLdb/GG/qtrait?trait_ID='
'AQTLPig' : 'http://www.animalgenome.org/cgi-bin/QTLdb/SS/qdetails?QTL_ID='
'AQTLTraitPig' : 'http://www.animalgenome.org/cgi-bin/QTLdb/SS/qtrait?trait_ID='
'AQTLSheep' : 'http://www.animalgenome.org/cgi-bin/QTLdb/OA/qdetails?QTL_ID='
'AQTLTraitSheep' : 'http://www.animalgenome.org/cgi-bin/QTLdb/OA/qtrait?trait_ID='
'AQTLHorse' : 'http://www.animalgenome.org/cgi-bin/QTLdb/EC/qdetails?QTL_ID='
'AQTLTraitHorse' : 'http://www.animalgenome.org/cgi-bin/QTLdb/EC/qtrait?trait_ID='
'AQTLRainbowTrout' : 'http://www.animalgenome.org/cgi-bin/QTLdb/OM/qdetails?QTL_ID='
'AQTLTraitRainbowTrout' : 'http://www.animalgenome.org/cgi-bin/QTLdb/OM/qtrait?trait_ID='
'AQTLPub' : 'http://www.animalgenome.org/cgi-bin/QTLdb/BT/qabstract?PUBMED_ID='

**Comment by nlwashington** [comment]
@mbrush what is the right relationship between a QTL and a gene that it is related to?  perhaps GENO:feature_to_gene_relation  ?
