### ISSUE TITLE
add data source IMPC

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#14]
add IMPC geno-pheno data.

this can be fetched from csv or REST queries (json).

http://www.ebi.ac.uk/mi/impc/solr/genotype-phenotype/select?q=*:*&rows=10&wt=json

or

ftp://ftp.ebi.ac.uk/pub/databases/impc/latest/csv/IMPC_genotype_phenotype.csv.gz
ftp://ftp.ebi.ac.uk/pub/databases/impc/latest/csv/EuroPhenome_genotype_phenotype.csv.gz
ftp://ftp.ebi.ac.uk/pub/databases/impc/latest/csv/MGP_genotype_phenotype.csv.gz

**Comment by bryanlaraway** [comment]
In my latest commit, https://github.com/monarch-initiative/dipper/commit/e7655cd5331b171a8537db11f2ecee921b057290, I believe I have wrapped up the IMPC ingest. I should have the full genotype partonomy completed from the effective_genotype down to the sequence_alteration_type, plus the genotype to phenotype annotations. I'll work on submitting tickets for any known issues I have encountered that need addressing. Additionally, I'll try and abstract out some of the functions for creating the more complex parts of the genotype partonomy from the individual parts.

Running the full ingest on IMPC takes about 90 minutes. If you want to look at a subset of the data, comment out the processing of the additional data files (lines 121 to 124). I’ll try and run the full ingest and add the full output ttl file to the DropBox for review, but for now I have updated the impc_test_set.ttl file in the DropBox.

**Comment by bryanlaraway** [comment]
Have a few new columns with the 3.0 release from IMPC: allele_name, project_name, project_fullname, top_level_mp_term_id, percentage_change, and statistical_method. Some of these we have seen before in prior releases, so it appears that they were added back.

**Comment by nlwashington** [comment]
each association comes with information about who performed the assay/analysis:  resource_name, project_name, and phenotyping_center.  how should we add these to the associations?  i would think these might fall under either the "evidence" or "source", or perhaps in a new provenance category.

for example: http://www.mousephenotype.org/data/genes/MGI:1100498

the items list both IMPC and JAX in the first few cases here.  it seems important to track this provenance.

if i do attach these resources to the associations, what is that pattern?  (we haven't really attached whole "projects" as evidence before.)  i figure that we'd probably want to attach the phenotyping_center to a whole evidence blob for the assay (which is also provided, which we are not dealing with yet.)

in this case, let's say i've created an association with the id MONARCH:12345.  this represents the first genotype-to-phenotype association listed in the above webpage.  what would the triples look like for the evidence that is attached to it?

    MONARCH:12345 a :Association
        RO:has_phenotype MP:abnormal_sleep_behavior
        RO:has_genotype <a genotype id that we assemble from the allele, gene, strain, etc>
        RO:has_source <http://www.mousephenotype.org/>  # this is IMPC, but is this the right syntax?

the sources in these cases are: 
* MGP  <-- not sure what the uri would be here.  is it KOMP?
* [IMPC](http://www.mousephenotype.org/)
* [EuroPhenome](http://www.europhenome.org/)
* [3I](http://www.immunophenotyping.org/about-3i)  
should they be listed as literals?  or some link to a source registry?

i could punt on this until the next release, if it is too hard to do this round.
@cmungall or @mbrush
