### ISSUE TITLE
add owl ontology declarations to data

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#142]
need each ttl file to have an owl:Ontology declaration, in order to "source" it.

like:
<pre>
source_id rdf:type owl:Ontology .
</pre>
the ```source_id``` needs to be the same as is in the accompanying dataset.ttl for each source.  this should be the monarch-processed version of the source.

**Comment by cmungall** [comment]
How about:

    <http://data.monarchinitiative.org/ttl/biogrid.ttl> a owl:Ontology ;
      owl:versionInfo <http://archive.monarchinitiative.org/ttl/biogrid-YYYY-MM-DD.ttl>

`owl:versionInfo` isn't really part of the HCLS recommendations (but neither is owl:Ontology). With our OWL modeling hats on these are ontologies in the OWL sense (aka bags of axioms, could be abox and tbox)

**Comment by mellybelly** [comment]
seems reasonable, but bypasses any release info from the source. but maybe for consistency we just don't worry about that, or add in a different place (but this was discussed elsewhere)

**Comment by nlwashington** [comment]
ok, so owl:versionInfo is supposed to be used with a literal, and owl:versionIRI with an IRI... i think @cmungall has mixed the two.  I will try:

    <http://data.monarchinitiative.org/ttl/biogrid.ttl> a owl:Ontology ;
        owl:versionIRI <http://archive.monarchinitiative.org/ttl/biogrid-YYYY-MM-DD.ttl>
        owl:versionInfo "biogrid-YYYY-MM-DD"

**Comment by nlwashington** [comment]
@ccondit close if this is satisfactory.
