### ISSUE TITLE
process clinvar xml

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#155]
we've already got the clinvar processed from the flat files, but we really need to get it from the xml to ensure that we get proper citation information, as well as links to all the genes when there's >1 involved.

for that we'll need to process the ftp://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/ClinVarFullRelease_00-latest.xml.gz

**Comment by kshefchek** [comment]
This is completed, see duplicated ticket here: https://github.com/monarch-initiative/dipper/issues/276
