### ISSUE TITLE
Verify curie map for identifier.org URIs

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/dipper#158]
Verify that these URIs resolve as some look incorrect, for example:
'PomBase' : 'http://identifiers.org/PomBase:'
'TAIR' : 'http://identifiers.org/TAIR:'
'SwissProt' : 'http://identifiers.org/SwissProt:'
etc.

**Comment by nlwashington** [comment]
This should be added to the testing suite.

**Comment by jmcmurry** [comment]
A related issue is here: https://github.com/monarch-initiative/monarch-app/issues/984
In essence, we need to not only verify that the mappings are correct, but also that they are consistent app-wide.

**Comment by jmcmurry** [comment]
Hmm. 'TAIR' : 'http://identifiers.org/TAIR:' is definitely wrong: resolution of the ID depends on knowing which type it is. I'm not sure what our identifier policy ought to be in this situation. TAIR prescribe a prefix (and a colon), but that prefix (eg. "Gene", or "AASequence") is so generic as to invite confusion (at best) and collisions (at worst).
Perhaps we could tweak their prefixes simply by prepending 'TAIR-'. Still, the locus example requires special handling as it doesn't have a prefix at all.

identifiers.org resolving nsp | native resolving nsp | example LRI | LRI RegEx | Suggested prefix
--------|--------|-------|----|-----
http://identifiers.org/tair.gene/ | http://arabidopsis.org/servlets/TairObject?accession= | Gene:2200934 | 	^Gene:\d{7}$ | TAIR-Gene
http://identifiers.org/tair.locus/ | http://arabidopsis.org/servlets/TairObject?type=locus&name= | AT1G01030 | ^AT[1-5]G\d{5}$ | TAIR-Locus
http://identifiers.org/tair.protein/ | http://arabidopsis.org/servlets/TairObject?accession= | AASequence:1009107926 | ^AASequence:\d{10}$ | TAIR-AASequence

**Comment by kshefchek** [comment]
I think @TomConlin took care of this, please reopen if there are still issues
