### ISSUE TITLE
add data source HPO annotations

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#16]
import the disease-phenotype associations from http://human-phenotype-ontology.org jenkins.

@cmungall or @pnrobinson , is the jenkins build number ok to use to tag the data "version"?  (for example, it's on #789 today. http://compbio.charite.de/hudson/job/hpo.annotations/lastStableBuild/)

**Comment by nlwashington** [comment]
I am happy to use a date stamp as the version.  (That is what I do for any sources that don't have explicit version numbers.)

**Comment by drseb** [comment]
sorry for the delay! I will do this tomorrow!!

**Comment by drseb** [comment]
Hi,

> I am happy to use a date stamp as the version. (That is what I do for any sources that don't have explicit version numbers.)

could you let me know if the file “data_version.txt” associated with every build does the job?

Seb=

**Comment by nlwashington** [comment]
@drseb i am now using the ```data_version.txt``` in the pipeline to version the dataset.

**Comment by nlwashington** [comment]
i have finished the initial pass at HPO annotation import for the rare disease files.  this only includes the "abnormal" annotations.  ("remarkably normal" annotations will get addressed in #113.)  still need to fix the evidence codes in #114. code is cleaned up, and documented.
