### ISSUE TITLE
zfin orthology evidence

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#164]
zfin provides orthology calls.  they also have evidence for these calls, but it is only available in zebrafishmine.

there is a termplate query for it:
http://zebrafishmine.org/template.do?name=Gene_Orthologue&scope=all

but it only lists ZDB-ORTHO identifiers, rather than external (NCBIGene or ENSEMBL) ids.  And I can't figure out how to get at the id/mapping.  i've put in a request to their curators... waiting to find out more.

**Comment by selewis** [comment]
We might check with Paul Thomas. They went through an exercise of comparing
PANTHER ortholog calls to ZFIN's manually made (really) ortholog calls.
Mostly the same, but he or Huaiyu might have the mapping information.

On Thu, Jul 23, 2015 at 2:10 PM, Nicole Washington <notifications@github.com

**Comment by nlwashington** [comment]
yes, but from the basic panther orthology files, there are no publications referenced, whereas the zfin data has PMIDs attached.

**Comment by nlwashington** [comment]
will be in next load.
