### ISSUE TITLE
implement go annotation parser

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/dipper#165]
Q: is it better to implement this as a standalone module with its own object model, and have this as a dependency? Or just bake right into dipper?

**Comment by nlwashington** [comment]
for processing GO annotations, do we want to be selective for monarch-purposes to only ingest the IMP annotations?  furthermore, do we want to convert them from simply an annotation to GO:xxxxxxx to be GO:xxxxxxxPHENOTYPE ?

**Comment by nlwashington** [comment]
@cmungall shall we try to include GO in the Nov data push?

**Comment by kshefchek** [comment]
Initial parser implemented, see https://github.com/monarch-initiative/dipper/issues/410 for discussion/comments.
