### ISSUE TITLE
import mpd data & map to MP terms

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#169]
http://phenome.jax.org/download/mpd_datasets_metadata.xml  **
http://phenome.jax.org/download/straininfo.csv
http://phenome.jax.org/download/measurements.csv
http://phenome.jax.org/download/ontology_mappings.csv and 
http://phenome.jax.org/download/strainmeans.zip of the files, and remove duplicate values 

as before with the NIF ingest, we'll need to map the measurements to MP terms; we can map those that are > 2sd from mean of those tested. 

@mbrush and @cmungall we may need to link the measurements/calls to what the references were as the basis of comparison.  for example, phenotype P is observed when compared to the average of strains X, Y, Z.   this should go into the evidence model somehow.

**They may have just changed this filename recently from ... datasets_metadata.xml. - Julie Edit

**Comment by nlwashington** [comment]
the current strategy for this data is to create a "sex qualified genotype" (GENO:0000645), and list the strain_id as the genomic background for that genotype.

however, i wonder if instead (or in addition to) we might want to make the female/male versions of each strain just members of the strain itself?  

for example, if a strainX has a male member:
<pre>
strainX rdf:type NCBITaxon:mouse
strainX-male RO:member_of strainX
strainX-male rdf:type sex-qualified-genotype
strainX-male GENO:background_genotype strainX
strainX-male RO:has_phenotype MP:some_phenotype
</pre>
or even, should we say that:
<pre>
strainX-male rdf:type strainX
</pre>
this latter case may not work, because strainX itself is not declared as a class, it is presently just an instance of the NCBITaxon:mouse.

furthermore, how do i qualify the genotype as being of a particular sex?

**Comment by nlwashington** [comment]
ok, just found the classes for GENO:male_genotype and female_genotype in the latest (GENO commit)[https://github.com/monarch-initiative/GENO-ontology/commit/7c3100c66e5fccad5ff2b4e6b3616a5a4edbbbc3].

**Comment by jmcmurry** [comment]
MPD have newly implemented sex-specific URLs for us to hang annotations off of. eg:
http://phenome.jax.org/db/q?rtn=strains/details&strainid=7&sex=f
http://phenome.jax.org/db/q?rtn=strains/details&strainid=7&sex=m

**Comment by jmcmurry** [comment]
This past January MPD absorbed a collection of ~70 QTL data sets (the QTL Archive).   These QTL data sets have their own set of phenotype measurements, that we store separately from our strain survey phenotypes measurements (because they are different objects). These QTL phenotype measurements have been mapped to ontology terms.  This information was released prematurely and retracted incompletely. The download file available of the QTL phenotype measurements is now available. http://phenome.jax.org/download/

**Comment by nlwashington** [comment]
should the QTL Archive data have a different citation/source?

**Comment by nlwashington** [comment]
FYI, i suspect we get the qtl phenotypes from MGI directly; but we won't have the assays unless we pull them here.

**Comment by nlwashington** [comment]
The MPD data is now in our scigraph, using a +/- 2s.d. cutoff.  We have not yet implemented the complex provenance model (to be in another ticket).
