### ISSUE TITLE
Variants and phenotypes

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/dipper#174]
When I go to the Variants tab for Disease Group: Charcot-Marie-Tooth disease
http://beta.monarchinitiative.org/disease/DOID%3A10595
and I click on one of the variants, I am taken to the Phenogrid page and the variant is associated with a set of phenotypes. I am not sure this is the correct/desired behaviour, since as far as I know we do not have this level of variant-for-variant phenotype data, and I would assume that the phenotype data is coming from the disease entry (BUT: not every patient/every variant is associated with all of these phenotypic features of course!). I think the variants should be linked to their source, which is also not clear from this Webpage.

**Comment by nlwashington** [comment]
Each of these variants has been associated with a given OMIM term as coming from ClinVar or other data source, which are the "phenotypes" listed.  but you're right, the phenogrid is using the inferred data to map from the class of disease to the phenotypic features.

@pnrobinson Issues with the interface behavior should be logged into monarch-app.

**Comment by nlwashington** [comment]
moved to monarch-app tracker.
