### ISSUE TITLE
Relation ontology link broken

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/dipper#178]
Looking at this page:
http://beta.monarchinitiative.org/disease/OMIM:609311
there is a "tool tip" that appears when you hover the mouse over RO_0003301
Two issues:
(i) The tool tip just repeats RO_0003301 but it should provide the English language name of the term
(ii) the link is broken (http://www.ontobee.org/browser/rdf.php?o=RO&iri=http://purl.obolibrary.org/obo/RO_0003301).

**Comment by nlwashington** [comment]
Moving this to monarch-app, https://github.com/monarch-initiative/monarch-app/issues/885
