### ISSUE TITLE
Model: _mgivslckey77893 [Not Specified]

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/dipper#179]
The title "Model: _mgivslckey77893 [Not Specified]" is not very informative. It is coming from this page:

http://beta.monarchinitiative.org/model/MGI:5460859

Under the assumption that the title is being picked up by mining some fields of the page, I think that we should have some sort of post-processing that does not show "Not Specified", which is likely to be confusing if you see it outside of the context of MGI. In this particular case, it would be better to show simply the name of the allele as the model name: Fgd4tm1.1Ics (with Fgd4<super>tm1.1Ics</super>).

**Comment by nlwashington** [comment]
This is an error with the data processing...it should have a proper label.  I'll investigate.

**Comment by nlwashington** [comment]
This seems okay in tests; should be fixed with the next release.
