### ISSUE TITLE
refactor to use less memory

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#187]
serializing to turtle is apparently a memory-intensive process.  (current flybase serialization of only a partial graph dies during writing with 25M nodes).  this will either need to be tied to disk, or perhaps we elect to write other file formats instead of turtle if the graph size is too big.  

we need to test using the [sleepycat storage](https://github.com/RDFLib/rdflib/blob/master/rdflib/plugins/sleepycat.py) and or other methods that optimize further using [setstorage](https://github.com/osma/rdflib/blob/setstore/rdflib/graph.py)  (note some old discussion for memory issues found [here](https://groups.google.com/forum/#!topic/rdflib-dev/EZqiUs7qTUc).)

**Comment by kshefchek** [comment]
The streaming graph (streamed n-triples) implementation of the graph class should work for this, see https://github.com/monarch-initiative/dipper/pull/416
