### ISSUE TITLE
upgrade travis CI

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#192]
I notice that [build 184](https://travis-ci.org/monarch-initiative/dipper/builds/78322718) lists that it was on legacy infrastructure.

This should be upgraded:
http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

**Comment by kshefchek** [comment]
fixed with f6b3ca6703cc3309a810257477f1fd8087a11bd5
