### ISSUE TITLE
Update ZFIN to use fish

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/dipper#193]
ZFIN genotypes have changed from ZDB-GENO-000209-20 to ZDB-FISH-000209-20 and some files updated with _fish appended, for example
http://zfin.org/Downloads/wildtype-expression.txt

is now

http://zfin.org/Downloads/wildtype-expression_fish.txt

See: http://zfin.org/Downloads

**Comment by nlwashington** [comment]
I'm converting this ticket to be toward revising the ZFIN pipeline to accomodating the concept of FISH.  

their fish are basically giving identifiers to our "effective" genotypes.  This is a welcome change, but we'll need to refactor the any of the pipeline that might utilize morpholios and/or touch the genotypes.

**Comment by nlwashington** [comment]
@mbrush , this means that the morpholinos are pulled out of the environments.  as you may recall, we were keeping track of morpholinos as part of environment, in addition to it being in the extrinsic genotypes.

is it important to list the morpholino as a component of the environment object?  i _may_ be able to do something about this to recover them through some hacking, but not totally sure.

**Comment by nlwashington** [comment]
changes also to the wildtypes file to map the wiltype strain genotypes to fish ids (stocks?)
