### ISSUE TITLE
Consider replacing equivalent IDs in the RDF graph

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/dipper#197]
This ticket is for brainstorming purposes...

We could theoretically replace equivalent IDs in the RDF using sparql (see https://github.com/monarch-initiative/mckb/blob/bd44f23a8/mckb/sources/CGD.py#L618), based off of http://www.w3.org/TR/sparql11-update/#deleteInsert

For example, with KEGG genes, omim genes, orphanet diseases, it would be advantageous to use a standard ID across all sources, for example, NCBI gene ids.  To do this we would need to process equivalency information as the last step in creating the graph.

For example:

```
    <http://www.kegg.jp/dbget-bin/www_bget?hsa:105379264> a owl:Class ;
        rdfs:label "uncharacterized LOC105379264" ;
        OIO:hasExactSynonym "uncharacterized LOC105379264" ;
        rdfs:subClassOf OBO:SO_0000704 .
```

Then make the statement

```
    <http://www.kegg.jp/dbget-bin/www_bget?hsa:105379264> owl:equivalentClass <http://www.ncbi.nlm.nih.gov/gene/105379264> .
```

And then:

```
     self._replace_entity(self.graph, kegg_id, ncbi_id, self.bindings)     
```

This should be trivial in sources like KEGG which include this information.  But in other sources we would need to access files and functions from other sources, such as gene_info.gz from NCBI Gene.

**Comment by nlwashington** [comment]
Well, we're already working on this at the layer of processing the load into scigraph, where the initial annotations to the source-specific identifier is maintained and we can track the provenance of mapping the identifier over to one of the things it is equivalent to.  

The first attempt at this process was just tested and finished loading today; we are testing the next phase (loading into golr) now.

I am hesitant to overwrite the identifiers as we are losing a piece of provenance information.  Not to say that we won't eventually do it, but I hesitate to do it yet.

**Comment by nlwashington** [comment]
Also, if we do it at the scigraph layer, then we can have uniform processing of moving nodes by a set of rules (like always use the NCBI gene id as the "leader", or give preference to MGI when it's a mouse gene).  Otherwise, the user has to keep track of it at the data processing/dipper side, and they might not all be processed in the same way.

**Comment by kshefchek** [comment]
I think it's important to handle equivalent nodes in SciGraph regardless, I'm not suggesting this as a complete alternative, but just something that may be useful down the line to clean up the data.  In some cases this could be done without changing provenance if the source provides the equivalent mappings, for example, KEGG.  It's just something to keep in our back pocket.
