### ISSUE TITLE
association provenance model

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#200]
For any given association, we want to add provenance to the association.

Currently, we do this by adding a source (which is really a PMID) and an ECO code.  But these will all get folded into a proper provenance model.

This will require refactoring how we add the references (PMIDs) and ECO codes in all of the association models.  (Large-scale refactor will be a separate ticket.)

This ticket is to serve to flesh out the initial model, and code for the first implementation.

**Comment by mbrush** [comment]
Several related efforts are modeling experimental provenance and evidence for associations:
 * **Ontologies:** OBAN, PROV, ECO, OBI
 * **Datasets:** Monarch, EBI/CTTV (Centre for Therapeutic Target Validation) data,  Noctua/LEGO data, BRCA variant association data

Each effort has its own set of use cases, and has proposed different design patterns for modeling their data. Likely many other efforts are also developing ad hoc solutions to modeling experimental provenance. To what extent do we want develop a community model of experimental provenance and evidence that can be shared across efforts?   If we want to pursue an aligned approach, now is the time. Or should we just focus for now on implementing our own solution four our immediate needs?

**Some questions that are relevant either way:**
 1. Conceptually what are provenance and evidence? How are they different?  How are they related?
 2. What are our use cases and competency questions of these groups and the wider community for creating and using provenance and evidence information?
 3. What existing efforts can / should we leverage?
 4. Can we align design patterns that will meet needs of all in an interoperable way?

**Comment by mellybelly** [comment]
So very briefly, from my perspective, you want to reify the relationship between two entities with an evidence class. The evidence itself can have a variety of attributes (things like assay or p value or outcome), one of which is the provenance. But provenance is also transitive in the sense that evidence for an association can include information from other sources, that themselves have their own provenance.

**Comment by mbrush** [comment]
Latest notes on this model and proposed straw man can be found and commented on here:
https://docs.google.com/document/d/1W94ellFMfcm2nJVa8OCpNdlzacre77xzsfsrZ352p8s/edit#

**Comment by cmungall** [comment]
Compare with: https://github.com/geneontology/minerva/blob/master/specs/owl-model.md

Note RO:0002612 is only valid for owl axiom annotation. An analogous property would be used for OBAN.

**Comment by kshefchek** [comment]
https://github.com/monarch-initiative/SEPIO-ontology
