### ISSUE TITLE
add cmaps to repo and documentation

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#205]
We make cmaps available for each resource, to demonstrate the elements of any given data source, and how we turn it into a graph.  

These need a place to live for the public to view to understand our modeling, and should become official parts of our documentation.

@cmungall shall these just go into our git for dipper?  or live in a more monarch-specific location?

Once this location is determined, we will place completed cmaps in this location.

**Comment by kshefchek** [comment]
Cmaps are now in https://github.com/monarch-initiative/ingest-artifacts, this ticket has been superseded with https://github.com/monarch-initiative/dipper/issues/422
