### ISSUE TITLE
import gwas catalog

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#206]
EBI now dumps the gwas catalog annotated with EFO.  simple to bring in.  

@cmungall any chance EFO will get integrated with Upheno in any way?  if we import, will this get utilized in any meaninful way?

**Comment by cmungall** [comment]
We should be able to integrate the phenotype/trait part. I'll take a look once the dipper code is in, and will make sure we get in equiv axioms for everything

**Comment by nlwashington** [comment]
want me to add this for the [TG milestone](https://github.com/monarch-initiative/dipper/milestones/Thanksgiving%20data%20push)?

**Comment by cmungall** [comment]
done

**Comment by nlwashington** [comment]
note that some of the intronic variations seem to be missing the genes that they are contained within.  about 5%.  i have written to the gwas helpdesk to inquire if they will fix it.

**Comment by nlwashington** [comment]
annotations in the gwas catalog are listed in the source data according to the original SNP that was reported.  the catalog also indicates if the original SNP is merged/replaced with another SNP record that is more current.

at dipper-time, should i migrate the annotations to the "current' snp id, or leave them to the original snp and allow the scigraph-clique-migration plan take care of it?

**Comment by nlwashington** [comment]
note that some annotations are made to "kgp" ids and not standard "rs" ids.  a quick search tells me that the kgp ids are a result of the illumnia platform for the 1000Genomes project.  a mapping file is not yet readily available (though i just emailed illumina tech support to request it).  otherwise, we can try mapping based on genomic location.

**Comment by nlwashington** [comment]
also, when creating the associations, i make them between the variant (SNP rsid) and the EFO term(s), using the "contributes_to" relationship.

**Comment by nlwashington** [comment]
closing this.  refactoring any relationships will take place in another ticket.
