### ISSUE TITLE
add source biogrid

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#21]
add thebiogrid.org interactions.  these are both X interacts_with Y triples, and reified association objects with provenance.  see modeling ticket #19

**Comment by cmungall** [comment]
Yes, make a monarch prefix

**Comment by nlwashington** [comment]
at the moment, it takes <10  min to process the full biogrid.  i've temporarily added some code that will filter the data by taxid (but this should probably be removed in the future.) in commit 89f79bc

**Comment by nlwashington** [comment]
ok, monarch prefix used for associations in commit 3be2466

**Comment by nlwashington** [comment]
it took ~7 min to create the id mapping file for just mouse+human with Biogrid+ENSEMBL+NCBIGene+MGI ids.  Created 395K nodes.

**Comment by nlwashington** [comment]
this has been tested in SciGraph and the data appears to work.
