### ISSUE TITLE
Repeated rows in disease page under genes tab

### ISSUE THREAD

**Issue by yuanzhou** [monarch-initiative/dipper#216]
Went to http://beta.monarchinitiative.org/disease/OMIM:105830 and checked out the genes tab.

There are several repeated rows that contain the same info and same links.

![capture](https://cloud.githubusercontent.com/assets/195873/10762582/0c6562bc-7c9d-11e5-8863-63fd5a7d72ce.PNG)

**Comment by kshefchek** [comment]
This should be fixed in our beta golr load, but we have not yet pushed any configuration changes to the beta site (it's still running of our staging server).

**Comment by yuanzhou** [comment]
Thanks @kshefchek , maybe I posted this issue in the wrong place. It should be under monarch-app.
