### ISSUE TITLE
OMIM IRI's do not resolve

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/dipper#219]
See https://github.com/monarch-initiative/monarch-app/issues/1040 as a reference

OMIM IRIs are created via the curie mapping:
'OMIM' : 'http://purl.obolibrary.org/obo/OMIM_'

However, these IRIs do not resolve.  Should we be pointing to their page - http://www.omim.org/entry/{id} ?

**Comment by cmungall** [comment]
Can't be fixed until OCLC restore login

**Comment by kshefchek** [comment]
@cmungall should I put in a fix on the front end or will this be resolved before our release?

**Comment by cmungall** [comment]
Front end for now
