### ISSUE TITLE
refactor to remove duplicated test_ids

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#222]
the test_ids are currently found in two places:
-  test_ids.json in the /tests
-  conf.json that is not committed to the repo.  (conf.json also houses the API keys and other private information.)

we should remove the redundancy and streamline the code.

**Comment by kshefchek** [comment]
these are now in one place, https://github.com/monarch-initiative/dipper/blob/master/resources/test_ids.yaml
