### ISSUE TITLE
add decipher disease-gene-phenotype assoc

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#223]
DDD finally make their curated list of disease-gene assoc public:
https://decipher.sanger.ac.uk/files/ddd/ddg2p.zip

they unfortunately distribute this with only gene symbols (from gencode), so we will have to do the mapping to a proper identifier during ingestion.  we may be able to leverage the genomic coordinates (i think of the gene?  but unclear.) to help to confirm the gene id.

also note that there are phenotype terms in here.  @pnrobinson or @drseb do you know the provenance of these annotations?  here's a little example:

<pre>
#gencode_gene_name      mode    category        consequence     disease omim    ddg2p_id        pubmed_ids      hpo_codes
NSUN2   Biallelic       Probable DD gene        All missense/in frame   Autosomal- Recessive Intellectual Disability MRT5       611091  10055   22541559 ;22541562 ;21063731 ;22577224  HP:0000007 ;HP:0000252 ;HP:0000275 ;HP:0000276 ;HP:0000316 ;HP:0000319 ;HP:0000322 ;HP:0000331 ;HP:0000426 ;HP:0000430 ;HP:0000431 ;HP:0000448 ;HP:0000486 ;HP:0000506 ;HP:0000574 ;HP:0000581 ;HP:0000601 ;HP:0000664 ;HP:0000964 ;HP:0001250 ;HP:0001257 ;HP:0001260 ;HP:0001263 ;HP:0001347 ;HP:0001518 ;HP:0001761 ;HP:0001771 ;HP:0003236 ;HP:0004322 ;HP:0008070 ;HP:0008897 ;HP:0008936
</pre>

**Comment by nlwashington** [comment]
i've emailed the decipher list to request that they (1) describe their HP curation process a bit more (like are these manually curated or computationally derived or imported?) and (2) to add gene ids, or at minimum information about the gencode version that is used.

**Comment by nlwashington** [comment]
someone should review this too, but i found their overarching [license](https://decipher.sanger.ac.uk/legal#overview) on the Deicpher website to be [CC-NC-ND](http://creativecommons.org/licenses/by-nc-nd/2.5/).   anyone else care to comment if the data files from https://decipher.sanger.ac.uk/about#downloads/data (as opposed to the web content) would be restricted under this license?

**Comment by nlwashington** [comment]
The ddg2p file is not documented, and therefore i am unsure what the HPO annotations represent in the file (as in, are they disease phenotypes or gene phenotypes?).  I think it is best to be conservative and not include them in the output until this can be clarified.  Therefore, a first pass will only include the disease-gene associations, together with the PMIDs.

**Comment by drseb** [comment]
I once had contact with them and I think they have a very strict licence that allows you to visualise some data on the web, but not make the data available for download in any format. (Data Display Agreement)

**Comment by nlwashington** [comment]
thanks @drseb.  I've just sent a clarification message to ask what license is attached to the contents of that zip file (which is non-patient-level).

**Comment by nlwashington** [comment]
note that ~6% (115/1800) disease-gene associations have an unmapped disease id, and no accompanying HPO ids.  for example:
<pre>
['ACTA1', 'Biallelic', 'Probable DD gene', 'All missense/in frame', 'Nemaline myopathy 3', '', '13889', '10508519', '']
</pre>
which you can see here:
https://decipher.sanger.ac.uk/gene/ACTA1#overview/clinical-info

In this case, the label of the disease appears to match [OMIM:161800](http://omim.org/entry/161800), but for whatever reason isn't included in the file.

We could consider mapping these to OMIM and/or DO classes some other way.

**Comment by kshefchek** [comment]
We never incorporated this due to licensing/legal ambiguities. Ensembl now offers this under a more clear license: https://www.ebi.ac.uk/gene2phenotype.  Replacing this ticket with https://github.com/monarch-initiative/dipper/pull/602
