### ISSUE TITLE
Add encrypted API keys to travis config

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/dipper#230]
Encrypting our API keys with travis is one way we could test sources that require API keys to download data.  Does this impose any security risks?

See https://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables

**Comment by jmcmurry** [comment]
@DoctorBud  @kltm perhaps you could weigh in?

**Comment by kltm** [comment]
My read of it is that encrypted environment variables work just fine (just upload your key), but you need to write tests to deal with the fact "that encrypted environment variables are not available for pull requests from forks." Which, if I understand your current workflow, is a bit of an issue.

**Comment by kshefchek** [comment]
We could still follow the PR workflow and just branch instead of fork.  I don't think @nlwashington has adopted the git flow model here at this point anyway.

**Comment by kshefchek** [comment]
This was never added but we've worked around it in various ways, closing for now.
