### ISSUE TITLE
Version dipper package

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/dipper#234]
It would be useful to be able to reference a version of dipper in a given release.  While there's more needed to actually recreate output from this pipeline (versions of all underlying sources + the version of dipper), I think this will be a good starting point.

**Comment by mellybelly** [comment]
agree, and also in for each release you'd also have the data version and ontology/import chain version, since the dipper script depends on coordination amongst these three

**Comment by kshefchek** [comment]
done, see duplicated ticket https://github.com/monarch-initiative/dipper/issues/450
