### ISSUE TITLE
update OMIM to remove dependency on omim.txt

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#237]
omim source no longer dumps the omim.txt file, which we were using to fetch the omim entity identifiers.  we will need to fix the code to remove this dependency.

**Comment by TomConlin** [comment]
There is: 
http://omim.org/static/omim/data/mim2gene.txt
which has:
       MIM_numbers, NCBI_Gene_IDs, Ensembl_Gene IDs, HGNC_Gene_Symbols
it may be sufficient to replace the missing omim.txt

**Comment by kshefchek** [comment]
We're hashing out the licensing issues to regain access to omim files.

**Comment by cmungall** [comment]
no disease labels..

**Comment by TomConlin** [comment]
It looks like we were already making api calls with the ids we got. 
pulling the label for the (phenotype) ids at the same time is not that far out of the way.
unless we are not licensed to make api calls any more then it is moot.

**Comment by nlwashington** [comment]
FYI, the former use of omim.txt was specifically to get the ids in use. I
then queried their API for most of the rest. This was to limit the requests
to a useful subset of the 100000...700000. It was certainly a lot of
overhead just to get the ids, but definitely less time than iterating over
600K ids of which a very small fraction were actually in use. mim2gene
would be insufficient to specify all ids used by omim.

**Comment by cmungall** [comment]
ah of course, in that case we can do use the mim2gene

**Comment by TomConlin** [comment]
??? can do use


counts of the types of id in mim2 gene  are:
  15199 gene
   6295 phenotype
   1808 predominantly phenotypes
   1201 moved/removed
     85 gene/phenotype

**Comment by nlwashington** [comment]
I have an old txt file at home, I can doublecheck tonight.

Stats here indicate 23,389 entries:
http://omim.org/statistics/entry

Those numbers seem to align (your count  totals 23,387, with the exception
of "moved") which is awesome. So I guess that works!

Be gone, omim.txt!

On Feb 24, 2016 10:36 PM, "Tom Conlin" <notifications@github.com> wrote:
>
> ??? can do use
>
> counts of the types of id in mim2 gene are:
> 15199 gene
> 6295 phenotype
> 1808 predominantly phenotypes
> 1201 moved/removed
> 85 gene/phenotype
>
> —
> Reply to this email directly or view it on GitHub.

**Comment by kshefchek** [comment]
@nlwashington any chance you have saved a cache of the raw files used to populate the current versions of scigraph?  We seem to have lost this in move and it would be good to store these as backups.

**Comment by TomConlin** [comment]
OMIM is running using mim2gene.txt in place of  omim.txt.

Once tested this may be closed.
