### ISSUE TITLE
add runtime configurability

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#25]
We need a way to run dipper under various configurations.  This could be handled either with a configuration file or with a command-line interface with flags (or even both!)

In particular, the following should be configurable in the first-pass:
1.  specification of sources to be run (should default be all?)
2.  help that lists the available sources 
3.  format of data output (this is currently hard-coded to turtle, but could be configurable to other formats)
4.  forcing of re-downloading of data sources and/or re-generation of triples, even if the software thinks that the data is okay.
5.  a test-run mode with a user-specified limit on the number of records processed.  (default to 100?)

**Comment by cmungall** [comment]
How do I run it at the moment?

**Comment by nlwashington** [comment]
on the commandline you can say
  python3 __init__.py
or in your ide, do the same.  it's basically a main.

**Comment by nlwashington** [comment]
all of the above can be done in the code now, it just isn't available on the commandline without un/commenting the code.

**Comment by kshefchek** [comment]
@julesjacobsen I'm open to suggestions.  I was going to start with argparse to see if that suites our needs.

**Comment by kshefchek** [comment]
@nlwashington @bryanlaraway I've added the command line options --sources --limit --parse_only, for example
to disable writing
--sources mgi,ZFIN --limit 100 --parse_only
for writing
--sources mgi,ZFIN --limit 100

As of right now this would be the only way to run the script, but I can re-enable the way we were doing things before for testing if you would like.

I still have some other things to add but just made the first commit.

**Comment by nlwashington** [comment]
added in commit c8cf9d5e5a76ae6d1502741ca623176c06ddd71f

**Comment by nlwashington** [comment]
can you add a main so that on the commandline it can be executed like:
<code>    dipper --sources mgi --limit 100</code>
right now it runs like:
<code>    python3 \__init__.py --sources mgi --limit 100</code>

**Comment by kshefchek** [comment]
I've added a main function and a shebang so it can be ran like the above example.  Would this work or do we want to have some sort of build script so this is more platform independent?

**Comment by kshefchek** [comment]
added a --force option with 990b6826415c742e3a9818b4234fd326e11dd26f to force redownloads.  So far only implemented for downloading remote files, so no postgres support for MGI.  I also went through and updated the fetch() functions for each class.

**Comment by kshefchek** [comment]
Updated --parse_only to turn fetching on/off (instead of writing).

**Comment by nlwashington** [comment]
all of the above are added.  closing for now.  new options should be new tickets.
