### ISSUE TITLE
Design pattern for sex-specific G2P associations

### ISSUE THREAD

**Issue by mbrush** [monarch-initiative/dipper#255]
Some sources such as IMPC assess phenotypes separately on male vs female cohorts of mice, and assign phenotypes separately to male vs female genotypes. We need to model the sex-dependence of the genotype so we can capture when a G is associated with a P only in one sex, when it has explicitly been shown to affect both males and females, and when G2Ps are reported independent ofsex (e.g. associations in sources such as MGI). Below we outline two approaches.

**Approach 1**: Create sex-qualified genotypes (male intrinsic genotype, female intrinsic genotype) from which to hang sex-specific phenotypes. Intrinsic genotypes that are not qualified by would by contrast be considered 'sex-agnostic'. This approach would would lead to the following graph for the association of the _decreased erythrocyte cell number_ phenotype with the _'Mysm1<tm1a(KOMP)Wtsi>/Mysm1<tm1a(KOMP)Wtsi [C57BL/6/WTSI]'_ genotype (in the case that it is relevant to both male and female genotypes). 

![concepts_012](https://cloud.githubusercontent.com/assets/5184212/12939298/0fb58b8a-cf73-11e5-8126-dceb6646bf35.jpg)

Here, the phenotype asserted on the sex-qualified genotypes gets propagated to its sex-agnostic genotype part, where it would be aggregated with other phenotypes that may be asserted at this level. This approach adds some overhead in creating more genotype classes, more genotype individuals, and more property chains to support phenotype propagation.  But it gives us a node for the sex-qualified genotype that may be useful for future use cases or analyses.

**Approach 2**:  A simpler approach is to hang the sex of the organism as a qualifying context on the association itself, alongside any qualifying environmental or developmental stage contexts. For a phenotype tested without regard to sex, no sex-qualifier would be captured (A).  For a phenotype specific to males, only a male qualifier would be recorded (B).  For a phenotype specific to females, only a female qualifier would be recorded (C). And for phenotypes explicitly tested and observed in makes and females, the two separate associations in (B) and (C) would be made (or perhaps a single association with male and female qualifiers, or a single 'male and female' qualifier?).

![concepts_014](https://cloud.githubusercontent.com/assets/5184212/12996902/2db78da0-d0e9-11e5-8310-2b4796f53bf8.jpg)

This approach would also allow us to distinguish when a phenotype affects only males, only females, has explicitly been shown to affect both males and females, or has only been tested independently of organism sex. The modeling, and the propagation logic needed are both much simpler.  But it feels like kind of a cop out.

@mellybelly @cmungall @nlwashington -  Looking for feedback as to what pattern is preferred.  What query or analytical use cases may favor one approach over another?  Are there other approaches we should consider?

**Comment by mbrush** [comment]
Also, consider display of things in Monarch app w.r.t. creating male and female genotypes. See 'Genotypes' tab for https://monarchinitiative.org/variant/MGI:4362924

And what makes sense on a genotype page for the IMPC genotypes? Separate pages for male vs female genotypes, and also one for the sex-agnostic genotype?  Or just one for the agnostic genotype, with a column for the 'sex' context (male, female, not tested, male + female)?

**Comment by pnrobinson** [comment]
I think that "sex intrinsic genotype" is confusing, since for most of the models we are talking about, the relevant part of the genotype is the same for both sexes, and other factors are responsible for the sexual dimorphism. (Sex intrinsic genotype sounds like a gonosome) Therefore, I would favor alternative 2.

**Comment by pnrobinson** [comment]
Another issue is that it would be worthwhile to capture the statistical evidence in more detail. The studies performed at the IMPC have small samples sizes, many potential sources of bias, and downstream users of the data should have this information. The annotation of a more traditional model (based on publication) is often more certain.

**Comment by kshefchek** [comment]
We have implemented both approaches at the moment.  However, perhaps we should consider moving to approach 2.  Closing as the core issue is resolved.
