### ISSUE TITLE
Missing basis for inference

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/dipper#262]
Please excuse me if there's a duplicate ticket, but I can't figure out what the trail is that got us to these inferred relationships.

http://monarchinitiative.org/gene/NCBIGene:3549

<img width="1338" alt="screen shot 2016-02-10 at 11 09 39 am" src="https://cloud.githubusercontent.com/assets/3658863/12958515/eff64c66-cfe6-11e5-97f5-c94b38817258.png">

**Comment by kshefchek** [comment]
At one point we would list sources that were used to generate an inferred relationship, but our original method did not scale and has yet to be replaced.  So for now these are empty.  @jnguyenx is there a ticket to track the work on the association code in the golr-loader?

Ideally this would be a good place for a DAG view when that becomes feasible.

**Comment by jnguyenx** [comment]
https://github.com/SciGraph/golr-loader/issues/13

That's on my high priority list.

**Comment by kshefchek** [comment]
Eco codes, sources, and references are now populated.  This view is not great but this is referenced in the monarch-app repo, eg https://github.com/monarch-initiative/monarch-app/issues/1604
