### ISSUE TITLE
Static Analysis refactoring

### ISSUE THREAD

**Issue by TomConlin** [monarch-initiative/dipper#266]
Since I have had have limited exposure to python/python3 and am unfamiliar with the dipper code base, one way to address both while being exposed to accepted best practices is to run the code through static analyzers such as ```pylint```  and reduce the number of complaints it makes.  Doing this before continuing with the dipper part of the ClinVar XML load should result in a more consistent script on my part. 

This refactoring may result in a fair amount of churn without any change in behavior. But the result should be more consistent which will make autodoc-ing tools such as ```pycallgraph``` happier. 

Kent has agreed this is not a terrible idea but everyone who might care should have an opportunity to weigh in.

**Comment by cmungall** [comment]
If this can be done quickly seems fine, but don't want to get sucked into minutiae

**Comment by TomConlin** [comment]
Done see #279
