### ISSUE TITLE
Google Code references

### ISSUE THREAD

**Issue by TomConlin** [monarch-initiative/dipper#268]
References to Google Code should be removed

This one has been commented out
but it would be nice to know if it can be replaced before it is deleted  

    dipper/sources/ZFIN.py:  
    # old     'url': 'https://phenotype-ontologies.googlecode.com/svn/trunk/src/ontology/zp/zp-mapping.txt',},  

This one is in a comment
but it would be nice to know if it can be replaced before it is deleted  

    dipper/sources/EOM.py:    
    Monarch-curated data for the HP to EOM mapping is stored at
     https://phenotype-ontologies.googlecode.com

This one is in code and cannot be right.   

    dipper/sources/EOM.py:           
    'url': 'https://phenotype-ontologies.googlecode.com/svn/trunk/src/ontology/hp/mappings/hp-to-eom-mapping.tsv'  

guessing something like this would work instead:    

    https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/master/src/mappings/hp-to-eom-mapping.tsv

**Comment by TomConlin** [comment]
@mbrush do you have the new names/locations for the ontologies mentioned?

**Comment by TomConlin** [comment]
changing the one in dipper/sources/EOM.py to 
https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/master/src/mappings/hp-to-eom-mapping.tsv

**Comment by jmcmurry** [comment]
@TomConlin can this be closed then?

**Comment by TomConlin** [comment]
I took the reference out of the comment in EOM.py will push it eventually

no resolution on the deadwood in   
dipper/sources/ZFIN.py:  
```# old     'url': 'https://phenotype-ontologies.googlecode.com/svn/trunk/src/ontology/zp/zp-mapping.txt',},  ```

it has been removed,  but no word on what it should have been

closing
