### ISSUE TITLE
add source ncbi genes

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#27]
need to add in the ncbi genes.  see disco nif-0000-02801
here's what we currently pull into disco related to genes:

wget -nv ftp://ftp.ncbi.nih.gov/gene/DATA/gene_info.gz
wget -nv ftp://ftp.ncbi.nih.gov/gene/DATA/gene_history.gz
wget -nv ftp://ftp.ncbi.nih.gov/gene/DATA/gene2pubmed.gz

for the initial pass, let's restrict genes to our favorite organisms.

let's just do the above for now, then augment with the following later (another ticket)
wget -nv ftp://ftp.ncbi.nih.gov/gene/GeneRIF/generifs_basic.gz
wget -nv ftp://ftp.ncbi.nih.gov/gene/GeneRIF/interactions.gz

**Comment by nlwashington** [comment]
@cmungall for the gene2pubmed, what is the appropriate kind of triple to make?  (as in what is the relationship here?)

**Comment by nlwashington** [comment]
how about 'is_about' (IAO:0000136)
http://www.ontobee.org/browser/rdf.php?o=IAO&iri=http://purl.obolibrary.org/obo/IAO_0000136

**Comment by selewis** [comment]
This same relationship (might) be useful for gene2pubmed when it's used for
GO evidence. Isn't any article essentially used as evidence (since it
describes some experiment that was done) for some characteristic of the
gene (or other biological entity).

Question is whether or not we need to indicate what particular gene
characteristic(s) the particular gene2pubmed relationship is relevant for.

-S

**Comment by mellybelly** [comment]
I think is_about is fine for this purpose, the paper is about the gene. The GO evidence is different, you have to read the paper and understand the evidence, which is a more deeper description of what evidence is presented than a simple reference to a gene. We often use is_about to refer to the relationship between a document and any of its subjects.

**Comment by nlwashington** [comment]
the only information that is available to me is that gene X is related to pub Y.  other than that, i don't know why the gene is linked to the publication.  
for association / annotation statements  (like gene G has_phenotype P, or gene G <some rel> GOterm O), these are reified and attached to a source S (pmid).  
but this example is different.

**Comment by nlwashington** [comment]
there's also 'mentions' : http://www.ontobee.org/browser/rdf.php?o=IAO&iri=http://purl.obolibrary.org/obo/IAO_0000142

**Comment by mellybelly** [comment]
prefer is_about- more generic and more widely used.

**Comment by selewis** [comment]
Right, but what I am trying to say is that (since it is an actual ontology)
that we can use the broader class (is_about), but then for GO_evidence use
a subclass of is_about. Plus there are certainly other sub-classes of
is_about that would also be useful.

-

**Comment by selewis** [comment]
What's the difference between them. 'mentions' seems vaguer.



On Fri, Jan 16, 2015 at 1:39 PM, Nicole Washington <notifications@github.com

**Comment by nlwashington** [comment]
here's the final output parts:
    <http://www.ncbi.nlm.nih.gov/gene/488> a owl:Class ;
    rdfs:label "ATP2A2" ;
    faldo:location _:12q2411,
        "12q24.11" ;
    OBO:RO_0002162 <http://www.ncbi.nlm.nih.gov/taxonomy/9606> ;
    OBO:RO_0002205 <http://www.hprd.org/protein/00161> ;
    dc:description "ATPase, Ca++ transporting, cardiac muscle, slow twitch 2" ;
    OIO:hasExactSynonym "ATPase, Ca++ transporting, cardiac muscle, slow twitch 2",
        "DAR" ;
    OIO:hasRelatedSynonym "ATP2B",
        "ATPase, Ca++ dependent, slow-twitch, cardiac muscle-2",
        "DAR",
        "DD",
        "SERCA2",
        "SR Ca(2+)-ATPase 2",
        "calcium pump 2",
        "calcium-transporting ATPase sarcoplasmic reticulum type, slow twitch skeletal muscle isoform",
        "cardiac Ca2+ ATPase",
        "endoplasmic reticulum class 1/2 Ca(2+) ATPase",
        "sarcoplasmic/endoplasmic reticulum calcium ATPase 2" ;
    rdfs:subClassOf OBO:SO_0001217 ;
    owl:equivalentClass ENSEMBL:ENSG00000174437,
        OBO:OMIM_108740,
        <http://www.genenames.org/cgi-bin/gene_symbol_report?hgnc_id=HGNC:812> .

    <http://www.ncbi.nlm.nih.gov/gene/1035> a owl:Class ;
    rdfs:label "CDN1" ;
    OBO:IAO_0100001 <http://www.ncbi.nlm.nih.gov/gene/578> ;
    owl:deprecated "true"^^xsd: .

    <http://www.ncbi.nlm.nih.gov/pubmed/10791558> a owl:NamedIndividual ;
    OBO:IAO_00000136 <http://www.ncbi.nlm.nih.gov/gene/10>,
        <http://www.ncbi.nlm.nih.gov/gene/9> .
