### ISSUE TITLE
Coriell URL resolves but seems to be incorrect 

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/dipper#272]
https://catalog.coriell.org/0/Sections/Search/Sample_Detail.aspx?Ref=ND34391
Clicked on from here: 
http://monarchinitiative.org/model/Coriell:ND34391

@kshefchek is this is a provider-side issue? Other Coriell links from http://monarchinitiative.org/gene/NCBIGene%3A6622#models are fine.

**Comment by TomConlin** [comment]
ND34391 must have appeared in a previous snapshot of Coriell as it does not exist in the data fetched from there this afternoon.

**Comment by jmcmurry** [comment]
And we've come full circle. https://github.com/monarch-initiative/dipper/issues/260
I will close this ticket instead.
