### ISSUE TITLE
Add data source ClinVar XML

### ISSUE THREAD

**Issue by mbrush** [monarch-initiative/dipper#276]
Our initial ingest of ClinVar (see #7) used a tsv file that was missing much of the data only captured in their XML dumps.  Our second pass will leverage the XML data, and include full evidence and provenance metadata.

xml data dump: ftp://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/ClinVarFullRelease_2015-12.xml.gz
xsd schema: ftp://ftp.ncbi.nlm.nih.gov/pub/clinvar/xsd_public/ 
data dictionary: http://www.ncbi.nlm.nih.gov/projects/clinvar/ClinVarDataDictionary.pdf

**Comment by mbrush** [comment]
Issues raised in #269 related to where in the data pipeline to merge/collapse 'equivalent' associations that claim the same fact under a single association node.   As of March 3, consensus is to merge late, at the UI level - so our DIPper pipeline will not perform this merge in the data that gets output as ttl and dumped into SciGraph. While the consensus is that this is the easiest path forward from a technical perspective for Monarch needs I would advocate that for the purposes of any linked data we provide to the community, we create a rdf dataset where equivalent associations are merged.

**Comment by mbrush** [comment]
Diagram of the initial proposal for structuring one ingested Monarch:association (which correspond for now to a single ClinVar SCV):

![clinvar_pass_1 3-3-16](https://cloud.githubusercontent.com/assets/5184212/13510566/f7e689fc-e145-11e5-8cdf-ef85d6465265.jpg)

**For our first pass at ingesting this data we will:**

1.  Bring in the individual SCVs as instances of oban:associations (but not group SCVs making the same association  under a merged association node).

2. Ingest only SCVs using the five relationships from the ACMG classification  guidelines (pathogenic, likely pathogenic, benign, likely benign, uncertain significance). We will created five separate GENO object properties relationships to use in our associations (rather than previous proposal of collapsing these five into three) 

3. Capture the following evidence and provenance information:
 * the asserting agent/organization (e.g. ENIGMA, Counsyl)
 *  classification methods/guidelines used (e.g. 'ENIGMA BRCA1/2 Classification Criteria')
 * dates assertions were created, last updated, and last evaluated.
 * supporting data for now will include only publications
 * the 'MethodType' ClinVar uses to describe type of study that generated data/evidence (one of 'clinical testing', 'literature only', 'reference population', 'research', 'curation', or 'case-control' (not used in BRCA subset))

4. (For Rd 2?) Create links of 'equivalence' (sameAs? equivalent_to?) and 'contradiction' (contradicts) between associations that assert the same, or contradictory facts, respectively. This will support merging of equivalent associations in subsequent processing steps, and support links from associations to refuting evidence.

**Comment by kshefchek** [comment]
https://github.com/monarch-initiative/dipper/pull/334
https://github.com/monarch-initiative/dipper/pull/335
