### ISSUE TITLE
Refactor code to use new OBAN property

### ISSUE THREAD

**Issue by mbrush** [monarch-initiative/dipper#278]
We have been using OBAN:association_has_object_property  to link Monarch associations to its predicate. But this is not the intended use of this property.  OBAN has now added a new property specifically to link associations to predicates they use: OBAN:association_has_predicate.

All DIPper code needs to be refactored to replace all usage of OBAN:association_has_object_property with OBAN:association_has_predicate.  Should be straightforward as there should be no valid use of OBAN:association_has_object_property.

Full IRIs for these are:
http://purl.org/oban/association_has_object_property
to be replaced with
http://purl.org/oban/association_has_predicate

**Comment by kshefchek** [comment]
Bump, we should fix this in the next release.
