### ISSUE TITLE
Correct curie mapping for monarch

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/dipper#284]
https://github.com/monarch-initiative/dipper/blob/master/dipper/curie_map.yaml#L2

Should be:

`'': 'https://monarchinitiative.org/:'`

(Note that https and the www shouldn't be important when https://github.com/monarch-initiative/monarch-devops/issues/34 is fixed)

**Comment by cmungall** [comment]
Do we even need this - shouldn't all prefixes be declared?

if we do need a base prefix, we should consider doing this with `@base` or `@vocab` as per the json-ld context spec

**Comment by kshefchek** [comment]
Agreed, it would be nice if we could do away with these.  My understanding is that this was a first pass to resolve issues like this: https://github.com/monarch-initiative/dipper/issues/8

**Comment by jnguyenx** [comment]
The issue happens when we have identifier with the monarch prefix.

For example on the overview page of
https://beta.monarchinitiative.org/genotype/:_fbgenotypekey86496

The monarch-app will use a SciGraph vocabulary service to expand the given
curie to a full iri. It'll output
http://www.monarchinitiative.org/_fbgenotypekey86496 which will result as a
not found.


As Kent mentioned, maybe there's a better fix to do in the data itself.

**Comment by jnguyenx** [comment]
Let's wait for a proper fix from #8
