### ISSUE TITLE
Run diff on OMIM OMIM-HPO vs. HPO OMIM-HPO profiles

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/dipper#287]
OMIM is running their own text matching pipeline to assign HPO terms to their clinical synopsis terms, thereby auto-creating OMIM HPO profiles. These may or may not be similar to our automated+manual pipeline. 

Ideally we would provide these back to them rather then them creating a different set. Note that this set is available via their API and is being used to generate content in MedGen.

API keys are easy to get here: http://omim.org/help/api
I have one if anyone needs.

So.. need to compare the data in the OMIM API: http://api.omim.org/api/search/clinicalSynopsis
vs. what we have here: https://github.com/monarch-initiative/hpo-annotation-data

@kshefchek or @TomConlin perhaps you can help? 
@cmungall @drseb please provide requirements for the analysis. 
I think we want to know things like how many are identical, how many are missing from either set, and for those with mismatches what is the difference based on graph distance or some other measure.

**Comment by cmungall** [comment]
I think any of us could do the analysis quickly. The stumbling block for me (and I'm guessing @drseb) is figuring out the API, which I haven't done before. Less easy than just downloading a file and analyzing it. 

It looks like we have 99% of this done in _transform_entry in OMIM.py. It may be easiest to simply add this to our dipper dump (of course we would surface the OMIM HPO assignments in a way that would not confict with ours). Our we can just make this an options.  if someone who runs this can just post a snippet of the json that gets fed into _transform se can immediately what needs to be done

**Comment by TomConlin** [comment]
Kent will have uses the OMIM API but have less time for it now than I do. 
I will also be stumbling around figuring out either the API or OMIM.py or even if  OMIM.py has access to the new API keys yet.  Will start there.

**Comment by drseb** [comment]
It would be great if you could try to generate a OMIM-ID to HPO-ID mapping file and send this to @cmungall or me - we will generate some statistics.

**Comment by TomConlin** [comment]
have some bureaucratic tasks first, then I'll have a go

**Comment by cmungall** [comment]
Or even the complete ttl with the HPs added, whatever is fastest

**Comment by TomConlin** [comment]
Have replaced the functionality of the no longer available OMIM.txt.Z with mim2gene.txt
 running (limping) OMIM.py to completion results in no HP: identifiers in the 800k triples produced
Requested and received a key to access morbidmap.txt (expires a year from today)
(runing now > 30min)

I have yet to figure out a replacement for the no longer existing phenotypicSeriesTitles.txt.
I have requested ftp download of the full .json file instead of the 20/request http calls we are doing now.

**Comment by TomConlin** [comment]
@cmungall @drseb 
Without establishing the replacement for 'phenotypicSeriesTitles.txt' there are no HPO identifiers in the  output from OMIM.py.
I have accumulated and joined all the omim json files from their API and learned enough [jq](https://stedolan.github.io/jq/manual/)  to match omim numbers with sets of  ... semi structured text strings containing HPO identifiers.  

[OMIM_HPO.json.zip](https://github.com/monarch-initiative/dipper/files/216042/OMIM_HPO.json.zip)

The data is structures as an simple array of arrays, omims without any HPO matches are included with an explicit empty array of matches 
```
[
  300049,
  [
    "Bicuspid aortic valve {SNOMEDCT:72352009} {ICD10CM:Q23.1} {UMLS:C0149630} {HPO HP:0001647 UMLS:C0149630}",
    "X-linked dominant {UMLS:C1847879} {HPO HP:0001423}",
    "Coagulopathy {SNOMEDCT:362970003,64779008} {ICD10CM:D68.9} {ICD9CM:286} {UMLS:C0005779} {HPO HP:0003256}",
    "Mental retardation, mild (in some patients) {UMLS:C3149612} {HPO HP:0001256 UMLS:C0026106};",
    "Neuronal migration disorder {UMLS:C1837249} {HPO HP:0002269 UMLS:C1837249}",
    "Patent ductus arteriosus {SNOMEDCT:253686000} {UMLS:C3495549} {HPO HP:0001643 UMLS:C0013274};"
  ]
]
[
  600092,
  [
    "Narrow, bell-shaped thorax {UMLS:C1865186} {HPO HP:0001591 UMLS:C1865186};",
    "Trapezoidal shaped vertebral bodies {UMLS:C4025171} {HPO HP:0005621}; Abnormal clavicles {UMLS:C4021792} {HPO HP:0000889};",
    "Cerebellar vermis hypoplasia {UMLS:C1840379} {HPO HP:0001320 UMLS:C1865061};",
    "Iris hypoplasia {SNOMEDCT:95714006} {UMLS:C0344539} {HPO HP:0007676 UMLS:C0344539}; Optic disc coloboma {SNOMEDCT:17541006,44295002} {ICD10CM:H47.319,H47.31,Q14.2} {ICD9CM:377.23} {UMLS:C0155299};",
    "Micromelia {SNOMEDCT:74370006} {UMLS:C0025995} {HPO HP:0002983 UMLS:C0025995}; Short metacarpals and phalanges;",
    "Male pseudohermaphroditism {SNOMEDCT:111332007} {ICD10CM:Q56.1} {UMLS:C0238395} {HPO HP:0000037 UMLS:C0238395};",
    "Microcephaly {SNOMEDCT:1829003} {ICD10CM:Q02} {ICD9CM:742.1} {UMLS:C0025958} {HPO HP:0000252 UMLS:C0025958} {EOM ID:8ae2118220c1308f IMG:Microcephaly-small.jpg};"
  ]
]
[
  157147,
  []
]

```

for the masocistic the command is: 
    ```jq '.[].omim.entryList[].entry|[.mimNumber , [..|strings|match(".*HPO HP:.*"; "gn").string]]' omim.json > OMIM_HPO.json```

**Comment by cmungall** [comment]
Thanks Tom

I can't unzip the zip

But I think we can infer what the procedure is and where we would differ.

First, we add value when we combine with Orphanet, or our own manual HPO annotation. It's easy to filter these and to show the difference here

For the subset that comes from OMIM, it looks like they are doing some text mapping of their text field, so this would be roughly comparable to our process here. @drseb would know the nuances of our approach and could hone in on a case where we expect to see a difference

**Comment by TomConlin** [comment]
GH does not accept the upload with a .json extension and suggests what it will allow including .zip (but not gzip)  
the zip used is:  
```
zip -v
Copyright (c) 1990-2008 Info-ZIP - Type 'zip "-L"' for software license.
This is Zip 3.0 (July 5th 2008), by Info-ZIP.
Currently maintained by E. Gordon.  Please send bug reports to
the authors using the web page at www.info-zip.org; see README for details.

Latest sources and executables are at ftp://ftp.info-zip.org/pub/infozip,
as of above date; see http://www.info-zip.org/ for other sites.
...
```

The command used to create the .zip was:  
```
zip  < OMIM_HPO.json > OMIM_HPO.json.zip
```

the .zip reports as:  
```
file OMIM_HPO.json.zip 
OMIM_HPO.json.zip: Zip archive data, at least v3.0 to extract
```
and unsurprisingly works fine for me just clicking on it.
I can put the file up elsewhere  or here as an uncompresses .txt if it continues to be problematic.

**Comment by drseb** [comment]
I also cannot unzip the file.

**Comment by TomConlin** [comment]
@mellybelly was also unable to open, so here it is with a .txt extension.

[OMIM_HPO.json.txt](https://github.com/monarch-initiative/dipper/files/237219/OMIM_HPO.json.txt)

**Comment by drseb** [comment]
thanks @TomConlin 

@cmungall can you run some comparisons or should I?

**Comment by TomConlin** [comment]
@drseb  I would not mind being privy to your process if you do

**Comment by drseb** [comment]
> @drseb I would not mind being privy to your process if you do

ah sure @TomConlin .

I would just take your file and compare it to the data contained here: https://github.com/monarch-initiative/hpo-annotation-data/tree/master/rare-diseases/annotated

There is a file for each OMIM entry (ignore the DECIPHER-XX.tab).

> For the subset that comes from OMIM, it looks like they are doing some text mapping of their text field, so this would be roughly comparable to our process here. @drseb would know the nuances of our approach and could hone in on a case where we expect to see a difference

 E.g.: Does OMIM also return negative annotations with their API? (i.e. patients with that disease do never have HPO:xxx)


Further steps would be decided when having had a first glance at the results.

**Comment by TomConlin** [comment]
@cmungall @drseb @mellybelly 
Please humor me and test opening this ".zip" file which is _not_ created with a zip utility but a renamed '.gz' file created with gzip.

[OMIM_HPO.json.zip](https://github.com/monarch-initiative/dipper/files/237239/OMIM_HPO.json.zip)

**Comment by drseb** [comment]
@TomConlin works perfect for me

**Comment by TomConlin** [comment]
figures...

**Comment by cmungall** [comment]
Can't right now I'm afraid

**Comment by TomConlin** [comment]
I will get something together based on DrSeb's lead and Mallissa's Qs

**Comment by drseb** [comment]
@TomConlin I removed the links to the files, as it violates OMIM-license to put such a file on a public place like this repo (dipper). (You probably should remove the file from any place where it is publicly available). I also suggest to move this ticket to private repo - the best option seems  https://github.com/monarch-initiative/hpo-annotation-data

**Comment by TomConlin** [comment]
moved to #https://github.com/monarch-initiative/hpo-annotation-data/issues/107
