### ISSUE TITLE
wormbase has None as synonym

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/dipper#290]
I guess that this None is the python null value.

`wormbase.nt:362649399:<http://identifiers.org/wormbase/WBGene00001490> <http://www.geneontology.org/formats/oboInOwl#hasExactSynonym> "None" .`

**Comment by TomConlin** [comment]
I expect there are many more.
I have included a guard in dipper/utils/GraphUtils.py addSynonym()
which will prevent this in all the datasets.
We need more of of these precautions 

It is in my repo 
https://github.com/TomConlin/dipper/blob/master/dipper/utils/GraphUtils.py

It will get a PR when I get testing worked out.
