### ISSUE TITLE
Need to pull in Reactome data

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/dipper#291]
As a first step towards phenotype profile matching against pathways, and also vis integration with Reactome. @cmungall @kshefchek @jnguyenx

**Comment by cmungall** [comment]
For Noctua we're looking at a non-lossy or close to non-lossy transform: https://github.com/geneontology/noctua/issues/37

Here I assume we want a simple lossy set of associations: gene G involves in pathway P

Of course this will overlap with GO BP annotations (some of which may come from R in the first place).

For the monarch case, I think a simple SPARQL query over the reactome biopax RDF should suffice

**Comment by mellybelly** [comment]
I think it can be simple, but we might want to leverage negatively regulates and positively regulates relations for the phenotype profile matching (potentially alongside the inverse phenotypes), for relevance ranking.

**Comment by TomConlin** [comment]
mysql dumps (and more)available here:

http://www.reactome.org/pages/download-data/

**Comment by cmungall** [comment]
The Ensembl2Reactome is probably the easiest for a first pass. We should 
be able to do a turn this around quickly. We can return to the regulates 
question later.

Don't bother using all levels. Return to this if/when we have a pathway 
page.

**Comment by cmungall** [comment]
http://www.reactome.org/download/current/Ensembl2Reactome.txt
Just the ENSGs at first

Should we have a genetic dipper script for simple gene association files, configured by e.g. yaml?

**Comment by kshefchek** [comment]
I've added this in to my current PR, see https://github.com/kshefchek/dipper/commit/9c6807308c56d8cabec451d2059dd56e3e25af27

Model: https://github.com/kshefchek/dipper/commit/9c6807308c56d8cabec451d2059dd56e3e25af27#diff-75854f3df52f650cc62ad5a28097b586R29

We could also model this as:

        gene_id RO:has_gene_product _gene_product
        _gene_product RO:involved_in pathway_id
To be more consistent with how we modeled KEGG, but either will work with our cypher query for gene-pathway: https://github.com/monarch-initiative/monarch-cypher-queries/blob/master/src/main/cypher/golr-loader/gene-pathway.yaml

**Comment by cmungall** [comment]
For going beyond simple tables, may be easier to use their graph database: http://www.reactome.org/pages/documentation/developer-guide/graph-database/

**Comment by kshefchek** [comment]
Basic gene-pathway associations have been in since our August 2016 release, will close and make a new ticket for improving the ingest.

**Comment by jmcmurry** [comment]
Made the new ticket here #440
