### ISSUE TITLE
why some values in .ttl not curified?

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/dipper#294]
Parking this here but it isn't a high priority if not an easy fix. It is not clear to me why: 
1. Some of the values in our .ttl are curified and others not.
2. Some of the identifiers are nested. OBO:OMIIM_145980

http://data.monarchinitiative.org/ttl/clinvar.ttl

<img width="725" alt="screen shot 2016-04-29 at 10 28 47 am" src="https://cloud.githubusercontent.com/assets/3658863/14924061/708849f0-0df5-11e6-8b02-9e9440c1b58f.png">

**Comment by kshefchek** [comment]
See https://github.com/RDFLib/rdflib/issues/632

**Comment by kshefchek** [comment]
Moved to RDFLib/rdflib#632
