### ISSUE TITLE
Bring in antibody data from MGI 

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/dipper#30]
We will be bringing in some test antibody data from MGI to pilot test a "resource" tab and related search functionality.

This should be done with @bryanlaraway and @mbrush to sort out the model. 

Here is an example of the data: http://www.informatics.jax.org/gxd/summary?antibodyKey=1000

**Comment by nlwashington** [comment]
Also here:
http://www.informatics.jax.org/searches/antibody.cgi?3435

FYI, a brief perusal of the data suggests that they don't have xrefs to external antibody ids (as in company/brand identifiers).  But it might just require closer inspection.
