### ISSUE TITLE
Add a QC check for improbably equivalence axioms

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/dipper#304]
We believe we may have an equivalence axiom between FlyBase:FBgn0064121 and NCBIGene:2 (which is human) - see #303

Meanwhile we should have a global check. This involves consistency between multiple ttls so perhaps best done downstream via cypher/scigraph. One check would be that a gene is only a member of one species (thus a clique that merges genes from two species is wrong).

**Comment by kshefchek** [comment]
We could test this after each scigraph load with:

        MATCH (gene:gene)-[:RO:0002162]->(taxon1)
        MATCH (gene:gene)-[:RO:0002162]->(taxon2)
        WHERE taxon1 <> taxon2
        AND taxon1.iri > taxon2.iri
        RETURN DISTINCT gene, taxon1, taxon2

for example: [scigraph-dev](https://scigraph-data-dev.monarchinitiative.org/scigraph/cypher/execute?cypherQuery=MATCH+%28gene%3Agene%29-%5B%3ARO%3A0002162%5D-%3E%28taxon1%29+MATCH+%28gene%3Agene%29-%5B%3ARO%3A0002162%5D-%3E%28taxon2%29+WHERE+taxon1+%3C%3E+taxon2+AND+taxon1.iri+%3E+taxon2.iri+RETURN+DISTINCT+gene%2C+taxon1%2C+taxon2&limit=100)

If we were to turn this into a junit test where would it go, as a dipper-integration-test?

**Comment by cmungall** [comment]
On 9 May 2016, at 9:15, Kent Shefchek wrote:

> If we were to turn this into a junit test where would it go, as a 
> dipper-integration-test?

Do we have these yet? Would this be complex to implement?

**Comment by kshefchek** [comment]
yes: https://github.com/monarch-initiative/dipper-integration-test
But typically it runs on a smaller subset of the data.

**Comment by kshefchek** [comment]
This query has been added to our weekly qc report.
