### ISSUE TITLE
Create ID-URL files for collaboration sites to link to us

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/dipper#315]
OMIM would like a file of OMIM disease IDs so that they can easily link to us, but we need to remove gene IDs or separate them out (see also #273 for issues on this).

e.g. "I was waiting for a list of phenotype MIM numbers that have content in MONARCH for the URL
https://monarchinitiative.org/disease/OMIM:100800. I received a file from Nicole Washington, but it had all 24,000+ MIM#'s including genes. Can you provide a file of just disease MIM numbers that have MONARCH content?"

I suspect that other resources such as Orphanet, MyGene2, etc. would like to do the same. 

For every release we could dump an easy to consume file, with the diff, and some doc for these types of consumers? 

@TomConlin @cmungall

**Comment by kshefchek** [comment]
[omim-diseases.txt](https://github.com/monarch-initiative/dipper/files/276580/omim-diseases.txt)

curl 'https://solr.monarchinitiative.org/solr/golr/select?wt=csv&rows=500000&start=0&fl=object&fq=object_category:%22disease%22&csv.separator=%09&csv.header=false&q=object:OMIM*' | sort -u > omim-diseases.txt

**Comment by kshefchek** [comment]
We can use solr for omim once #273 is fixed since it has the highest priority in the clique merge.  For other sources we can use sparql.

**Comment by kshefchek** [comment]
see https://monarchinitiative.org/page/links
