### ISSUE TITLE
Add property axioms from ontologies

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/dipper#316]
Right now we load property axioms (for example, property a owl:ObjectProperty) into our source turtle files.  This is redundant since we pull these in from the individual ontologies, and could also lead to errors for ontologies actively under development (GENO, SEPIO).

I've written a script to generate these from their owl files, so now we just need to remove these functions from the dipper code, such as GraphUtils.loadAllProperties(graph).

**Comment by cmungall** [comment]
Be very careful. Changing the declarations can alter the semantics and 
affect the SciGraph load. Why do these lead to errors?

**Comment by kshefchek** [comment]
These are defined in the owl files we import into scigraph, why have them defined twice?  In dipper these currently hard coded.

**Comment by cmungall** [comment]
if there is no import in the ttl file then the semantics may be either 
different or unspecified

**Comment by kshefchek** [comment]
I would prefer importing from the source owl file over hard coding, if these are needed.  Let's discuss offline.

**Comment by kshefchek** [comment]
Added a function to pull property axioms from the source owl files.  Right now the path to the owl files are hard coded but we should update so they are pulling from the same versions used in the scigraph load.  Tested on our largest data set (flybase/3.2 gig as nt) and it added 123 seconds to the load.  Every source loaded either through the main dipper.py script or through the unittests (to get _test files) will run through this function prior to serializing the graph.
