### ISSUE TITLE
Consider alternatives/improvements to SciGraph cliquemerge

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/dipper#318]
Not sure if this belongs in SciGraph or Dipper.  We should investigate ways to improve the performance of the cliquemerging, some ideas:

- At the dipper level, see https://github.com/monarch-initiative/dipper/issues/197, but might be harder to capture provenance
- At the Scigraph owl loader/owl api level
- After loading into neo4j (current approach), but throwing more resources at it horizontally and using spark.

I know theres been some work done in this area already, just making a ticket for discussion and tracking purposes.

**Comment by kshefchek** [comment]
We ended up improving performance at the golr loader level, closing.

**Comment by cmungall** [comment]
not totally following. Surely cliquemerging is before exporting json for golr?

**Comment by kshefchek** [comment]
You're right, it was fixed at the scigraph-load level.
