### ISSUE TITLE
Pun EFO classes as instances of UPHENO:0001001

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/dipper#320]
We ingest the GWAS dataset, which links variants to EFO classes, but this is invisible on our site because EFO is not loaded into scigraph or hooked into uberpheno and/or mondo.  Theres a lot of interesting data here, and these classes are not always abnormal diseases/phenotypes, such as the variant responsible for brown/blue eye color.  I propose we type these classes as instances of UPHENO:0001001 so that these are indexed as phenotypes in scigraph and will be indexed in the solr views.

Another option would be load EFO into scigraph.

cc @cmungall @mbrush @mellybelly @nicolevasilevsky 

Ontology related ticket here: https://github.com/monarch-initiative/monarch-disease-ontology/issues/57

**Comment by kshefchek** [comment]
Outcome from dev call is that we will bridge EFO diseases into mondo and traits/phenotypes elsewhere.

**Comment by mbrush** [comment]
Poking around GWAS catalog ingest and noted that the objects of many associations are not diseases or phenotypes or traits, but 'measurements', e.g. 'serum albumin measurement'.  These measurements are indicative of phenotypes/traits, but the associations we create end up dubiously stating things like:
`'rs10880855 contributes_to 'refractive error measurement'` 
and
`'rs10880855 contributes_to self-reported educational attainment'`

We could deal with this by mapping measurements to phenotype classes in HPO, or using a different relationship in associations when the object is not a phenotype, trait, or disease

I also noted that we pull information about dbSNP variants into SciGrpah via GWAScatalog (e.g. genomic position, allele freq, taxon). We should get this directly from the source (or myVariant) - so data is current and has a single source of truth.

**Comment by kshefchek** [comment]
Implemented for phenotypes, disease now linked through mondo
