### ISSUE TITLE
Improve gene descriptions by integration with GeneWiki?

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/dipper#322]
We really don't have any descriptions on the gene pages, we could get additional info from Entrez or perhaps from GeneWiki in collaboration with BGood and @andrewsu, and have point back to GeneWiki or some type of GeneWiki view inside of Monarch. @DoctorBud @jmcmurry lets brainstorm

**Comment by kshefchek** [comment]
Does mygene.info work? see https://github.com/monarch-initiative/monarch-app/issues/863

**Comment by andrewsu** [comment]
Sorry for the late reply.  Not sure from the issue that Kent linked to --
is mygene.info serving your needs?  If not (and you think it should),
please let us know!  Same on Gene Wiki links...

Best,
-andrew

**Comment by kshefchek** [comment]
I think we can close with https://github.com/monarch-initiative/monarch-app/commit/b23487cd61209a504b6f4e04bafd7fb7c140d9ce
