### ISSUE TITLE
genotype model

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#34]
we need to flesh out the genotype model via parsing in dipper.

there's an initial commit of a Genotype class, but it needs major refactoring to deal with data sources that may not have all genotype parts within a single file, where those genotype parts span multiple files.  (for example, MGI).

we will use MGI as our first example of this.

**Comment by nlwashington** [comment]
@mbrush or @cmungall, can you comment about whether the genotypes (and their parts) should be bonafide classes, or instances, of those types (for example, intrinsic genotypes, genomic_backgrounds, vslc, etc.)

i think the plan at the moment is to model genes as classes.  (and in the current MGI parser, we are modeling all those features as classes rather than instances.

**Comment by mbrush** [comment]
I think we want genotypes and their parts (vslcs, variant loci, sequence alterations, etc) in the data to be instances of the appropriate GENO class(es).  As I understand it, genes are a special case that we are treating as classes (at least for now, but they may get punned to individuals to support phenotype propagation). This is how we had previously specc'd things out, and how we defined things in the yaml config for the disco2ttl pipeline.

**Comment by nlwashington** [comment]
should 'wild-type' alleles be added?  we sort-of went through this convo before, but let's document it here.  if a resource such as MGI gives identifiers to a reference/wild-type allele, do we want to actually include those in the data?  (i hate to throw away data.)  i worry that if we do include them, that it might just muck things up.

**Comment by mbrush** [comment]
I think GENO could handle this in a pretty straightforward way - just link the wt allele to its parent VSLC using GENO:0000385#has_reference_part relation (analogously to how a variant allele is linked using GENO:0000382#has_alternate_part).  So it would just be one extra triple for genotypes with a wt allele identified. Phenotypes wont propagate over this has_reference_part relation, so we avoid associating wt alleles with phenotypes.

I think we did not include these before because we didn't foresee a need/use case for this information being explicitly represented.  But doesn't hurt much to add it.

**Comment by selewis** [comment]
The thing that worries me about official encoding 'wild type' is that it is
not a authentic biological object. It is a man-made artifice of
convenience. The somewhat random allele that the background strain just
happened to carry.

It's analogous to the entire pseudogene debate. It's important in the
modeling that we clearly distinguish between man-made artifacts/constructs
and genuine biological features. So, obviously we want to capture the fact
that some allele has been characterized as 'wild type', but wondering
whether we should be distinguishing between subclasses like 'allele that
introduces a stop codon' (if it were to be instantiated) and a subclass
based on utility to a given type of investigation like 'wild type allele'.

I believe that going forward 'wild type' will fade away from use like the
buggy whip, replaced by direct calculations of allele frequency.

-S

**Comment by nlwashington** [comment]
i think we've covered most issues here.  new items to add to the genotype modeling should be opened as new tickets.
