### ISSUE TITLE
models for G+E and/or G+P+E

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#35]
We'll need to record a few patterns of data that include environments (such as responses to drugs), to make associations like:

disease D that is caused by variant V is sensitive/responsive to drug R.
person with variant V and exposed to drug R is more susceptible to disease D

please help determine the triple (reified, if necessary) pattern that is needed for these cases, and then we'll implement them in a new Association model.

**Comment by cmungall** [comment]
Might we also want to record the activity of the drug? This may be specified to the individual association. E.g. some drugs may act as agonists in some tissues and modulators in another.

There are different options here, including a granular pathway/lego level representation of the activity of the drug modulating the pathway.

As a high level view, how about modeling this as in a typical variant-disease pair and adding an extra property for the modifying effect of the drug/environment?

Can discuss more tomorrow

**Comment by nlwashington** [comment]
what about if we associate a phenotypic_quality with the variant-disease association like 'increased resistance to' toward the drug, like:

variant_disease_assoc_id RO:has_quality 
  [ :hasSubject PATO:increased_resistance_to
    :hasPredicate RO:towards
    :hasObject DrugBank:some_drug ]

**Comment by nlwashington** [comment]
some examples of relationships between a drug and a disease (caused by a specific variant), are:
decreased sensitivity
detrimental effect
increased benefit
no response  
no sensitivity
reduced sensitivity
resistance         
response          
sensitivity

**Comment by mellybelly** [comment]
hm this can be tricky. I do think some of these are phenotypes that are altered relative to before the drug, whereas some may be specific propensities. 

Also some might be somewhat synonymous but referring to a propensity vs. outcome, respectively. For example, resistance might be a propensity of a tumor to not be responsive to a drug, whereas "no response" is the outcome of the treatment.

**Comment by nlwashington** [comment]
I agree, these are not quite relationships; i suppose my question is, do we define them like a "precomposed" relationship with a logical definition that maps to the various phenotype (and drug) parts, or do we just do that at ingest time? (my ontological naivety is evident here.)

**Comment by bryanlaraway** [comment]
I want to add to this with the environments I'm seeing in ZFIN #12 in the http://zfin.org/Downloads/pheno_environment.txt file. There are many environmental variables that we could model. I've exported a csv with some general environment types into the dipper_testfiles folder in DropBox (LAMHDI-Project/FileSharing/dipper_testfiles/ZFIN/environment_conditions.csv), although there may be many subtypes (especially in the 'chemical-other' group). 

Note that if you look at the file from ZFIN, there are also morpholinos, TALENs, and CRISPRs, which we will take care of with the extrinsic genotype (just morpholinos for now).
