### ISSUE TITLE
Update Clinvar for scigraph compatibility

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/dipper#350]
We need to make some updates to the clinvar xml parser to be compatible with some scigraph features.

1. Add the triple:
@prefix MonarchData: <http://data.monarchinitiative.org/ttl/> .
MonarchData:clinvar.ttl a owl:Ontology ;
Reason: This is used in SciGraph to link data to their source ontology

2. Use consistent RDFS:label iri
All rdfs label iris should be: http://www.w3.org/2000/01/rdf-schema#label
Right now some have a 1999 instead of 2000
In Scigraph, used to map to node.label property:
https://github.com/monarch-initiative/SciGraph-docker-monarch-data/blob/master/src/main/resources/monarchLoadConfiguration.yaml.tmpl#L109

3. Use blank nodes instead of monarch iris in the full set.  Blank nodes are handled differently in scigraph and UI.

Overall, it would be great if we were using RDFLib here, and our graph util and models API.  If there are pain points in using either of these please document these and we can figure out a gameplan to improve them moving forward.

**Comment by TomConlin** [comment]
points addressed
