### ISSUE TITLE
Stop clinvar parser from creating associations if no pathogenicity call made

### ISSUE THREAD

**Issue by mbrush** [monarch-initiative/dipper#351]
The dipper script is creating associations between a variant and a disease even if there is no pathogenicity call being made (e.g. the 'pathogenicity' is indicated as 'unknown', or 'uncertain significance', but the appropriate relation is not being added to the graph). This leads to Monarch:associations with no predicate, which is problematic for the golr loader which expects every association to have exactly one predicate linked through the oban:association)_has_object_property relation.

For example see the ‘not provided’ call for the SCV000072786 assertion for ClinVarVariant:38001 [here](http://www.ncbi.nlm.nih.gov/clinvar/variation/38001/). Some other association that lack predicates:

    MATCH (a) 
    WHERE a:association AND NOT (a)-[:`http://purl.org/oban/association_has_object_property`]->() 
    RETURN distinct a.iri
    +---------------------------------------------------------+
    | a.iri                                                   |
    +---------------------------------------------------------+
    | "http://purl.org/oban/association"                      |
    | "http://purl.obolibrary.org/obo/GENO_0000833"           |
    | "http://monarchinitiative.org/MONARCH_e34744b16c5d6baa" |
    | "http://monarchinitiative.org/MONARCH_ec0c35d697b8e2b1" |
    | "http://monarchinitiative.org/MONARCH_6002705703dcc77d" |
    | "http://monarchinitiative.org/MONARCH_44a99fe8ce73f2c5" |
    | "http://monarchinitiative.org/MONARCH_e2eb90d9eba257e6" |
    | "http://monarchinitiative.org/MONARCH_8f6c6d380a29767a" |
    | "http://monarchinitiative.org/MONARCH_e21208e8de131e67" |
    | "http://monarchinitiative.org/MONARCH_c0ea57a367fe2903" |
    +---------------------------------------------------------+

    MATCH (a) WHERE a:association AND NOT (a)-[:`http://purl.org/oban/association_has_object_property`]->() RETURN distinct count(a)
    +----------+
    | count(a) |
    +----------+
    | 22059    |
    +----------+

**Comment by TomConlin** [comment]
@mbrush  do you have a cmap to reflect this update?

**Comment by mbrush** [comment]
Really nothing to add to the cmap.  This is just adhering to the rules for when we create an association for a given SCV, based on the classification mapping to one of the five ACMG categories (pathogenic, likely pathogenic, uncertain significance, benign, likely benign).  Note I updated the example in the original post above - was supposed to be the SCV whose classification was 'not provided'.  Spot checking a few of the other problematic associations, I see many others with 'not provided' as the classification. So guessing that the mapping in the dipper code is not filtering out these SCVs where the classification doesn't map to an ACMG code, and instead creating an association that lacks a punned relationship.

**Comment by TomConlin** [comment]
Medgen supplies  "diseases" identifiers with the label "not provided"

**Comment by TomConlin** [comment]
@mbrush  I am taking this issue to mean that if a Monarch association does not have one of the five ACMG calls then omit the entire association.

For the example you gave with SCV000072786 (which is under RCV000044773)
 now looks like:

![rcv000044773](https://cloud.githubusercontent.com/assets/1911895/17119794/e849c966-527c-11e6-8e7f-9f12d42e5721.png)

Previously, the edges from MONARCH other than the one to GENO had a count of two.  

here is the output of the test set (the .txt on the end is so it could be uploaded)  

[ClinVarTestSet_20160725.ttl.txt](https://github.com/monarch-initiative/dipper/files/382685/ClinVarTestSet_20160725.ttl.txt)

**Comment by mbrush** [comment]
"I am taking this issue to mean that if a Monarch association does not have one of the five ACMG calls then omit the entire association."

-------------------

Yes, exactly.  If the pathogenic call isn't an ACMG category (or something we mapped to an ACMG category).  And if I am understanding your nice diagram correctly, it reflects what I would expect for what we should extract from RCV000044773 - i.e. only one association being created (for SCV000210772).

**Comment by TomConlin** [comment]
The overall effect of this change is:   
- We previously accepted or rejected a "ClinVarSet" as a whole  (A RCV and _all_ the sibling SCV).   
- We now selectively reject individual SCV.  

SCV rejection is based on the existence of  the ClinicalSignificance Description field not its content as we map ambiguous content to the ACMG catagory: "uncertain significance".
