### ISSUE TITLE
Wrong IRI for Fanconi Renotubular Syndrome?

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/dipper#355]
I thought this was just an instance of an unresolvable IRI, but ontobee doesn't even seem to have an ontology with the prefix DC; it isn't familiar to me. Nor does a search for Renotubular in Ontobee yield results. 

https://beta.monarchinitiative.org/disease/DC:0000148 points to http://purl.obolibrary.org/obo/DC_0000148

**Comment by TomConlin** [comment]
In a sane world DC would be "Dublin Core"  followed by a metadata term.  
Will try to make it different.

**Comment by TomConlin** [comment]
in our ingested  triples the identifier fragment "0000148"  exists in:
```
    grep -l "_0000148>" out/*.nt
    out/animalqtldb.nt
    out/coriell.nt
    out/hpoa.nt
    out/omia.nt
    out/wormbase.nt
    out/zfin.nt
    out/zfin_slim.nt
```
with ZP, HP, GENO, CL. LPT  but never (so far) associated with the DC prefix

**Comment by cmungall** [comment]
DC is the prefix given to the OMIM disease clusters, by MGI. We can 
rename this in the Monarch repo.
