### ISSUE TITLE
NCBIGene:2989 (GULOP) should not be equivalent to scurvy

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/dipper#356]
Searching for scurvy leads us here
https://monarchinitiative.org/disease/NCBIGene%3A2989

Which is confusing. Presumably coming from an incorrect NCBIGene to OMIM (disease) equivalency

**Comment by kshefchek** [comment]
fixed with: https://github.com/monarch-initiative/dipper/pull/357

**Comment by jmcmurry** [comment]
The referenced issue is a duplicate. https://github.com/monarch-initiative/monarch-app/issues/1318#issuecomment-237464990

**Comment by kshefchek** [comment]
fixed with: #357
