### ISSUE TITLE
Unit test for pages with no descriptions

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/dipper#359]
Possibly a BioCreative task?

**Comment by kshefchek** [comment]
Was this intended for dipper or monarch-app?

**Comment by jmcmurry** [comment]
In retrospect, "pages" was misleading. I meant any clique-leader with no description. As such, would this be a better issue for SciGraph? I defer to you.

**Comment by cmungall** [comment]
I think your suggestion from last week was a good one. We accept dead-ends as inevitable, we just get smart about recognizing them and providing the user helpful routes out

**Comment by jmcmurry** [comment]
Agreed, this would be not be instead of that "way out of dead ends" but just for the prose descriptions /definitions themselves especially for genes and diseases (phenotypes we have covered). This is why @mellybelly had suggested a BioCreative challenge, but we would need to start with a list of entities for which we are missing definitions/descriptions.

**Comment by kshefchek** [comment]
The majority if not all of the descriptions come from mondo.owl or mygene.info, we may be capturing some descriptive information in dipper that we could include though.

**Comment by jmcmurry** [comment]
Of all our shortcomings, this one doesn't keep me up at night ;) The issue was not primarily for *us* to fix the lack of definitions so much as it was to specify a list of entities for which we could outsource them. If generating a list isn't really easy to do, it is fine to de-prioritize.

**Comment by kshefchek** [comment]
I propose we replace with https://github.com/monarch-initiative/monarch-app/issues/1561
