### ISSUE TITLE
CGD predicate terms

### ISSUE THREAD

**Issue by TomConlin** [monarch-initiative/dipper#373]
@mbrush 
Our file
<http://data.monarchinitiative.org/ttl/cgd.ttl>
uses the predicate "OBO:RO_has_environment" 1,106 times.  

I believe GGD is a quiescent data source and we reuse 
the same datafile each release. 
@kshefchek   confirm?
hence it is not updated with current ontology terms.

RO does not now include that term.  
RO does not have that term as obsolete/replaced.  

"has_environment" is fine label 
but I would expect the term to have a zero padded integer identifier
for the concept independent of the current label   
similar to:   
<http://purl.obolibrary.org/obo/RO_0002483>  

I do not see any thing compelling in RO 
to replace "has environment"  there is "has habitat"
but that is not appropriate for a chemical/drug environment.

CGD is the only ingest using this predicate  
Likewise CGD exclusively uses the predicate terms:   

<http://purl.obolibrary.org/obo/GENO_altered_nucleotide>
<http://purl.obolibrary.org/obo/GENO_reference_amino_acid>
<http://purl.obolibrary.org/obo/GENO_reference_nucleotide>
<http://purl.obolibrary.org/obo/GENO_results_in_amino_acid_change>

altered_nucleotide   
-there are thousands of terms involving nucleotide
in ontobee some must have to do with SNPs,  SO_0000694 ?

An ontology to cover IUPAC ambiguity codes should exist
note:  ambiguity - reference is altered_nucleotide

<http://purl.obolibrary.org/obo/SO_0001505>
could serve for both  'reference_nucleotide' and 'reference_amino_acid'
if nothing better exists.

'results_in_amino_acid_change'  
If it were yes/no we could use SO_0001819 ! 'silent substitution" T/F
but here we have the resulting AA.

Since the association is from a (mutation) genotype
 SO_0001606 ! amino_acid_substitution

```<genotype>  <SO:0001606> "aaa"```

seems plausible.

**Comment by mbrush** [comment]
I am not familiar with this source and wasn't involved  in the modeling here.  But recall that Nicole or Kent created some placeholder relationships like this which are likely the non-numeric IRIs you refer to.  Seem that this source needs to be revisited and refactored.  @kshefchek perhaps you can shed some light here? Is there a cmap or a test ttl file for this source?

**Comment by kshefchek** [comment]
The code for this lives in a different repo: https://github.com/monarch-initiative/mckb

This was developed as a prototype for another project, but is not meant for any production environment, we don't use it in the monarch db.

We can move the ticket over to mckb or close.

**Comment by TomConlin** [comment]
Is there an argument for <http://data.monarchinitiative.org/ttl/cgd.ttl> remaining in the production data repository or may I remove?

**Comment by kshefchek** [comment]
we should host it somewhere, maybe http://data.monarchinitiative.org/dev/ makes more sense, cc @bwalsh

**Comment by TomConlin** [comment]
cgd.ttl may now be found in dev

**Comment by bwalsh** [comment]
Thanks for the heads up.  Has the format of the file changed? Is there new
content?

**Comment by TomConlin** [comment]
@kshefchek would know but I do not think so 
(But I also do not know as compared to what)

I just moved the file till it becomes integrated into Monarch.
