### ISSUE TITLE
Replace BFO 'part-of' and 'has-part'

### ISSUE THREAD

**Issue by TomConlin** [monarch-initiative/dipper#374]
@cmungall @mbrush 

BFO_0000050  ! part of
BFO_0000051  ! has part 

These terms have not been welcome in the basic formal ontology 
for several years now, we should replace them with well supported terms.  

We use them in across all ingests from here: 
https://github.com/monarch-initiative/dipper/blob/c2f379fea90ca3d40b844f3f3a8ffefbbc24a260/dipper/utils/GraphUtils.py#L56

For "has part"  there is a single obvious choice.

http://purl.obolibrary.org/obo/RO_0000057 ! has part

For "part of" it is not as clear.  Ontobee still  referenced BFO_0000050  but as part of RO
<http://www.ontobee.org/ontology/RO?iri=http://purl.obolibrary.org/obo/BFO_0000050>
technically this works, but if the Basic Formal Ontology does not support the terms we(?) should not continue using their namespace BFO for what is now a RO term.

other related terms

 http://purl.obolibrary.org/obo/RO_0002287
    part of developmental precursor of

http://purl.obolibrary.org/obo/RO_0002329
    part of structure that is capable of

http://purl.obolibrary.org/obo/RO_0002350
    member part of

http://purl.obolibrary.org/obo/RO_0002331
    enables part of

http://purl.obolibrary.org/obo/RO_0002225
    develops from part of

http://purl.obolibrary.org/obo/RO_0002314
    inheres in part of

http://purl.obolibrary.org/obo/RO_0002216
    capable of part of

http://purl.obolibrary.org/obo/RO_0002380
    branching part of

http://purl.obolibrary.org/obo/RO_0002177
    attached to part of

http://purl.obolibrary.org/obo/RO_0002509
    determined by part of

http://purl.obolibrary.org/obo/RO_0002012 
    occurent part of

reference
https://github.com/BFO-ontology/BFO/issues/46.

**Comment by cmungall** [comment]
> http://purl.obolibrary.org/obo/RO_0000057 ! has part

has participant. Different relation.

https://github.com/oborel/obo-relations/wiki/ROAndBFO

**Comment by TomConlin** [comment]
@cmungall  I am glad you noticed that, it bothered me they were not symmetric

we are using 
BFO_0000050 ! part of
BFO_0000051 ! has part 

The BFO does not have, support nor endorse those terms, they are obsoleted.
Those terms now exist in the RO but are not in the RO namespace 
this is not on  the path of least astonishment from a curie/identifier perspective.

I would ask that either we choose supported terms from some ontology  or
they get  proper RO identifiers for everyone to use.

**Comment by kshefchek** [comment]
My understanding from reading https://github.com/oborel/obo-relations/wiki/ROAndBFO#part-of is that these are maintained by the relation ontology, but stay in the BFO namespace (but are not in bfo.owl).  I find it confusing as well but expect the explanation is too long for github.  But for now it sounds like it is out of our hands.
