### ISSUE TITLE
Add variant locations to clinvar xml parser

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/dipper#376]
We will be working with UCSC to predict orthologous variants across species.  To do this we want to compare genomic coordinates for variants in the same gene across species.  We previously pulled genomic coordinates from the clinvar tab file, but this is not yet added to the xml parser.  The modeling should be the same.

**Comment by kshefchek** [comment]
Sounds like I misunderstood the requirements for this, but let's leave open and de-prioritize.  We would need this for any genome browser type widget.

**Comment by cmungall** [comment]
> let's leave open and de-prioritize

do you have a github label for that?

**Comment by kshefchek** [comment]
Closing, we will move this functionality to a generic vcf parser.
