### ISSUE TITLE
 RO_HOM0000017 ! in orthology relationship with

### ISSUE THREAD

**Issue by TomConlin** [monarch-initiative/dipper#378]
@mbrush 
omia, panther and zfin ingests use the term  RO_HOM0000017 
which no longer appears in <https://raw.githubusercontent.com/oborel/obo-relations/master/ro.owl>

alternatives appreciated

ditto for 
 - RO_HOM0000011 
 - RO_HOM0000018 
 - RO_HOM0000020   
but only panther uses them

**Comment by cmungall** [comment]
it's in the import chain

(btw, always use the purl)
