### ISSUE TITLE
GENO_0000532 ! has expression-variant part

### ISSUE THREAD

**Issue by TomConlin** [monarch-initiative/dipper#379]
@mbrush 
zfin ingest uses it but it is no longer found in https://raw.githubusercontent.com/monarch-initiative/GENO-ontology/develop/src/ontology/geno.owl

**Comment by cmungall** [comment]
a quick grep around GENO reveals that this is the intended property: 
http://purl.obolibrary.org/obo/GENO_0000382

The fix should be straightforward but you will need to coordinate changes with any cypher queries

**Comment by mbrush** [comment]
@TomConlin you can go ahead and swap in the GENO:0000382 property for any usage of GENO:0000532 in zfin.  I don't see any other ttl files with this predicate, and I don't see anything in the cypher queries that would need to be coordinated for this change.  Ticket can be closed once this is done.
