### ISSUE TITLE
pathways or other gene collections

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#38]
We'll need to be able to model / handle collections of features (genes, variants, etc.).  A specific case of these are pathways (where we might have an ordered list), but we might have unordered collections, like KEGG pathways.  

@mbrush what kind of relationship would we use here if we want to say that a gene is part_of a pathway?

**Comment by cmungall** [comment]
For GO, gene products are involved_in the process/pathway

**Comment by mbrush** [comment]
A practical question here is do we want a different relation to link genes to pathways vs gene products to pathways.  From a realist view this would be appropriate -  pathways are processes that gene products RO:'participate_in'. Genes (as GDCs) don't directly participate in a pathway in the RO sense, and perhaps this justifies defining a different relation being used here (contribute_to? is_gene_involved_in?).

But from a practical perspective it might be prudent to use the same relation to link genes or gene products to a pathway. Perhaps say the semantics of involved_in are looser than that of RO:participates_in and we could use this relation.  Or create subrelations (is_gene_involved_in and is_gene_product_involved_in).

We could also then make the involved_in property be transitive over whatever relation/path we end up defining to link genes to their products? So we could infer (if we did not assert) that a gene is involved_in a pathway when it product is involved.

**Comment by nlwashington** [comment]
so, for kegg stuff should i just say:

gene involved_in pathway?

or make some anonymous node that is the product of the gene, like:
gene has_product (some protein) involved_in pathway ?

**Comment by nlwashington** [comment]
as per #39, we say:

gene_id RO:involved_in pathway_id
pathway_id subClassOf GO:0007165

we should consider refactoring to use gene products, but i leave that in another ticket.

**Comment by nlwashington** [comment]
ok, so if i create BNodes for the gene_products, what would those gene products be typed (subclassed) as?  we don't actually know a priori what the "active" type of those products are (RNA vs Protein), so i would like to be generic an call them "gene product", but i can't figure out what class that maps to.  is there such a class?

**Comment by nlwashington** [comment]
the Pathway module follows the indirect route, creating a "bioinformational molecule" that is a has_gene_product relationship with the original gene, when the actual gene product is unknown, and is involved_in the pathway.
