### ISSUE TITLE
add CTD gene-pathway associations

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#39]
using the gene-pathway modeling set out in #38, add the associations for genes to pathways here:
http://ctdbase.org/reports/CTD_genes_pathways.tsv.gz

the nice thing is that CTD have done the hard work of parsing KEGG, so we get those for free here, and allows us to work with pathways as simply bags of genes first, instead of the complicated directed graphs that they actually are (which will be modeled more completely by Reactome)

**Comment by nlwashington** [comment]
@cmungall should these pathways be subclasses of some pathway term, like http://purl.obolibrary.org/obo/PW_0000001

**Comment by nlwashington** [comment]
@kshefchek since we have no source or provenance information about the gene-to-pathway links, i am not sure that we need to create the reified association between the genes and pathway (for example, since no information is given, we can't really use the TAS evidence code, since it's not really traceable); perhaps a simple triple is sufficient here?  

pathway_id RO:has_member gene_id ?

**Comment by kshefchek** [comment]
I agree, we don't have a reference for these so TAS doesn't make sense.

Should I utilize the gene symbols from this file or will this come from elsewhere?

**Comment by nlwashington** [comment]
as they are entrez ids, the labels will come from elsewhere.

**Comment by nlwashington** [comment]
probably add the RO:has_member rel to the graphutils relationship def?

**Comment by kshefchek** [comment]
Adding gene ids (entrez), kegg, and reactome pathways as classes.  These can be removed when we import these classes separately.

**Comment by cmungall** [comment]
They can be subclasses of GO signal transduction. The relation would be RO_0002331 involved in

Many of the KEGG pathways are in GO. It would be useful to compare overlap in genes (but this would be more of a GO task)

**Comment by kshefchek** [comment]
Is this right?
gene_id RO:involved_in pathway_id
pathway_id subClassOf GO:0007165

**Comment by nlwashington** [comment]
Gene (products) are now added to pathways.  Pathways are subclasses of cellular processes and of 'pathway' PW:0000001.  The gene products that are linked are the anonymous gene products.
![screen shot 2015-06-22 at 5 15 48 pm](https://cloud.githubusercontent.com/assets/5124411/8311058/9474580c-1988-11e5-8916-313036c70609.png)

**Comment by nlwashington** [comment]
@mbrush verify cmap and modeling.  close if satisfied.
