### ISSUE TITLE
handle rdf data sources

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#4]
we'll need to handle rdf datasources, and mapping to our own schema, perhaps with sparql queries.  for example, bio2rdf.

**Comment by nlwashington** [comment]
this is not required for the 'flip' release...moving to parking lot.

**Comment by kshefchek** [comment]
Replacing with rdf source specific tickets, I'm not sure we need to abstract up front unless we see repeated functionality across sources.

J-phenome: https://github.com/monarch-initiative/dipper/issues/329
nextProt: https://github.com/monarch-initiative/dipper/issues/292
bio2rdf: https://github.com/monarch-initiative/dipper/issues/15
