### ISSUE TITLE
Add  Source: RGD GAF files

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/dipper#400]
RGD provides GAF files which should be easy to ingest:

ftp://ftp.rgd.mcw.edu/pub/ontology/annotated_rgd_objects_by_ontology

**Comment by mbrush** [comment]
- **Source Name:**  Rat Genome Database  (rattus-mp GAF files)
- **Source Data Description:**  target of this ingest is only gene-phenotype associations from provided GAF tsv file
- **Source Data Extraction**
     - _Source Data Location_:  ftp://ftp.rgd.mcw.edu/pub/data_release/annotated_rgd_objects_by_ontology/rattus_genes_mp
     - _Source Contact(s):_ http://rgd.mcw.edu/contact/index.shtml
- **Source Data Exploration**
     - _Source Documentation:_  ftp://ftp.rgd.mcw.edu/pub/data_release/annotated_rgd_objects_by_ontology/README
     - _Dipper Python Notebook(s):_   
     - _Dipper-Curated Source Datasets:_  
- **Data Modeling and Transformation**
     -  _Target Model Cmaps_:  https://github.com/monarch-initiative/dipper/tree/master/docs/RGD
- **Generated Data QA**
     - _Dipper Test.ttl file:_  
     - _Dipper QA Notes Doc:_  
     - _Dipper Python Notebook(s):_  
     - _Other (unit tests?, cypher queries?):_   
- **Final Documentation**
     - _Public Cmaps:_  
     - _Developer Cmaps:_

**Comment by mbrush** [comment]
Tom - like the ADD-SOURCE label as a way to find/group these kinds of tickets,  but think the issue title needs to be more descriptive than "RDG GAF Files" - i.e. the title needs to indicate this ticket is about adding this as a new source.

**Comment by kshefchek** [comment]
Let's coordinate with and reuse ontobio where we can: https://github.com/biolink/ontobio/blob/master/ontobio/io/gafparser.py

**Comment by cmungall** [comment]
+1

Should be reasonably stable.

I think the dipper gaf parser can eventually be eliminated. there are a few things the ontobio one doesn't do yet

 - dipper will download an enormous mapping file. in gafparser, you can provide your own mappings for subject (genes)
 - dipper will make phenotype classes for IMPs. If we want to keep doing this, this functionality would be dipper specific, it would just make use of generic parsing

**Comment by kshefchek** [comment]
It's not great but this seems to work as a resolver service (for genes and references):
http://rgd.mcw.edu/generalSearch/RgdSearch.jsp?quickSearch=1&searchKeyword=

**Comment by kshefchek** [comment]
https://github.com/monarch-initiative/dipper/pull/516
