### ISSUE TITLE
Dipper should only produce a file if the process completes successfully

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/dipper#404]
See https://github.com/monarch-initiative/monarch-devops/issues/56

With Makefile I always do this:

```
myprog -o foo.out.tmp && mv foo.out.tmp foo.out
```

Can we have dipper do the equivalent?

**Comment by kshefchek** [comment]
Is it clear that this is actually happening?  We set bash -e when running the jenkins jobs, the script should stop before it's copied to data.monarch, and each run clears out the previous download of source files.

**Comment by TomConlin** [comment]
I can not say it is clear, I see no smoking gun in either go's or panther's  jenkins console logs indicating anything about disk problems.

http://ci.monarchinitiative.org/job/build-go-ttl/lastBuild/console
http://ci.monarchinitiative.org/job/build-panther-ttl/lastStableBuild/console

I expect those links will rot quickly as they are displaced by new job runs

**Comment by cmungall** [comment]
OK, looking at the config I think my ticket is invalid
