### ISSUE TITLE
Cycle in scigraph

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/dipper#409]
Original issue https://github.com/monarch-initiative/SciGraph-docker-monarch-data/issues/4

![graph](https://cloud.githubusercontent.com/assets/4312088/22043705/c6363ae8-dcc5-11e6-85ed-bb3a659010c4.png)
```
http://purl.obolibrary.org/obo/DOID_1242 (globe disease)
http://purl.obolibrary.org/obo/DOID_5614 (eye disease)
```

I tracked down the backward edge in http://purl.obolibrary.org/obo/clo.owl.
```
    <!-- http://purl.obolibrary.org/obo/DOID_5614 -->

    <owl:Class rdf:about="&obo;DOID_5614">
        <rdfs:label rdf:datatype="&xsd;string">eye disease</rdfs:label>
        <rdfs:subClassOf rdf:resource="&obo;DOID_1242"/>
```

I found another cycle, coming from clo.owl again. This time it's a 2 hops cycle:
![graph 1](https://cloud.githubusercontent.com/assets/4312088/22080601/057b2114-dd75-11e6-9598-192f42854239.png)
The false assertion is:
`(http://purl.obolibrary.org/obo/DOID_308)-[:subClassOf]->(http://purl.obolibrary.org/obo/OMIM_545000)`

**Comment by cmungall** [comment]
Good catch

The problem of injection of stale axioms pervades ontology releases. It's particularly bad here because CLO is so old that it includes SubClassOfs that are inverses of what we have currently.

The quick fix here is to either eliminate CLO (do we use this @mbrush ) or to import only a simple version.

**Comment by kshefchek** [comment]
We use it in the Coriell ingest, how about we just pull from https://raw.githubusercontent.com/CLO-ontology/CLO/master/src/ontology/clo.owl instead of the purl which forwards to the merged file here: https://raw.githubusercontent.com/CLO-ontology/CLO/master/src/ontology/clo_merged.owl

**Comment by cmungall** [comment]
As a policy everything we should do should have a PURL otherwise we'll get fenkled down the line. I'll see if we can sort this out at the CLO end ASAP otherwise we'll go with the hack

**Comment by cmungall** [comment]
OK, CLO is a bit problematic here

clo.owl resolves to a merged file that was last updated in 2013!

@kshefchek's fix above pulls the unmerged one, which has distinct imports to individual purls: https://github.com/CLO-ontology/CLO/tree/master/src/ontology

However, the PURLs for the imports don't resolve...

**Comment by mbrush** [comment]
Guessing it will be a while before CLO addresses Chris' issue (https://github.com/CLO-ontology/CLO/issues/38) and generates a release with updated imports.  So for a short-term fix, I can manually generate a slim that contains only the cell line class hierarchy.  We can store this locally (perhaps just on the Monarch data server) and load into SciGraph from here. This sound reasonable?

Guessing that ROBOT tools would allow us to auto-generate such a slim as part of our pipeline, so it stays current/synced with the CLO - but I am not yet saavy with these tools.   But in the long term, hoping that CLO folks will both fix the problem natively by updating their imports, so we can use the proper CLO again.  We could also also them to create a resolvable slim as part of their release process that contains only the core cell line type hierarchy, and use this going forward.  Thoughts @cmungall?

**Comment by cmungall** [comment]
+1

you could also store it as a PR. We could even have a purl for it.

**Comment by mbrush** [comment]
Yes, I could make a PR for CLO to add the slim I created to their repo. And once they accept this, make a PR to the obofoundry purl registry adding a purl to the clo.yml file that resolves to this slim.  

This what you had in mind @cmungall?   Still requires action of part of CLO maintainers, but barrier much lower as I would do all the work.

**Comment by cmungall** [comment]
Note if you make a PR that artefacts are all available via raw github 
URLs. No dependency on CLO

**Comment by mbrush** [comment]
Manually generated a slim CLO file that contains only the cell line cell hierarchy and its closure up to the root. Will live locally for now and replace the full clo.owl import. But will make a PR for CLO to host in their repo, and request a file like this gets generated as part of their release cycle.

**Comment by jnguyenx** [comment]
:+1:

**Comment by kshefchek** [comment]
> Manually generated a slim CLO file that contains only the cell line cell hierarchy and its closure up to the root. Will live locally for now and replace the full clo.owl import. But will make a PR for CLO to host in their repo, and request a file like this gets generated as part of their release cycle.

@mbrush any updates on this?  I noticed we're still using the 2017 copy of clo.  If you remember the owltools or robot command you used to generate this we can create it as part of our pipeline.

**Comment by matentzn** [comment]
I once migrated CLO to ODK and even created base.. Thats what we would need. But they didnt want to merge the PR. Too much technical debt for them!

I would suggest simply using the new ROBOT feature called "base". Dont worry about the dependencies, we dont need more then what is already in Monarch.owl.. 

```
robot filter -I http://purl.obolibrary.org/obo/clo.owl \
  --base-iri http://purl.obolibrary.org/obo/CLO_ \
  --select "annotations" \
  --axioms internal \
  --include-term IAO:0000117 \
  --include-term IAO:0000119 \
  --preserve-structure false \
  --output results/clo-base.owl
```

Something along these lines. (Didnt test, but top of my head). Or use remove axioms --external.

http://robot.obolibrary.org/filter

Remember, very new ROBOT feature! Super cool!

**Comment by kshefchek** [comment]
good to know, let's incorporate this!
