### ISSUE TITLE
add elements of morphology

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#41]
Let's get the elements of morphology mappings in.  

This will require the flat-file mapping from @nicolevasilevsky, as well as the screen scraping from the DISCO system (nlx_157874-1), to get the terminologies and links to their site.  (We could consider adding the HP-EOM mappings as a separate resource, but let's start with it combined for now.)

**Comment by nlwashington** [comment]
As part of the pipeline, it would be good to output a warning to notify if there are missing HP mappings.

**Comment by nlwashington** [comment]
i think for EOM, we don't want to recreate their hierarchy; we're going to leave that up to HP.
we really just want the ids,their definitions, and image links:
<eom id> equivalentClass <hp id>
<eom id> rdfs[label] literal(label)
<eom id> dc[description] <definition>  where the definition is the mixture of the objective and subjective definitions
<eom id> dc[comment] <comments>
<eom id> foaf:depicts <image url>
<eom id> OIO:hasRelatedSynonym <synonym>
<eom id> OIO:hasRelatedSynonym <use the replaced labels here too>

**Comment by bryanlaraway** [comment]
@mbrush @nlwashington For linking the term back to the EOM page via URL link, does foaf:page work?

**Comment by bryanlaraway** [comment]
This should be wrapped up with my latest [commit](https://github.com/monarch-initiative/dipper/commit/212631791dac07a8da62841d9905db9c804f75c7).

Issues outstanding:
-Any additional data need for data provenance for this resource?
-Is the Monarch_phenotype the correct subclass for morphology terms, or do we want GENO:0000348 - phenotype?
-Is the foaf:page the correct predicate for a link to a web page (morphology_term_id, foaf:page, morphology_term_url)?

Copies of the ttl output and the tsv mapping file are in the dipper_testfiles DropBox folder.

**Comment by bryanlaraway** [comment]
Reassigning to @mbrush  for QA.

Here is example output from one of the terms that has entries for each variable:

OBO:EOM_1d53660e657259f0 a owl:Class ;
    rdfs:label "Macrocephaly" ;
    dc:comment "Head circumference is measured from just above the glabella (the most prominent point on the frontal bone above the root of the nose) to the most posterior prominent point of the occipital bone using a tape measure. Some standard charts are organized by centiles [Hall et al., [2007]], others by standard deviations [Farkas, [1981]]. It is important to add an indication of how far above the normal standard the head circumference is if an accurate assessment of this can be made. Macrocephaly is an absolute term. The term relative macrocephaly can be used when the head size centile exceeds the centile for height, for example, head size at the 75th centile with height at the 5th centile for age and sex." ;
    dc:description "Objective Description: Occipitofrontal (head) circumference greater than 97th centile compared to appropriate, age matched, sex-matched normal standards; Subjective Description: Apparently increased size of the cranium" ;
    OIO:hasRelatedSynonym " OFC, enlarged",
        "Head circumference, enlarged",
        "Macrocranium" ;
    rdfs:subClassOf :MONARCH_phenotype ;
    owl:equivalentClass OBO:HP_0000256 ;
    foaf:depiction "http://elementsofmorphology.nih.gov/images/terms/Macrocephaly-large.jpg",
        "http://elementsofmorphology.nih.gov/images/terms/Macrocephaly-small.jpg" ;
    foaf:page "http://elementsofmorphology.nih.gov/index.cgi?tid=1d53660e657259f0" .

**Comment by pnrobinson** [comment]
By the way, there appears to be an extra white space here, which at worst will cause difficult to debug problems with downstream applications. Please be sure to trim off leading and trailing white space!
cheers Peter

OIO:hasRelatedSynonym " OFC, enlarged",


Dr. med. Peter N. Robinson, MSc.
Professor of Medical Genomics
Professor in the Bioinformatics Division of the Department of Mathematics and Computer Science of the Freie Universit�t Berlin
Institut f�r Medizinische Genetik und Humangenetik
Charit� - Universit�tsmedizin Berlin
Augustenburger Platz 1
13353 Berlin
Germany
+4930 450566006
Mobile: 0160 93769872
peter.robinson@charite.de
http://compbio.charite.de
http://www.human-phenotype-ontology.org
Introduction to Bio-Ontologies: http://www.crcpress.com/product/isbn/9781439836651
I have learned from my mistakes, and I am sure I can repeat them exactly
ORCID ID:http://orcid.org/0000-0002-0736-9199
Scopus Author ID 7403719646
Appointment request: http://doodle.com/pnrobinson
________________________________________
Von: Bryan Laraway [notifications@github.com]
Gesendet: Samstag, 21. Februar 2015 00:13
An: monarch-initiative/dipper
Betreff: Re: [dipper] add elements of morphology (#41)

Reassigning to @mbrush<https://github.com/mbrush> for QA.

Here is example output from one of the terms that has entries for each variable:

OBO:EOM_1d53660e657259f0 a owl:Class ;
rdfs:label "Macrocephaly" ;
dc:comment "Head circumference is measured from just above the glabella (the most prominent point on the frontal bone above the root of the nose) to the most posterior prominent point of the occipital bone using a tape measure. Some standard charts are organized by centiles [Hall et al., [2007]], others by standard deviations [Farkas, [1981]]. It is important to add an indication of how far above the normal standard the head circumference is if an accurate assessment of this can be made. Macrocephaly is an absolute term. The term relative macrocephaly can be used when the head size centile exceeds the centile for height, for example, head size at the 75th centile with height at the 5th centile for age and sex." ;
dc:description "Objective Description: Occipitofrontal (head) circumference greater than 97th centile compared to appropriate, age matched, sex-matched normal standards; Subjective Description: Apparently increased size of the cranium" ;
OIO:hasRelatedSynonym " OFC, enlarged",
"Head circumference, enlarged",
"Macrocranium" ;
rdfs:subClassOf :MONARCH_phenotype ;
owl:equivalentClass OBO:HP_0000256 ;
foaf:depiction "http://elementsofmorphology.nih.gov/images/terms/Macrocephaly-large.jpg",
"http://elementsofmorphology.nih.gov/images/terms/Macrocephaly-small.jpg" ;
foaf:page "http://elementsofmorphology.nih.gov/index.cgi?tid=1d53660e657259f0" .

�

**Comment by nlwashington** [comment]
@nicolevasilevsky we seem to be missing mappings for:
Naris, Narrow
Foot, Osseous Syndactyly of
Hand, Osseous Syndactyly of

**Comment by nlwashington** [comment]
@pnrobinson i stripped out the leading/trailing whitespace in commit dcd14df
<pre>
OBO:EOM_1d53660e657259f0 a owl:Class ;
    rdfs:label "Macrocephaly" ;
    OBO:IAO_0000115 "Objective Description: Occipitofrontal (head) circumference greater than 97th centile compared to appropriate, age matched, sex-matched normal standards",
        "Subjective Description: Apparently increased size of the cranium" ;
    dc:comment "Head circumference is measured from just above the glabella (the most prominent point on the frontal bone above the root of the nose) to the most posterior prominent point of the occipital bone using a tape measure. Some standard charts are organized by centiles [Hall et al., [2007]], others by standard deviations [Farkas, [1981]]. It is important to add an indication of how far above the normal standard the head circumference is if an accurate assessment of this can be made. Macrocephaly is an absolute term. The term relative macrocephaly can be used when the head size centile exceeds the centile for height, for example, head size at the 75th centile with height at the 5th centile for age and sex." ;
    OIO:hasExactSynonym "Head circumference, enlarged",
        "Macrocranium",
        "OFC, enlarged" ;
    owl:equivalentClass OBO:HP_0000256 ;
    foaf:depiction "http://elementsofmorphology.nih.gov/images/terms/Macrocephaly-large.jpg",
        "http://elementsofmorphology.nih.gov/images/terms/Macrocephaly-small.jpg" ;
    foaf:page "http://elementsofmorphology.nih.gov/index.cgi?tid=1d53660e657259f0" .
</pre>

**Comment by nlwashington** [comment]
i also changed it so that the two definitions are added (as a list) with the IAO:definition property, rather than combined into a single string.

**Comment by nicolevasilevsky** [comment]
This term is in HPO: 
Naris, Narrow is Narrow naris HP_0009933

**Comment by nicolevasilevsky** [comment]
The term requests were rejected for:
Foot, Osseous Syndactyly of
Hand, Osseous Syndactyly of

http://sourceforge.net/p/obo/human-phenotype-requests/330/

How would you like to address this?

**Comment by nlwashington** [comment]
Comparing the definitions for those two terms at EOM, and in HP, i think the mapping probably is:

Foot, Osseous Syndactyly of
http://elementsofmorphology.nih.gov/index.cgi?tid=01f3cc71dd4c3b9d
http://purl.obolibrary.org/obo/HP_0010717

Hand, Osseous Syndactyly of
http://elementsofmorphology.nih.gov/index.cgi?tid=6058e1a1964f9cb8
http://purl.obolibrary.org/obo/HP_0010492

What do you think @nicolevasilevsky ?

**Comment by nlwashington** [comment]
we need to put the tab-delimited mapping file someplace public.  @cmungall shall we add it to phenotype-ontologies googlecode?

**Comment by cmungall** [comment]
1:2 mapping

**Comment by cmungall** [comment]
yes unless @drseb has done this already (don't see it in src/mappings/ 
in the hpo repo)

**Comment by nlwashington** [comment]
i don't see a standard place for mapping files in phenotype-ontologies repo.  let me know where the file should live.  (and no, i don't think that @drseb has it, because @nicolevasilevsky is the one who generated the mappings)

**Comment by cmungall** [comment]
how about

    mkdir src/ontologies/hp/mappings

and call it `hp-to-eom-mapping.tsv`

**Comment by nlwashington** [comment]
done.  added at https://phenotype-ontologies.googlecode.com/svn/trunk/src/ontology/hp/mappings/hp-to-eom-mapping.tsv

**Comment by nlwashington** [comment]
i've now added this as a job on bamboo:  https://bamboo.crbs.ucsd.edu/browse/MON-DE
will test loading into scigraph later this week.  will close when links between HP and images can be verified.

**Comment by drseb** [comment]
Hi.

> done. added at https://phenotype-ontologies.googlecode.com/svn/trunk/src/ontology/hp/mappings/hp-to-eom-mapping.tsv

Now we have hp-mappings at three different places:
- in hp itself as xrefs
- the (Orphanet, Medra, UMLS, LDDB) mappings I created with Peter and Sandra at http://compbio.charite.de/svn/hpo/trunk/src/mappings/
- https://phenotype-ontologies.googlecode.com/svn/trunk/src/ontology/hp/mappings/

Can we make a decision where we should collect the mappings? (My vote goes for hp)

Best,
Sebastian

**Comment by nlwashington** [comment]
this is nearly finished. awaiting SciCrunch/SciGraph#94 for final testing to get at depictions.

**Comment by nlwashington** [comment]
the image links are available as node properties, like here:
http://rosie.crbs.ucsd.edu:9000/scigraph/graph/EOM_01f3cc71dd4c3b9d.graphson or
http://rosie.crbs.ucsd.edu:9000/scigraph/graph/EOM_01f3cc71dd4c3b9d.gml
