### ISSUE TITLE
Some nodes have several taxon labels

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/dipper#415]
iri:http://purl.obolibrary.org/obo/CHR_9606chr4q28.3
http://www.w3.org/2000/01/rdf-schema#label:chr4q28.3 (Human),4q28.3
label:chr4q28.3 (Human),4q28.3category
neo4j label: sequence feature

It creates issues on my side to generate the search golr core. It expects a single taxon label.

**Comment by kshefchek** [comment]
fixed with https://github.com/monarch-initiative/dipper/pull/418

**Comment by kshefchek** [comment]
this is challenging and to this day we still have taxa with >1 labels, in the last load,

http://purl.obolibrary.org/obo/NCBITaxon_9515

Cebus apella
Sapajus apella

http://purl.obolibrary.org/obo/NCBITaxon_8364

Xenopus (Silurana) tropicalis
Xenopus tropicalis

http://purl.obolibrary.org/obo/NCBITaxon_11908

Human T-cell leukemia virus type I
Human T-lymphotropic virus 1

Proposing we track these in the QC reports for each data load and accept it as unavoidable

**Comment by cmungall** [comment]
How does this arise? This is all coming from a single version of ncbitaxon?
If we switch to base modules it should help

**Comment by kshefchek** [comment]
it comes from some ontologies hard importing stale versions of NCBI taxon, NCBITaxon:9515 comes from eagle-i (do we need eagle-i in scigraph?)
https://github.com/monarch-initiative/dipper/blob/master/translationtable/GLOBAL_TERMS.yaml#L141

**Comment by cmungall** [comment]
I don't think we need eagle-i

Better use of base modules will fix all this
