### ISSUE TITLE
add chr cyto band maps for human

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#42]
We need to add cytogenic band features, and make them available for search and display.  
We basically need to ontologize cytogenic band files.
Let's start with the human map:
http://hgdownload.cse.ucsc.edu/goldenPath/hg19/database/cytoBand.txt.gz
But the solution should be generalizable for any organism, and mapped to faldo.

For this example data:
chr1    0       2300000 p36.33  gneg
chr1    2300000 5400000 p36.32  gpos25
chr1    5400000 7200000 p36.31  gneg

For each band, we'd end up with a structure like:
_9606chr1p36.33 rdf[type] SO:chromosome_band, faldo:RegionSet
_9606chr1p36 contained_in _9606chr1p36.3
_9606chr1p36 faldo:location [ faldo:start 0 faldo:2300000]

(ideally we'd properly type the band itself with the gneg / gpos / etc type of band, but a term request is needed)

each of the bands themselves would need to be connected to the nested band they are part of, with the top level element being the full chromosome:  

_:9606chr1 rdf[type] SO:chromosome, faldo:RegionSet
_:9606chr1 in taxon NCBITaxon:9606
_:9606chr1 faldo:location [ faldo:start 0 ; faldo:end bazillion]

_9606chr1p rdf[type] SO:chromosome_arm, faldo:RegionSet
_9606chr1p partof _:9606chr1
_9606chr1p faldo:location [ faldo:start 0 ; faldo:end half-bazillion]

then the repeated (nested) pattern of the chr bands, like:

_9606chr1p3 rdf[type] SO:chromosome_band, faldo:RegionSet
_9606chr1p3 partof _9606chr1p
_9606chr1p3 faldo:location [ faldo:start 0 faldo:end a little less]

for more info on how to interpret the notation (with a nice figure):
http://ghr.nlm.nih.gov/handbook/howgeneswork/genelocation

**Comment by nlwashington** [comment]
i wonder if we should we materialize interband (SO:0000450) regions that are not in the files?

**Comment by selewis** [comment]
For display purposes (i.e. graphics) we'd ideally like linearly ordered
bands+interbands to produce a fully contiguous chromosome with no gaps or
overlaps.

**Comment by nlwashington** [comment]
oh, the interband regions are materialized with "gneg"

**Comment by pnrobinson** [comment]
What exactly is an interband region? I thought that chromosomes could be partitioned into bands (i.e., without remainder)?
-Peter

Dr. med. Peter N. Robinson, MSc.
Professor of Medical Genomics
Professor in the Bioinformatics Division of the Department of Mathematics and Computer Science of the Freie Universität Berlin
Institut für Medizinische Genetik und Humangenetik
Charité - Universitätsmedizin Berlin
Augustenburger Platz 1
13353 Berlin
Germany
+4930 450566006
Mobile: 0160 93769872
peter.robinson@charite.de
http://compbio.charite.de
http://www.human-phenotype-ontology.org
Introduction to Bio-Ontologies: http://www.crcpress.com/product/isbn/9781439836651
I have learned from my mistakes, and I am sure I can repeat them exactly
ORCID ID:http://orcid.org/0000-0002-0736-9199
Scopus Author ID 7403719646
Appointment request: http://doodle.com/pnrobinson
________________________________________
Von: Nicole Washington [notifications@github.com]
Gesendet: Freitag, 23. Januar 2015 20:34
An: monarch-initiative/dipper
Betreff: Re: [dipper] add chr cyto band maps for human (#42)

i wonder if we should we materialize interband (SO:0000450) regions that are not in the files?

**Comment by nlwashington** [comment]
@pnrobinson i reread the SO definition of interband, and it doesn't quite fit here like i thought it had... it seems specific for polytene chromosomes.  i believe the chromosome section of SO needs a lot of work. http://sequenceontology.org/browser/current_svn/term/SO:0000830

for now, i am typing all pos/neg bands as generic "bands", (see #43) but we will need to refactor this part of SO, or model it better in GENO.  additionally, it is presently a bit clunky to map the containing regions of a chromosome band, since i have to map it to the generic parent of both chr_band and chr_arm.

**Comment by nlwashington** [comment]
i've computed the coordinates for the nested chromosomal regions.  also i've put the described banding pattern into the DC:description, until such time as we have the appropriate disambiguating SO or GENO terms.  here's an example of the results.  
<code>

    <http://www.monarchinitiative.org/9606chr10q11> a faldo:Region,
        OBO:SO_0000830 ;
    rdfs:label "chr10q11" ;
    faldo:begin "40200000"^^xsd:int ;
    faldo:end "52900000"^^xsd:int ;
    OBO:RO_0002525 <http://www.monarchinitiative.org/9606chr10q1>

    <http://www.monarchinitiative.org/9606chr10q11.2> a faldo:Region,
        OBO:SO_0000830 ;
    rdfs:label "chr10q11.2" ;
    faldo:begin "42300000"^^xsd:int ;
    faldo:end "52900000"^^xsd:int ;
    OBO:RO_0002525 <http://www.monarchinitiative.org/9606chr10q11> .

    <http://www.monarchinitiative.org/9606chr10q11.21> a faldo:Region,
        OBO:SO_0000341 ;
    rdfs:label "chr10q11.21" ;
    faldo:begin "42300000"^^xsd:int ;
    faldo:end "46100000"^^xsd:int ;
    OBO:RO_0002525 <http://www.monarchinitiative.org/9606chr10q11.2> ;
    dc:description "gneg" .

</code>

**Comment by nlwashington** [comment]
@mbrush close if satisfied.
