### ISSUE TITLE
ClinVar: lost gene-variant mappings

### ISSUE THREAD

**Issue by TomConlin** [monarch-initiative/dipper#420]
continued from  https://github.com/monarch-initiative/monarch-app/issues/1398

**Comment by mbrush** [comment]
@TomConlin  the list of variant categories you pulled back using

     xmlstarlet sel -t -v './ReleaseSet/ClinVarSet/ReferenceClinVarAssertion/MeasureSet/Measure/@Type' ClinVarFullRelease_00-latest.xml.gz  | sort | uniq -c | sort -nr

may not be querying the right place to return the categories we need, as the list seems to be missing 'haplotype' which was the category that motivated us to look at this in the first place.  Could there be another element in the xml that we need to hit?  or perhaps this set of categories is encoded outside the xml data itself?

**Comment by TomConlin** [comment]
the other logical place to look is the same field within the SCVs

    $ xmlstarlet sel -t -v './ReleaseSet/ClinVarSet/ClinVarAssertion/MeasureSet/Measure/@Type' ClinVarFullRelease_00-latest.xml.gz  | sort | uniq -c | sort -nr
     355876 Variation
      30305 single nucleotide variant
       7936 copy number gain
       7294 copy number loss
       2398 Deletion
        965 Duplication
        251 Translocation
        217 Indel
        186 Insertion
         38 Complex
          4 Tandem duplication
          1 Inversion

nope not there either.
How about up a level?  
  
    xmlstarlet sel -t -v './ReleaseSet/ClinVarSet/ClinVarAssertion/MeasureSet/@Type' ClinVarFullRelease_00-latest.xml.gz  | sort | uniq -c | sort -nr
     404920 Variant
        164 CompoundHeterozygote
         95 Haplotype
  
okay something there but not enough to say so.
how about up a level in the RCV?  
    xmlstarlet sel -t -v './ReleaseSet/ClinVarSet/ReferenceClinVarAssertion/MeasureSet/@Type' ClinVarFullRelease_00-latest.xml.gz  | sort | uniq -c | sort -nr
     365344 Variant
        258 Haplotype
        175 CompoundHeterozygote
         5 Phase unknown
          1 gene-variant
          1 Distinct chromosomes

 Well I guess that is about as good as it gets.

**Comment by mbrush** [comment]
Interesting.  So it seem that we need to interrogate two elements in the RCV to determine how to rdf:type variants in ClinVar:
 
    /ReleaseSet/ClinVarSet/ReferenceClinVarAssertion/MeasureSet/@Type
 
seems to describe the zygosity and cis/trans nature for VSLC  variants, and gives us:
 365344 Variant
    258 Haplotype
    175 CompoundHeterozygote
     5 Phase unknown
      1 gene-variant
      1 Distinct chromosomes
 
and one level down
 
     /ReleaseSet/ClinVarSet/ReferenceClinVarAssertion/MeasureSet/Measure/@Type

seems to describe types for single variants, and gives us:
 306280 single nucleotide variant
  27984 Deletion
  10886 Duplication
   7819 copy number gain
   7142 copy number loss
   2744 Insertion
   2152 Indel
   584 Variation
   252 Translocation
   240 Microsatellite
    96 protein only
    38 Complex
    31 Inversion
     8 fusion
 
So, when the first value from /MeasureSet/@Type is 'Variant', defer to the second value from /MeasureSet/Measure/@Type and use mapping of these terms to SO classes.
 
When the first value from /MeasureSet/@Type is 'Haplotype', the  ClinVar variant we create is an instance of a GENO:0000871 ! 'haplotype'.
 
When the first value from /MeasureSet/@Type is 'Complex Heterozygote', the  ClinVar variant we create is an instance of a GENO:0000030 ! 'variant single locus complement', and we add a triple from this VSLC individual that describes its zygosity (predicate is GENO:0000608 ! has_zygosity, and object is   GENO:0000402 ! 'complex heterozygous').
 
Not sure yet what to do when the first value from /MeasureSet/@Type is 'Phase Unknown', 'gene-variant', or 'Distinct Chromosome'.

**Comment by TomConlin** [comment]
for the record when MeasureSet/@Type="Variant"  we will get  

    xmlstarlet sel -t -v './ReleaseSet/ClinVarSet/ReferenceClinVarAssertion/MeasureSet[@Type="Variant"]/Measure/@Type' ClinVarFullRelease_00-latest.xml.gz  | sort | uniq -c | sort -nr
     305512 single nucleotide variant
      27887 Deletion
      10864 Duplication
       7819 copy number gain
       7142 copy number loss
       2739 Insertion
       2137 Indel
        583 Variation
        252 Translocation
        240 Microsatellite
         96 protein only
         38 Complex
         30 Inversion
          8 fusion

When it is "Haplotype" we see  Measure@Types of

        486 single nucleotide variant
         35 Deletion
          9 Indel
          8 Duplication
         3 Insertion
          1 Variation
         1 Inversion

which will be ignored and `haplotype` used instead  

The Measure@Types is never "Complex Heterozygote"    
but when Measure@Types is "CompoundHeterozygote" we  get  

        274 single nucleotide variant
         60 Deletion
         13 Duplication
          4 Indel
          1 Insertion

**Comment by mbrush** [comment]
This is interesting Tom.  I think what this will let us do for Haplotypes and Compound heterozygotes is link these to their component sequence alterations, and assign types to these component alterations as captured at "Measure@Type".  

That is, rather than 'ignoring' the more atomic type of variant at "Measure@Type" for haplotypes and compound hets, we create instances of the variants these contain, and link them as variant_parts of the parent haplotype/compound het.  I think this is very important to do, assuming this info is provided in the source data.
 
@tomconlin can you generate an small xml file with a few records each where MeasureSet/@Type="Haplotype" and MeasureSet/@Type="Compound Heterozygote"?   Then I can look at the data to confirm that we can create these new nodes and relations, and update the camp/model accordingly.  Should be pretty simple, and seems important data to include in our ingest.

**Comment by TomConlin** [comment]
Sure @mbrush  as we speak I am rewriting a clinvar subsetter in python  because the previous xmlstarlet based one uses too much memory for laptops and is too slow on the servers , so while I am working on that why don't you round up some RCV you would like to test,  it should be pretty simple.

**Comment by mbrush** [comment]
Sure, in addition to the carefully selected set of example RCVs we already use for ClinVar QA, you could add the following:
 
**Haplotype RCVs:**
https://www.ncbi.nlm.nih.gov/clinvar/RCV000256457/
https://www.ncbi.nlm.nih.gov/clinvar/RCV000408532/
 
**Compound heterozygote**
https://www.ncbi.nlm.nih.gov/clinvar/RCV000197749/
https://www.ncbi.nlm.nih.gov/clinvar/RCV000087646/

And if you could provide a subset xml doc for these so i can look at the source data to spec the transform, that would be great as well.

**Comment by kshefchek** [comment]
I'm pretty sure this is fixed by @TomConlin please reopen if not.  The compound het stuff has been moved to https://github.com/monarch-initiative/dipper/issues/459
