### ISSUE TITLE
Define standard workflow and templates for documenting new data source ingests and updates

### ISSUE THREAD

**Issue by mbrush** [monarch-initiative/dipper#422]
Goal is to define conventions for how new source ingests (or updates to ingested sources) are described, tracked, and documented throughout their ingest cycle. The initial proposal below targets some simple first steps - essentially defining best practices around the things we already do and artifacts we already generate.  It also provides templates to support more efficient and consistent implementation of these best practices.   

As detailed below, all documentation of ingest status and generated artifacts will live in one of the following locations:.

1. **[Github Ingest Tickets](https://github.com/monarch-initiative/dipper/issues/422)**: An "_Add Source_" ticket for describing each initial source ingest, hosting high-level discussion, and linking to key artifacts. If needed a second "_Update Source_" ticket can be used to track subsequent improvements after initial ticket is closed.
2. **[Monarch Ingest Dashboard](https://docs.google.com/spreadsheets/d/1V228YQ2JFJl9Hjwv5UXkyZpLy3JJbGC8Xz_WgqPUeXM/edit#gid=707993175)**: A central spreadsheet for tracking source ingest status and priority (currently a Google Spreadsheet).
3. **[Ingest Artifact Folders](https://github.com/monarch-initiative/dipper/tree/master/docs)**: A central location for storing artifacts related to data **modeling** (e.g. cmaps and translation tables), **exploration** (e.g. Python notebooks and curated source datasets), and **QA** (currently in /docs directory of Dipper Github repo)
4. **[Ingest and QA Logs](https://drive.google.com/drive/u/0/folders/0ByKzIoedGeqJVHlxY0x5QXRVT0U)**:  A single doc per source for logging more _granular_ developer discussions related to data exploration and QA (currently Google docs - but propose to move to a Github ticket)

**Comment by mbrush** [comment]
**Initial proposal:**  Cut and past markdown text below into initial description of any new "Ingest Data Source" ticket, and populate relevant fields as possible throughout ingest cycle.

---
- **Source Name:**  
- **Source Data Description:** 
- **Source Data Extraction**
     - _Source Data Location_:  
     - _Source Contact(s):_  
- **Source Data Exploration**
     - _Source Documentation:_  
     - _Dipper Python Notebook(s):_   
     - _Dipper-Curated Source Datasets:_  
- **Data Modeling and Transformation**
     -  _Target Model Cmaps_:  
- **Generated Data QA**
     - _Dipper Test.ttl file:_  
     - _Dipper QA Notes Doc:_  
     - _Dipper Python Notebook(s):_  
     - _Other (unit tests?, cypher queries?):_   
- **Final Documentation**
     - _Public Cmaps:_  
     - _Developer Cmaps:_

**Comment by mbrush** [comment]
Proposed Template for "Add Source" tickets:
-----


- **Source Name:**  
- **Source Data Description:** 
- **Source Data Exploration**
     - _Source Data Location_:  
     - _Source Contact(s):_  
     - _Source Documentation:_  
     - _Dipper Python Notebook(s):_   
     - _Dipper-Curated Source Datasets:_  
- **Data Modeling and Transformation**
     -  _Target Model Cmaps_:  
- **Generated Data QA**
     - _Dipper Test.ttl file:_  
     - _Dipper QA Notes Doc:_  
     - _Dipper Python Notebook(s):_  
     - _Other (unit tests?, cypher queries?):_   
- **Documentation**
     - _Public Cmaps:_  
     - _Developer Cmaps:_

**Comment by mbrush** [comment]
**Alternate Proposal:** Requires more granular addition of links to each individual artifact, instead of simple check boxes to indicate which have been generated, and links to the general locations where the artifacts can be found.

----------------------------------


- **Source Name:**  
- **Source Data Description:** 
- **Source Data Exploration**
     - _Source Data Location_:  
     - _Source Contact(s):_  
     - _Source Documentation:_  
     - _Dipper Python Notebook(s):_   
     - _Dipper-Curated Source Datasets:_  
- **Data Modeling and Transformation**
     -  _Target Model Cmaps_:  
     -  _Translation table_:
- **Generated Data QA**
     - _Dipper Test.ttl file:_  
     - _Dipper QA Notes Doc:_  
     - _Dipper Python Notebook(s):_  
     - _Other (unit tests?, cypher queries?):_   
- **Documentation**
     - _Public Cmaps:_  
     - _Developer Cmaps:_

**Comment by cmungall** [comment]
Have we consider github projects (kanban board) in place of a spreadsheet

**Comment by mbrush** [comment]
Yes, we ultimately want a more automated approach for generating and maintaining an ingest status and prioritization dashboard. I do plan to explore the features provided by Github Projects here - to see if it can provide the features and flexibility we want.

**Comment by mbrush** [comment]
I moved initial draft of DIPper Best Practices and Workflow Conventions into wiki doc [here](https://github.com/monarch-initiative/dipper/wiki/Developer-Workflow-and-Documentation-Conventions).  Note that they no longer prescribe the detailed template for each add source.  Rather, the types an locations of relevant ingest artifacts  will be documented in this wiki page instead of each separate ticket.

**Comment by jmcmurry** [comment]
Julie to investigate zenhub and cross-org permissioning / accounts.

**Comment by kshefchek** [comment]
:thumbsup:
