### ISSUE TITLE
Cycle for NCBITaxon_1827

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/dipper#426]
There a conflicting axiom: monarch.owl is defining NCBITaxon_1831 as a subclass of NCBITaxon_1827, and according to SciGraph, flybase.ttl which has an equivalentClass between those two taxons.

I think that flybase needs to be fixed.

**Comment by kshefchek** [comment]
grep 'NCBITaxon_1827' flybase.nt 
<https://monarchinitiative.org/.well-known/genid/1cff3dc5a02a4b17e80> <http://www.w3.org/2002/07/owl#sameAs> <http://purl.obolibrary.org/obo/NCBITaxon_1827> .
grep 'NCBITaxon_1831' flybase.nt 
...
<http://purl.obolibrary.org/obo/NCBITaxon_1831> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2002/07/owl#Class> .
...
<http://purl.obolibrary.org/obo/NCBITaxon_1831> <http://www.w3.org/2002/07/owl#equivalentClass> <https://monarchinitiative.org/.well-known/genid/1cff3dc5a02a4b17e80> .
<http://purl.obolibrary.org/obo/NCBITaxon_1831> <http://www.w3.org/2000/01/rdf-schema#label> "Rhodococcus sp." .
...

Lot's of stuff wrong here, we shouldn't be assigning labels that are coming from NCBITaxon.owl, and we need to determine why there's a blank node being created here, and why the hashing isn't sufficient to be unique for one taxon.

**Comment by kshefchek** [comment]
fixed with https://github.com/monarch-initiative/dipper/pull/435
