### ISSUE TITLE
Orphanet mapping granularity

### ISSUE THREAD

**Issue by TomConlin** [monarch-initiative/dipper#431]
Should we increase the granularity of Orphanet mappings?
we currently set all  orphanet gene-disorder as one of 
 -  'has_phenotype' 
 -  'contributes_to'

or discard it.  
Orphanet provides more then two categories. 

```
  #   id      'has_phenotype'  RO:0002200
---- -----    -----------------------------------
4185 17949    Disease-causing germline mutation(s) in
 148 17955    Disease-causing somatic mutation(s) in 
 188 25979    Disease-causing germline mutation(s) (gain of function) in
 925 25972    Disease-causing germline mutation(s) (loss of function) in
 
              'contributes_to'  RO:0002326
---- -----    ---------------------------     
 510 17961    Major susceptibility factor in
  38 17967    Modifying germline mutation in
  35 17973    Modifying somatic mutation in
 218 17979    Part of a fusion gene in 
 217 17985    Role in the phenotype of

              ignored
              -----------------------
 178 18273    Candidate gene tested in
```

SO has  loss/gain of function terms   
but it may be a stretch to apply them directly to Orphanet assertions.

**Comment by cmungall** [comment]
For disease-gene, yes. Coordinate with @pnrobinson on the set used and with @mbrush on aligning with RO

**Comment by mbrush** [comment]
The stub of a ticket for the work of defining what gene-disease relations RO will create is [here](https://github.com/oborel/obo-relations/issues/146).

Proposed Wikidata gene-disease relations to coordinate  this work with is [here](https://www.wikidata.org/wiki/User:ProteinBoxBot/Gene-disease_links#Properties).

**Comment by kshefchek** [comment]
Addressing this in https://github.com/monarch-initiative/dipper/pull/602

**Comment by monicacecilia** [comment]
@kshefchek, thanks for all the work on #602. 

Kent's PR in dipper (#602 Improve ingests and modeling of human g2p data) addressed increased granularity of Orphanet mappings and added new relations from RO.  I am the least familiar with the model and want to ask whether this was also done in agreement with the [Wikidata gene-disease relations](https://www.wikidata.org/wiki/User:ProteinBoxBot/Gene-disease_links#Properties) (that Matt and @cmungall brought up).

@mbrush, have you had a chance to look over the updates? Have your suggestions been addressed?

If so, can this issue be **closed** now? 

And if so, is [# 23 in monarch-cypher-queries ](https://github.com/monarch-initiative/monarch-cypher-queries/issues/23)(define tighter constraints for gene to phenotype query paths/joins) also ready to be re-closed?


_(apologies for the quick trigger - you may have seen an earlier version of this comment fly by your inbox)_

**Comment by cmungall** [comment]
This is high priority, should be tracked in a project

As a general rule, rolling up relations is something we should do after a great deal of consideration. Why would someone want to use data from Monarch when they can get more granular information from source or an alternate ingest?

Aside; looking at:
https://github.com/monarch-initiative/dipper/blob/master/translationtable/orphanet.yaml

Is mapping between pairs of rdfs:labels a robust strategy? I suggest we manage things like this as equivalentProperty axiom bridges in RO

**Comment by kshefchek** [comment]
@cmungall agreed, it would be great to fix these relations.  As a side note I think lines 3-10 refer to terms that are no longer in the xml and should be removed.

**Comment by justaddcoffee** [comment]
Is this something I could help with? (Possibly throwing myself into the deep end here...)

**Comment by kshefchek** [comment]
@justaddcoffee yes that would be great

**Comment by kshefchek** [comment]
fixed with https://github.com/monarch-initiative/dipper/pull/722
