### ISSUE TITLE
Weird NaN label as double type

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/dipper#433]
While working on the search solr core, I get this weird label typesd as a double which breaks my code. It expects a String.

```
bgee.ttl:427506318:ENSEMBL:FBgn0036414 a OBO:SO_0000704 ;
bgee.ttl-427506357-    rdfs:label "NaN"^^xsd:double ;
```

**Comment by kshefchek** [comment]
The gene symbol is "nan" - pandas might be converting these to null NaN values.  We should remove label assignment from BGEE since these should be coming from elsewhere.  We also need to replace ENSEMBL:FBgn with FlyBase:FBgn, or establish equivalence between these two.

**Comment by lwinfree** [comment]
Oh that's a horrible gene name for data analysis >.<

**Comment by cmungall** [comment]
I can't believe our beloved python pandas is doing this. How could you 
pandas, I thought you were better than excel.

**Comment by kshefchek** [comment]
Fixed with https://github.com/monarch-initiative/dipper/pull/435
