### ISSUE TITLE
Use biomart API for up-front mapping and to simplify Ensembl module

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/dipper#444]
Consider replacing

E.g.
https://github.com/monarch-initiative/dipper/blob/077ac9672c3cbd9af19a620fa2644725899a115f/dipper/sources/Ensembl.py#L134-L200

(lots of hardcoded species..)

with https://pypi.python.org/pypi/biomart/

We may also want to use this for sources like string, that use ENSP. While we could delay mapping to clique merge stage, this may be expensive and without much gain.

It may be simpler to up-front map. ie. the String.py module would use biomart.py to get ENSP->Gene for each species and map as part of ingest.

**Comment by kshefchek** [comment]
Chatted with this last week with @mellybelly and @mbrush and they both felt strongly we leave the ENSP to ENSP relations instead of summing to the gene level at ingest time.

**Comment by kshefchek** [comment]
I reread some docs today that point to String not mapping data at the protein level, but rather using a single isoform as a placeholder:

STRING uses one protein per gene. If there is more than one isoform per gene, we usually select the longest isoform, unless we have information that suggest that other isoform regarded as cannonical (e.g., proteins in the CCDS database).

From http://string-db.org/cgi/help.pl, FAQ

Perhaps we should reconsider an upfront mapping to genes? cc @mellybelly @mbrush

**Comment by kshefchek** [comment]
Fixed with https://github.com/monarch-initiative/dipper/pull/478
