### ISSUE TITLE
Add Source: CIViC

### ISSUE THREAD

**Issue by mbrush** [monarch-initiative/dipper#445]
**Source Name:** 
CIViC (Clinical Interpretation of Variants in Cancer)
  
**Source Data Description:**
CIVIC data is a crowd-sourced, variant-centric database that holds **four types of assertions** curated from the literature about the clinical relevance of genetic variants to cancer:
1.  *Diagnostic* claims that a variant is associated with a particular type (or subtype) of cancer (but not necessarily causal? - i.e. could this be a marker or non-driver mutation?)
2.  *Predictive* claims that a variant confers sensitivity or resistance to a treatment (in the context of a particular cancer)
3.  *Prognostic* claims that a variant impacts disease progression, severity, or patient survival
4. *Predisposition* claims that a variant increases likelihood of developing a particular cancer)
  
**Scope of Ingest:**
Take 'predictive' associations first,  specific elements to be ingested on first pass is TBD. 

**Source Data Location:** 
Data releases (tsv): https://civic.genome.wustl.edu/#/releases
API:  https://genome.github.io/civic-api-docs/
  
**Source Documentation:**  
FAQ links to all relevant documentation are here: https://civic.genome.wustl.edu/#/faq

**Additional Notes:**

**Comment by mbrush** [comment]
Note that Wikidata ingests this resource already - and may be a possible route of ingest into SciGraph.  We should explore if their ingest includes all data/metadata we would want, e.g. regarding evidence and provenance.  

One potential issue is that in cases where a variant effect is assessed for two drugs used in combination, WD seems to make separate 'claims' that the variant confers sensitivity or resistance to each drug individually. This doesn't seem right  - but more complex modeling would be needed to handle cases of combination therapies.

**Comment by kshefchek** [comment]
replaced by https://github.com/monarch-initiative/dipper/issues/813
