### ISSUE TITLE
>10 new data sources and 40 species/strains, adding 200,000 new associations

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/dipper#453]
Per R24 [here](https://docs.google.com/document/d/1s5waFXyzyYz8oZe6MYZ4WwTb1BzdTgki-PiQ7JTmRfE/edit).

**Comment by kshefchek** [comment]
New sources:
- Rat Genome Database
- Saccharomyces Genome Database
- MyChem (not yet in our production db)

@TomConlin @putmantime @mbrush am I missing any?
