### ISSUE TITLE
WBGene IDs and RGD should be clique leaders over NCBIGene

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/dipper#455]
See https://monarchinitiative.org/gene/MGI:97490#homologs

Noticed by @selewis here: https://github.com/biolink/biolink-api/issues/66

**Comment by kshefchek** [comment]
We could use this as an opportunity to improve our current gene clique strategy, which is to hard code prefix:123 rdf:type cliqueLeader in various dipper scripts.  I would think a taxon specific configuration in scigraph would be preferred.

**Comment by mellybelly** [comment]
I like the idea that the preferred ID is the nomenclature authority (e.g. mostly MODs, HGNC). Also, how does this relate to the various ortholog calling methods, Quest for Orthologs?

**Comment by selewis** [comment]
Quest for Orthologs is using HGNC (genes) and UniProt (protein) identifiers for human and that's what PANTHER provides. Compara, otoh, uses ensembl gene IDs.

**Comment by kshefchek** [comment]
Replacing ticket with https://github.com/monarch-initiative/dipper/issues/466
