### ISSUE TITLE
Clinvar introduced new elements for 'CompoundHeterozygote'

### ISSUE THREAD

**Issue by TomConlin** [monarch-initiative/dipper#459]
ftp://ftp.ncbi.nlm.nih.gov/pub/clinvar/release_notes/20170504_data_release_notes.pdf

```

The May release uses a new element, GenotypeSet, to indicate that an interpretation was made about
two alleles that are on different chromosomes.This case was formerly reported as:
<MeasureSet Type="CompoundHeterozygote" ID="424841">
and is now reported as:
<GenotypeSet Type="CompoundHeterozygote" ID="424841">
    <MeasureSet Type="Variant" ID="375249">
        <Measure Type="single nucleotide variant" ID="361947">...</Measure>
    </MeasureSet>
    <MeasureSet Type="Variant" ID="375250">
        <Measure Type="single nucleotide variant" ID="361945">...</Measure>
    </MeasureSet>
</GenotypeSet>
Currently all GenotypeSets are of Type "CompoundHeterozygote", indicating a simple allele on each
chromosome. In the future we will also include GenotypeSets of Type "Diplotype", indicating a
haplotype on one or both chromosomes.
```

**Comment by kshefchek** [comment]
Per #420, we should model complex hets in this way:

    ClinVarVariant:424841 a GENO:0000030 ;
        GENO:0000608 GENO:0000402 ;
        GENO:0000382 dbSNP:80159221 ;
        GENO:0000382 dbSNP:778624615 ;
        GENO:0000845 OMIM:208900 .


Where
GENO:0000030 ! variant single locus complement
GENO:0000608 ! has_zygosity
GENO:0000402 ! complex heterozygous
GENO:0000382 ! has_variant_part
GENO:0000845 ! has_uncertain_significance_for_condition

**Comment by pnrobinson** [comment]
What does phrase "complex heterozygous" mean? Is this the same as "compound heterozygous" or intended to be a generalization?

**Comment by kshefchek** [comment]
From GENO: a heterozygous quality inhering in a locus complement comprised of two different varaint loci and no wild type locus. (e.g.fgf8a&lt;ti282a&gt;/fgf8a&lt;x15&gt;)

**Comment by pnrobinson** [comment]
In medical genetics, we would use "compound heterozygous" for this, and I have never heard complex heterozygous -- unless there is a reason for the label (e.g., used by model organisms?), it probably should be changed!

**Comment by kshefchek** [comment]
I assume this term label is more oriented to model data.  We should move this over to the GENO tracker: https://github.com/monarch-initiative/GENO-ontology/issues

**Comment by mellybelly** [comment]
That GENO def refers to a compound het

**Comment by TomConlin** [comment]
May as well note here ClinVar has now introduced a third level of typing i.e.     

       GenotypeSet ID="424700" Type="CompoundHeterozygote"
         MeasureSet ID="242681" Type="Variant"
           Measure ID="46900" Type="single nucleotide variant"
         ...
         MeasureSet ID="242682" Type="Variant"
           Measure ID="46899" Type="single nucleotide variant"
         ...

**Comment by mbrush** [comment]
@pnrobinson @mellybelly - I changed label of GENO:0000402 to 'compound heterozygote' - this is indeed correct.
 
@kshefchek  your model looks good.  I would type the clinvar variant as a GENO:0000030 ! 'variant single locus complement'.
 
I will create a ticket to implement a diplotype class in GENO - as it seems ClinVar will be annotating these in the future.

**Comment by mbrush** [comment]
Hi @TomConlin.  I added a [clinvar cmap](https://github.com/monarch-initiative/ingest-artifacts/blob/master/sources/ClinVar/Compound%20Het%20model/Clinvar_CompoundHet_20170601.cmap) with a couple compound het examples. Models omit evidence/provenance metadata as nothing is changing here for now. I also manually created an [rdf text file](https://github.com/monarch-initiative/ingest-artifacts/blob/master/sources/ClinVar/Compound%20Het%20model/ClinVar_CompoundHet_20170601.rdf) representing the first of the cmap examples as ttl and n-triples.  @kshefchek had previously indicated that this could be helpful for coding and QA of dipper scripts. LEt me know if this is useful.

Finally, as Kent noted, records for these compound hets will typically describe the two variants that comprise them, and often provide dbSNP identifiers that we can use to build an IRI for these variants.  But the dbSNP ids are not always present - you may have to consult to XML to see if maybe there are ClinvarVariant ids we can use?  If nothing, should we create these as skolemized nodes and just give them a type an a label?  

Let me know if you have questions or need anything else. Thanks!

**Comment by kshefchek** [comment]
Hoping to address this here: https://github.com/monarch-initiative/dipper/pull/729

**Comment by kshefchek** [comment]
See https://github.com/monarch-initiative/dipper/blob/master/docs/img/RCV000162061.svg
