### ISSUE TITLE
Mod Cliqueleader designations

### ISSUE THREAD

**Issue by TomConlin** [monarch-initiative/dipper#466]
Monarchs default clique leader are defined in  
https://github.com/monarch-initiative/SciGraph-docker-monarch-data/blob/master/src/main/resources/monarchLoadConfiguration.yaml.tmpl#L141

To override those defaults an identifier must  be explicitly tagged as a cliqueleader in the RDF input to SciGraph.

dipper employs  Model.makeLeader(id)  to attach an annotation property "MONARCH:cliqueLeader"  to the given id.  (can we get a legit ontological term?)

In https://github.com/biolink/biolink-api/issues/66  we have requests to add clique leader status to Flybase and Wormbase gene identifiers.  

Flybase is designating some identifiers as clique leaders but apparently either not enough or Flybase identifiers are being introduced elsewhere  

      622:         model.makeLeader(feature_id)
      911:         model.makeLeader(dbxref_id)
      1866:       model.makeLeader(did)

If there are no objections, I will designate  Wormbase gene identifiers as cliqueleaders and look into the sufficiency of the Flybase designations.

**Comment by mellybelly** [comment]
I agree, MOD IDs should be clique leaders, unless one is missing for some reason. @cmungall would the annotation property go in IAO ontology metadata?

**Comment by selewis** [comment]
And RGD as well as WB.

FlyBase appears to already be there, except there is discordance with what is in GOlr, where the prefix is FB.

**Comment by cmungall** [comment]
@TomConlin - I don't see how that yaml can be sufficient to determine the strategy, as MGI is not in there, yet MGI is (correctly) a clique leader.

https://scigraph-data.monarchinitiative.org/scigraph/graph/MGI:97490
https://scigraph-data.monarchinitiative.org/scigraph/graph/NCBIGene:18508

Everyone - software should not make assumptions about the clique leader. There is no semantic difference in being a clique leader. Any implementation of the biolink API should employ basic equivalence 'reasoning' on inputs, and many of the calls support the ability to map to preferred ID space (or can easily be mapped by a subsequent API call). Client apps should be able to use their preferred IDs, and get their preferred IDs out again.

Of course there are cases where we need to default to a leader, when exporting to limited formats, and it's polite practice to prioritize sources over aggregators (e.g. RGD over NCBIGene). But this is a presentation issue and software should not make or rely on assumptions.

**Comment by kshefchek** [comment]
Remember that clique leaders only matter for ID specific queries to scigraph.  By the time we make it to solr we write queries to the subClassOf|is_a|equivalentClass closure, so all equivalent IDs can be queried.

As Tom suggest right now we hard code these annotation axioms into the dipper code, for example for MGI: https://github.com/monarch-initiative/dipper/blob/master/dipper/sources/MGI.py#L1421

These isn't very optimal, ideally we would have a configuration with taxa specific ID spaces.  But that said, I would still like bio-link to talk to solr so we don't have to deal with clique leaders.  Otherwise any query to scigraph spanning edges needs to first go to https://scigraph-data.monarchinitiative.org/scigraph/docs/#!/dynamic/returns_the_clique_leader

**Comment by TomConlin** [comment]
@cmungall the yaml is not sufficient, hence the overrides. I am new to looking at our clique leader strategy but at first glance it seems a bit inverted. Exception to what we want should require the explicit override not what we want by default. Kent alluded to a dearth of necessary Taxon statements which would allow per species rules as a root cause for this situation.

**Comment by kshefchek** [comment]
I've mocked up a potential solution here: https://github.com/kshefchek/dipper/commit/54d1a8d231

It adds a configuration of taxon to preferred ID space mappings, which is processed when we ingest the NCBI gene db.  This does leave some room for error if a mod source has a gene identifier that is not in NCBI, but avoids us going the scigraph route.
