### ISSUE TITLE
CURIE prefix usage

### ISSUE THREAD

**Issue by TomConlin** [monarch-initiative/dipper#474]
We are generous in providing an extensive set curie prefixes to all RDF turtle files,
however we may not be fully realizing the benefits the prefixes within the files.

For example we supply  the prefix `NCBIGene:`  but despite having over six million RDF statements involving NCBIGene identifiers our prefix is only applied once and that is in error
as it expands to `https://www.ncbi.nlm.nih.gov/gene/LOC100520366` which does not exist.      

If RDF lib cannot apply the curie when emitting turtle there is no reason to include the prefix. 
If RDF iib can apply the prefixes we should see a drop in the RDF size from its current 8.4G.

**Comment by kshefchek** [comment]
https://github.com/monarch-initiative/dipper/issues/294
https://github.com/RDFLib/rdflib/issues/632

**Comment by kshefchek** [comment]
Closing, let's use the rdflib ticket for tracking.
