### ISSUE TITLE
Map deprecated Ensembl protein IDs in String-db to gene IDs

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/dipper#481]
String contains a large number of deprecated ensembl protein IDs.  In order to connect these to genes we need to ingest the gene to protein relationship along with the protein protein interaction.  This may just be a matter of pull this from older versions of ensembl (via biomart).

**Comment by kshefchek** [comment]
@julesjacobsen @drseb curious how you do this in exomiser.

**Comment by drseb** [comment]
@kshefchek do you mean in the context of PPI-analysis and STRING-data?

**Comment by drseb** [comment]
ah sorry, now I read the initial message

**Comment by drseb** [comment]
I map the protein-ids from string using their [mapping](http://string-db.org/mapping_files/entrez_mappings/). Not sure about the deprecation-issue though!

**Comment by julesjacobsen** [comment]
We don't use the Ensembl anything ids from String. We're using the entrez gene ids and I simply take the data as is. This is likely erroneous, but hopefully most of them are still relevant!

**Comment by drseb** [comment]
@kshefchek can you comment/investigate, if the deprecated protein IDs are still an issue after mapping to entrez?

**Comment by kshefchek** [comment]
@drseb @julesjacobsen thanks! Yes I'll go that route and see if I can still not resolve any ENSP ids to genes.  I had seen the entrez mapping file but was concerned that it had not been updated in 2 years.  But it's also possible there have not been any updates, I imagine protein to gene mapping is pretty stable.

**Comment by kshefchek** [comment]
The ncbi mapping file only provides mappings for human genes.  There are some uniprot mappings for the mods here: https://string-db.org/mapping_files/uniprot_mappings/, however, it's still unclear how to connect some of these IDs to genes.

ENSEMBL:ENSDARP00000100613 -> UniProtKB:E7F8F4

UniProt's mapping files: ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/idmapping/by_organism/ provide the mappings:

    E7F8F4  UniProtKB-ID    ASCC3_DANRE
    E7F8F4  Gene_Name       ascc3
    E7F8F4  GI      385178703
    E7F8F4  UniRef100       UniRef100_E7F8F4
    E7F8F4  UniRef90        UniRef90_E7F8F4
    E7F8F4  UniRef50        UniRef50_E7F8F4
    E7F8F4  UniParc UPI00020276FC
    E7F8F4  EMBL    CABZ01076009
    E7F8F4  EMBL    CABZ01076010
    E7F8F4  EMBL    CABZ01076011
    E7F8F4  EMBL    CABZ01076012
    E7F8F4  EMBL    CABZ01076013
    E7F8F4  EMBL    CABZ01076014
    E7F8F4  EMBL    CABZ01076015
    E7F8F4  EMBL    CABZ01076016
    E7F8F4  EMBL    CABZ01076017
    E7F8F4  EMBL    CABZ01076018
    E7F8F4  EMBL    CU468254
    E7F8F4  EMBL    CU915569
    E7F8F4  EMBL-CDS        -
    E7F8F4  NCBI_TaxID      7955
    E7F8F4  UniGene Dr.153991
    E7F8F4  STRING  7955.ENSDARP00000100613
    E7F8F4  eggNOG  KOG0952
    E7F8F4  eggNOG  COG1204
    E7F8F4  CRC64   48438FEBFAC54FF3


There are a few options:
1. We could process the UniProt mapping file and use eutils to map STRING -> GI -> NCBI gene
2. Query these out of archived versions of ensembl, for example as a starting point:

        SELECT  old_db_name
        FROM    stable_id_event
        JOIN  mapping_session USING (mapping_session_id)
        WHERE   old_stable_id = 'ENSDARP00000100613' AND score = 1
        ORDER BY old_version ASC, CAST(new_release AS UNSIGNED);

3. Map ids from symbols - using MyGene.info or our own solr search.

**Comment by julesjacobsen** [comment]
UniProt has a new API you might also consider:

https://www.ebi.ac.uk/proteins/api/doc/index.html

**Comment by cmungall** [comment]
We should test the uniprot one to see if it's aware of the deprecated ensembl IDs.

Quick google search suggests querying a biomart archive may be the best bet for dipper. Could easily pull a whole species at a time. Still a bit of a faff to determine which archive to use. E.g. https://www.biostars.org/p/149627/

But the whole situation seems a bit odd

**Comment by kshefchek** [comment]
It doesn't look like it:
https://www.ebi.ac.uk/proteins/api/proteins/Ensembl:ENSDARP00000100613?offset=0&size=100

but current ids work:
https://www.ebi.ac.uk/proteins/api/proteins/Ensembl:ENSP00000351276?offset=0&size=100

There is an ID mapping tool  here: https://www.ensembl.org/Homo_sapiens/Tools/IDMapper?db=core with an API script that is essentially a sql query:
https://github.com/Ensembl/ensembl-tools/blob/release/89/scripts/id_history_converter/IDmapper.pl

However, some of these lead to dead ends in ensembl, for example, I can query out that ENSDARP00000100613 was linked to ENSDARG00000078863, but then this gene identifier was deprecated without a replacement.  ZFIN does provide a xref mapping to this gene ID in their ID map file here: https://zfin.org/downloads/identifiersForIntermine.txt  

We will likely need species specific solutions.  For example, it looks like flybase string IDs are stored as xrefs in the ensembl fly db.  For humans we can use the string-ncbi mappings.

**Comment by kshefchek** [comment]
I've written a script here: https://github.com/monarch-initiative/dipper/blob/master/scripts/string/map-string-ids.py to resolve some of the deprecation issues.  We still end up filtering out deprecated IDs for all species, but I think this is the best we can do.
