### ISSUE TITLE
Add link to ingest-artifacts from dipper README

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/dipper#483]
We have all this lovely visual documentation completely hidden unless you are in the know:

https://github.com/monarch-initiative/ingest-artifacts/tree/master/sources

**Comment by mbrush** [comment]
Sure, will add a link to the dipper readme.   As an aside,  the rationale for storing the cmaps in separate repo from dipper code was to decouple Dipper as a general ingest tool from Dipper as used in Monarch.  This way, the Dipper repo is smaller and more generically re-usable by other folks, and not cluttered with a ton of Monarch-specific artifacts such as the cmaps which are quite large.

**Comment by mbrush** [comment]
Added link to ingest artifacts into dipper readme.
