### ISSUE TITLE
Determine score cutoff when ingesting string data

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/dipper#484]
String provides a confidence value for protein interactions described as:

"In STRING, each protein-protein interaction is annotated with one or more 'scores'.
Importantly, these scores do not indicate the strength or the specificity of the interaction. Instead, they are indicators of confidence, i.e. how likely STRING judges an interaction to be true, given the available evidence. All scores rank from 0 to 1, with 1 being the highest possible confidence. A score of 0.5 would indicate that roughly every second interaction might be erroneous (i.e., a false positive)."

Theres an example that says .4 is medium confidence:

"As an example, the model organism 'Escherichia coli K12 MG1655' is shown below — indicating the number of interactions per score type, at a confidence of 'medium' or better (score >= 0.400)"

Looking at the distribution of scores for experimental human p-p interactions, most appear to occur before .2.  The median score is .117 when removing 0s, and .043 when keeping them.  Note they multiply scores by 100 in their raw files.

![histo](https://user-images.githubusercontent.com/1467299/27346230-5cce3b8c-55a1-11e7-894f-7a98a5c34649.png)

@TomConlin provided a script that implements Otsu's method, which returns .553, but this may be invalid since the distribution is not bimodal.

Another option would be to ingest all data and the scores and allow users to filter based on their needs.  We should ingest the scores regardless.

@julesjacobsen may have some insight from working with String in exomiser.

**Comment by drseb** [comment]
Although I am not being asked, I hope it is still ok to give my two cents:
I have been and I am working with STRING a lot and also produced the interaction-matrices for Exomiser. I always used a high-confidence network, i.e. used 700 as cutoff.

**Comment by kshefchek** [comment]
@drseb of course you're being asked - I'm asking everyone!

Thanks for the info, 700 seems like a good cutoff for being relatively certain the interaction is valid.
