### ISSUE TITLE
Orphanet:284973 (Marfan syndrome type 2) has no listed phenotypes

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/dipper#486]
https://monarchinitiative.org/disease/Orphanet:284973

**Comment by kshefchek** [comment]
Poking around, it doesn't look like this is a dipper issue, will reopen a ticket in mondo.

**Comment by kshefchek** [comment]
There is a ticket here proposing Orphanet:284973 be equivalent to OMIM:610168, which will fix this issue:
https://github.com/monarch-initiative/monarch-disease-ontology/issues/101#issuecomment-294090344
