### ISSUE TITLE
Fix read the docs generation

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/dipper#490]
Right now sphinx documentation is manually generated and tends to fall behind.  We should explore options for automating this process, for example: https://github.com/rtfd/readthedocs.org/issues/1139

**Comment by cmungall** [comment]
hmm

this gets updated with every commit+push:
https://readthedocs.org/projects/ontobio/builds/

I don't think I did anything special here. I'm not sure why the dipper ones are stalled?

**Comment by cmungall** [comment]
https://github.com/biolink/ontobio/blob/master/docs/conf.py
https://github.com/monarch-initiative/dipper/blob/master/docs/conf.py

looks like you're tied to 0.0.1?

**Comment by kshefchek** [comment]
Looks we lost our webhook, I readded it and RTD is rebuilding when we push; however, the docs are still not updating. @cmungall are you sure the ontobio docs update automatically.  My understanding is that they are built from the files in your docs dir.

https://readthedocs.org/projects/dipper/builds/

**Comment by cmungall** [comment]
On 14 Jul 2017, at 9:31, Kent Shefchek wrote:

> Looks we lost our webhook, I readded it and RTD is rebuilding when we 
> push; however, the docs are still not updating. @cmungall are you sure 
> the ontobio docs update automatically.

I believe so, will check.

> My understanding is that they are built from the files in your docs 
> dir.

Correct

**Comment by kshefchek** [comment]
My goal here is to automate the api doc generation so we don't have to store, commit, and push them, they will just be generated on the fly by read the docs.  I believe this is what rtfd/readthedocs.org#1139 is describing.
