### ISSUE TITLE
ZP map, switch from Charite jenkins to new build process

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/dipper#499]
We currently pull the ZP map file from http://compbio.charite.de/jenkins/job/zp-owl-new/, but this is no longer maintained.  The new build process is outlined here:  https://github.com/Phenomics/zebrafish-phenotype-ontology and https://github.com/Phenomics/zebrafish-phenotype-ontology-build 

Depends on @drseb finishing the implementation.  Please reassign to me or @TomConlin when this is ready.

**Comment by kshefchek** [comment]
@drseb should we start pulling from the files here: https://github.com/Phenomics/zebrafish-phenotype-ontology-build ?

**Comment by balhoff** [comment]
@kshefchek I've been talking with @drseb about running the file generation via the upheno makefile and publishing there. Hopefully we'll have this running with some updates quite soon.

**Comment by cmungall** [comment]
The problem with static files in github is that they will likely get stale (the ones here at 8mo old).

They should run on some jenkins job or similar, ideally synced with whole release pipeline

**Comment by kshefchek** [comment]
Replacing with https://github.com/monarch-initiative/dipper/issues/723
