### ISSUE TITLE
handle xml data sources

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#5]
we'll need to handle parsing xml sources such as clinvar:

ftp://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/ClinVarFullRelease_00-latest.xml.gz

**Comment by nlwashington** [comment]
XML source handling example in for Orphanet.  Using iterparse can handle large files without having to pull the whole thing into memory, and should be used for when dealing with the full ClinVar in the future.

**Comment by mbrush** [comment]
re-opening as this is currently being dealt with by Tom Conlin for ingesting ClinVar XML.

**Comment by mbrush** [comment]
re-opening as this is currently being dealt with by Tom Conlin for ingesting ClinVar XML.

**Comment by mbrush** [comment]
re-closing, as is addressed by other ticket #155
