### ISSUE TITLE
add genereviews descriptions

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#51]
we want to bring in the genereviews data, like:
http://www.ncbi.nlm.nih.gov/books/NBK1262/

we may get access to this via word docs.  there are some docx parsers available, and discussions are underway with the genereviews folks about getting these.

initially, we just want to get their nice concise descriptions of the disease to augment the disease ontology.  

each of the gene reviews documents has versioning information recorded on a per-file basis.  @mbrush i am not sure how to deal with this.  can you list how we would add to the dataset description for these files?  we have this kind of information:
<pre>
Document Title	Created (YYYY-MM-DD)	Updated (YYYY-MM-DD)	Revised (YYYY-MM-DD)
(GeneReviews Project)	Label	Indicate “chapter” or “appendix”	Alternate Form (pdf)
Huntington Disease	1998-10-23	2010-04-22	2005-08-30			
</pre>
as well as specific individuals who have authored the document, like:
<pre>
Given Name(s)	Last Name	Suffix	Degrees	Affiliation	Email	CorrAu?(Yes)	Au. Footnote
Simon C	Warby		PhD	Department of Medical Genetics  University of British Columbia 
Vancouver, British Columbia, Canada	simon@cmmt.ubc.ca		
Rona K	Graham		PhD	Department of Medical Genetics University of British Columbia  Vancouver, British Columbia, Canada	ronakg@cmmt.ubc.ca 		
Michael R	Hayden		MB, ChB, PhD, FRCP(C), FRSC	Department of Medical Genetics 
University of British Columbia Vancouver, British Columbia, Canada	mrh@cmmt.ubc.ca		
</pre>

**Comment by nlwashington** [comment]
the genereviews ids and mappings to omim have been added in f9f7b54.  because the mapping between genereviews ids and omim is 1:many, i have added the genereviews ids as grouping classes.  these will need to be cleaned up manually, but this is a good start for adding to the disease ontology (@cmungall and @mellybelly).  note that because i don't know the types that the omim ids are, there may be rogue gene ids that show up as subclasses of the nbk disease ids.  also, do let me know if i should make each of the genereviews ids a subclass of genetic disease (DOID:630)...right now they are orphaned.

**Comment by selewis** [comment]
Just wondering. Might we be able to do something similar with SNOMED? If
not the definitions, then at least the IDs for analogous classes. It is
something that's been requested while here in Cambridge. I don't believe we
have this yet, although DO had the links once upon a time (links are
allowed by their licensing I believe)

On Thu, Feb 5, 2015 at 10:05 PM, Nicole Washington <notifications@github.com

**Comment by nlwashington** [comment]
we are in negotiations with genereviews folks to get access to all word docs, but probably not before the june release.  parking for now.

**Comment by nlwashington** [comment]
i notice that the copyright for the genereviews says that they grant distribution to others.  
http://www.ncbi.nlm.nih.gov/books/NBK138602/
i have inquired with GeneReviews staff again about getting this content, and with NCBI helpdesk as well.  If i get no reply, I am closing this ticket, as we cannot make any progress.

**Comment by nlwashington** [comment]
ncbi responded that they will not be distributing the genereviews work.
i have not heard back from genereviews themselves after many months of trying to contact.  therefore, i am closing this ticket.

**Comment by nlwashington** [comment]
here is the [copyright notice](http://www.ncbi.nlm.nih.gov/books/NBK138602/) from GeneReviews:

GeneReviews® chapters are owned by the University of Washington, Seattle, © 1993-2015. Permission is hereby granted to reproduce, distribute, and translate copies of content materials provided that (i) credit for source (www.ncbi.nlm.nih.gov/books/NBK1116/) and copyright (University of Washington, Seattle) are included with each copy; (ii) a link to the original material is provided whenever the material is published elsewhere on the Web; and (iii) reproducers, distributors, and/or translators comply with this copyright notice and the GeneReviews Usage Disclaimer. 

however, NCBI does not allow bulk download via robots of their content.  we can fetch it manually and process it in dipper to get the clinical descriptions.

**Comment by jmcmurry** [comment]
yay! this is so important

**Comment by nlwashington** [comment]
i am adding obo-style citation definitions, by appending ```[GeneReviews:NBK138602]``` to the definition of the term.  this may/not make it into what is displayed in the interface.

**Comment by nlwashington** [comment]
now these just have to get integrated into mondo, but is out of dipper's hands.  https://github.com/monarch-initiative/monarch-disease-ontology/issues/34
