### ISSUE TITLE
Clique leader warnings

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/dipper#520]
There are 11755 clique leader warnings (2 or more equivalent IDs are designated as clique leaders).  Some of these appear to be bugs and the IDs do not belong in the same clique. 

https://data.monarchinitiative.org/qc/archive/201709/clique-warnings.tsv

**Comment by kshefchek** [comment]
This will be tough to go through manually, maybe we need KBoom for gene cliques? @cmungall

**Comment by cmungall** [comment]
What would be helpful would be to see the paths somehow.

Actually you know maybe we should just run kboom over it. Can we query for all equivalence axioms between genes?

Or we could just do the whole mega-graph.

Do we have rough estimates for priors about who we believe more?

**Comment by cmungall** [comment]
@yy20716 will do the following

## Produce ptable.tsv input for kboom

This will be the result of a query for ALL equivalent classes across monarch. Let's do it globally! `?x owl:equivalentClass ?y`.

Cols:

 1. x
 2. y
 3. p(x SubClassOf y) = 0
 4. p(y SubClassOf x) = 0
 5. p(x EquivalentTo y) = 0.8
 6. p(Other) = 0.2

We can tweak the priors later. Maybe we believe some sources more than others.

Our focus is on genes, which are never subclasses of each other, so this limits the search space a lot!

## Create ontology input for kboom

For every class x y and above, we need two triples:

 - it's label
 - `a owl:Class`

call this ont.owl

## run kboom

`kboom --experimental  --splitSize 50 --max 5 -m report.md -n -o axioms.owl -t ptable.tsv ont.owl`

**Comment by jmcmurry** [comment]
I don't know if this is related, but https://monarchinitiative.org/HGNC:30579 shows NCBIGene:54434,ENSEMBL:ENSG00000084112,OMIM:606778 as equivalents; however reciprocal relationships are not shown if you go to a non-clique-leader https://monarchinitiative.org/NCBIGene:54434

**Comment by kshefchek** [comment]
This looks like a monarch-app issue - we're only querying direct neighbors.  To get the eq graph for non-clique leaders we need to search across 2 edges.

**Comment by kshefchek** [comment]
this ticket it too vague and potentially unclosable as written, replacing with https://github.com/monarch-initiative/dipper/issues/519
