### ISSUE TITLE
Fanconi Anemia annotation to do

### ISSUE THREAD

**Issue by lwinfree** [monarch-initiative/dipper#523]
As per request from @mellybelly, I checked the review article [Recent insights into the molecular basis of Fanconi anemia: genes, modifiers, and drivers](https://doi.org/10.1007/s12185-017-2283-4) to determine if we have all relevant genes/phenotypes annotated in Monarch. I found 3 issues where we could improve our annotation:

- [ ] **FANCD2 monoubiquitination.** Example from text: "Because the majority of FA patients carry mutations in core complex proteins, FANCI/D2 monoubiquitination is impaired in greater than 90% of FA patients [9, 10]". We have annotations for FANC1/D2 and for monoubiquitination separately, but nothing for how this is related to Fanconi. 

- [ ] **Aldehyde metabolism** with FA is not well annotated. The authors argue that there is some evidence that altered aldehyde metabolism is leading to more interstrand crosslinks (ICL) DNA damage, which is a diagnostic factor in FA patients. We don't have this aldehyde phenotype annotated for FA patients (as far as I could tell). Paper sources 43-51 discuss recent evidence for this link.

- [ ] **TGFBeta in FA not well annotated.** Example from text: "Only recently was transforming growth factor beta (TGFβ) signaling specifically identified as being hyperactive in FA patients [54]" Sources 54-63 discuss recent evidence for this link. We have info about TGFB, but not related to Fanconi.

**Comment by kshefchek** [comment]
should this ticket go in the data-boutique?

**Comment by lwinfree** [comment]
I'm not sure @kshefchek but I trust your judgement - feel free to move wherever you see fit

**Comment by kshefchek** [comment]
moved to https://github.com/monarch-initiative/data-boutique/issues/102
