### ISSUE TITLE
Invalid values for datatype in animalqtldb_dataset.ttl

### ISSUE THREAD

**Issue by yy20716** [monarch-initiative/dipper#525]
Hello, I tried to import animalqtldb_dataset.ttl file (https://data.monarchinitiative.org/ttl/animalqtldb_dataset.ttl) into a graph database such as Blazegraph. However, a number of errors occured as follows and the import process was failed.

> [error] (run-main-0) org.openrdf.rio.RDFParseException: '2017-09-25-09-00' is not a valid value for datatype http://www.w3.org/2001/XMLSchema#dateTime [line 14]
> org.openrdf.rio.RDFParseException: '2017-09-25-09-00' is not a valid value for datatype http://www.w3.org/2001/XMLSchema#dateTime [line 14]

It is possible that the time data type is not correctly expressed, e.g., 2017-09-25-09-00 may need to be represented as 2017-09-25T09:00:00. Could you please check this issue? Thank you.

**Comment by kshefchek** [comment]
thanks for fixing!
