### ISSUE TITLE
MGI Ingest: 

### ISSUE THREAD

**Issue by bryanlaraway** [monarch-initiative/dipper#53]
Need to adjust the MGI ingest of the mrk_summary_view table to handle rows that share the same ID. For example, MirBase may use the same ID (MI0000558) that applies to a microRNA (mirlet7b) and a microRNA cluster containing the same microRNA (Mirc31: microRNA cluster 31, including Mirlet7c-2 through Mirlet7b). The two entries have different MGI IDs, but connect back through the same internal marker ID.

Current implementation would have these read as the same in the turtle output file: 
miRBase:MI0000558 owl:sameAs _:markerkey445750, _:markerkey93138
The same miRBase ID maps to the two different internal marker keys, but instead we need to handle this in some way that the relation is captured (like mirlet7b part_of_cluster mirc31), unless we can handle this once MirBase is ingested?

References #13 .

**Comment by nlwashington** [comment]
i have temporarily suspended including MirBase for the MGI ingest.
