### ISSUE TITLE
DOID:50202 not resolving

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/dipper#531]
https://monarchinitiative.org/disease/DOID:50202

Clicked on this link from an external site, but it does not resolve.

**Comment by kshefchek** [comment]
Is it a valid DO id?

**Comment by kshefchek** [comment]
(closed this by accident) I suspect this is a zero padding issue, the intended page might be https://monarchinitiative.org/disease/DOID:0050202.  We could support this in the resolver but it might be tricky.  Surprisingly it doesn’t show up as the top hit in our search either: https://monarchinitiative.org/search/DOID:50202.  The easiest thing is asking the site to correct their URLs.

**Comment by kshefchek** [comment]
@jmcmurry thoughts on closing or moving this to the monarch-app?  Not much can be done on the dipper side and I don't want it getting lost in the shuffle.

**Comment by jmcmurry** [comment]
Agreed; moving would be great, thanks. Where does the resolver code live?

**Comment by kshefchek** [comment]
It is in the monarch-app, api.js and webapp.js

**Comment by kshefchek** [comment]
Moved to https://github.com/monarch-initiative/monarch-app/issues/1502
