### ISSUE TITLE
Malformed triples in clinvar_dataset.ttl

### ISSUE THREAD

**Issue by yy20716** [monarch-initiative/dipper#539]
I was trying to import all turtle files in [this repository](https://data.monarchinitiative.org/ttl) into Blazegraph database. I was able to import all files, except clinvar_dataset.ttl. This file contained some malformed nodes, e.g., 

> \<monarch2017-02-23\> dct:isVersionOf \<:ClinVar2017-02-23\> ;
>     dct:issued "2017-02-23"^^xsd:dateTime ;
>     pav:version "2017-02-23" .

where ":monarch2017-02-23" and ":ClinVar2017-02-23" are the ones that cause errors. My guess was that these nodes are generated by dipper/models/Dataset.py, so I wanted to briefly check this file. 

I first tried to run Dipper and wanted to check how the data was generated. However, when I launched the Dipper on my laptop, it was not working because the option "clinvar" was commented in dipper-etl.py. 
I guessed this was commented because it would take too much time to pull the data. For a testing purpose, I removed the comment so that I can run it as follows.

> yy20716@M3800:~/Workspace/dipper$ ./dipper-etl.py -s clinvar

However, I was stuck again because of these errors:

> Traceback (most recent call last):
>   File "/home/yy20716/Workspace/dipper/tests/test_source.py", line 33, in test_parse
>     self.source.parse()
>   File "/home/yy20716/Workspace/dipper/dipper/sources/ClinVar.py", line 115, in parse
>     self._get_variants(limit)
>   File "/home/yy20716/Workspace/dipper/dipper/sources/ClinVar.py", line 208, in _get_variants
>     ChromosomeAccession) = line.split('\t')
> ValueError: too many values to unpack (expected 29)

It seems that the number of the fields in this data becomes not 29 but 30. I stopped at this point because I was not sure why this error was produced (maybe the data is simply updated?). If this is not the correct way of running Dipper or there are any other ways that I can test generating clinvar_dataset.ttl, please let me know. Thank you.

**Comment by TomConlin** [comment]
ClinVar ingest generates [ntriples](https://data.monarchinitiative.org/ttl/clinvarxml_alpha.nt
) which can be turned into turtle by 
https://github.com/monarch-initiative/dipper/blob/master/scripts/add-properties2turtle.py
and decorated with those problematic triples.  

If the ntriples are sufficient for your use I would just use them till 
add-properties2turtle.py  bugs gets addressed

**Comment by kshefchek** [comment]
We need to retire or delete the ClinVar.py parser (tsv), it hasn't been maintained and was replaced by the xml parser.

I also think this _dataset file is from the old parser, I've removed it from the ttl folder.
