### ISSUE TITLE
Incorrect gene association for OMIM ID; need a better clique merge strategy

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/dipper#540]
https://monarchinitiative.org/disease/OMIM:256300#genes

The gene should be NPHS1
https://omim.org/entry/602716

**Comment by cmungall** [comment]
OK, let's explore the OMIM gene ID:

curl -X GET "https://scigraph-data.monarchinitiative.org/scigraph/graph/neighbors?id=OMIM%3A602716&depth=1&blankNodes=false&direction=BOTH&entail=false" -H  "accept: application/json"

two equivalence edges:

```
"edges": [
    {
      "sub": "OMIM:602716",
      "obj": "NCBIGene:107985317",
      "pred": "equivalentClass",
      "meta": {
        "isDefinedBy": [
          "https://data.monarchinitiative.org/ttl/omim.ttl",
          "https://data.monarchinitiative.org/ttl/ncbigene.ttl"
        ],
        "lbl": [
          "equivalentClass"
        ],
        "equivalentOriginalNodeTarget": [
          "http://www.ncbi.nlm.nih.gov/gene/4868"
        ]
      }
    },
    {
      "sub": "OMIM:602716",
      "obj": "NCBIGene:107985317",
      "pred": "equivalentClass",
      "meta": {
        "isDefinedBy": [
          "https://data.monarchinitiative.org/ttl/orphanet.ttl"
        ],
        "lbl": [
          "equivalentClass"
        ],
        "equivalentOriginalNodeTarget": [
          "http://www.orpha.net/ORDO/Orphanet_123889"
        ]
      }
    }
  ],
```

the one in ncbit/omim ttl is correct

the orphanet one is not right.

It doesn't appear to be there in current ordo:

https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http://www.orpha.net/ORDO/Orphanet_123889

an error in a previous version?

**Comment by cmungall** [comment]
curl -X GET "https://scigraph-data.monarchinitiative.org/scigraph/graph/neighbors?id=Orphanet%3A123889&depth=1&blankNodes=false&direction=BOTH&entail=false" -H  "accept: application/json"

```
"edges": [
    {
      "sub": "NCBIGene:107985317",
      "obj": "Orphanet:123889",
      "pred": "equivalentClass",
      "meta": {
        "equivalentOriginalNodeSource": [
          "http://identifiers.org/ensembl/ENSG00000161270"
        ],
        "isDefinedBy": [
          "https://data.monarchinitiative.org/ttl/orphanet.ttl"
        ],
        "lbl": [
          "equivalentClass"
        ]
      }
    }
  ],
```

this ensembl gene is NPHS1: http://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000161270;r=19:35825964-35869287

**Comment by cmungall** [comment]
aha!

curl -X GET "https://scigraph-data.monarchinitiative.org/scigraph/graph/neighbors?id=ENSEMBL%3AENSG00000161270&depth=1&blankNodes=false&direction=BOTH&entail=false" -H  "accept: application/json"

it's actually ncbigene.ttl that is at fault:

```
"edges": [
    {
      "sub": "ENSEMBL:ENSG00000161270",
      "obj": "NCBIGene:107985317",
      "pred": "equivalentClass",
      "meta": {
        "isDefinedBy": [
          "https://data.monarchinitiative.org/ttl/ncbigene.ttl"
        ],
        "lbl": [
          "equivalentClass"
        ]
      }
    }
  ],
```

**Comment by cmungall** [comment]
...and there we see it:

https://www.ncbi.nlm.nih.gov/gene?Db=gene&Cmd=DetailsSearch&Term=107985317

See related
Ensembl:ENSG00000161270

**Comment by cmungall** [comment]
To summarize

this chain is incorrect:

```
https://omim.org/entry/602716 -> Orphanet:123889 [orpha]
Orphanet:123889 -> Ensembl:ENSG00000161270 [orpha]
Ensembl:ENSG00000161270 -> NCBIGene:107985317 [ncbi]
```

this chain is correct

```
https://omim.org/entry/602716 -> NCBIGene: 4868 [omim]
```

having both together results in two disyinct NCBIGenes being merged. unfortunately the LOC one has it's label chosen as default: https://monarchinitiative.org/gene/NCBIGene:107985317

we need some reporting when we collapse entities in the same source. We also need a more sophisticated clique merge algorithm that will prioritize e.g. shorter paths

**Comment by TomConlin** [comment]
trusting bottom up aproaches I wpuld have started with:
```
tomc@monarch-data-load:~$ grep 'LOC107985317'  Devl/NTriples_201709/ntriples/*.nt
Devl/NTriples_201709/ntriples/kegg.nt:<http://www.kegg.jp/dbget-bin/www_bget?hsa:107985317> <http://www.w3.org/2000/01/rdf-schema#label> "no KO assigned | (RefSeq) uncharacterized LOC107985317" .
Devl/NTriples_201709/ntriples/kegg.nt:<http://www.kegg.jp/dbget-bin/www_bget?hsa:107985317> <http://www.geneontology.org/formats/oboInOwl#hasExactSynonym> "no KO assigned | (RefSeq) uncharacterized LOC107985317" .
Devl/NTriples_201709/ntriples/ncbigene.nt:<http://www.ncbi.nlm.nih.gov/gene/107985317> <http://www.w3.org/2000/01/rdf-schema#label> "LOC107985317" .
Devl/NTriples_201709/ntriples/ncbigene.nt:<http://www.ncbi.nlm.nih.gov/gene/107985317> <http://purl.org/dc/elements/1.1/description> "uncharacterized LOC107985317" .

```

(which is exactly what the new `rdf.monarch`  blazegraph  will facilitate)  

and looked to what could be done to remodel of filter those triples. 

But it is the data we get, so changing how we choose to interpret  via clique leaders is best

**Comment by cmungall** [comment]
yep - I actually started by sparqling individual ttls, but realized it was a global problem from the combo.

Yes, this will be easier when we have the triplestore (thanks @yy20716 !). Although of course there is nothing inherent about cypher that means it can't be done, it's just harder because we don't keep around a copy of the pre-merged graph (it can be figured out from the OriginalSource properties though.

**Comment by kshefchek** [comment]
I've made some adjustments to our manual xref vs eq strategy for human genes.  It made a modest improvement, we are down to 95 genes incorrectly merged into 47 cliques.  The NPHS1 issue mentioned here is fixed.
