### ISSUE TITLE
Complete data modeling for Elements of Morphology

### ISSUE THREAD

**Issue by bryanlaraway** [monarch-initiative/dipper#55]
I've started ingestion of Elements of Morphology ( references #41 ) and need some assistance with the data modeling. I have started drafting a concept map for EOM, which I have placed in the DropBox folder (LAMHDI-Project/Data modeling/Dipper Concept Maps/EOM.cmap). I have recreated some of the basics we have mapped in the [eom-map.yaml](https://github.com/monarch-initiative/monarch-app/blob/master/conf/rdf-mapping/eom-map.yaml) file, but I need a review of the designations and relations. 

I have connected most of the relevant variables, but I imagine at least five additional variables may be useful (terminology_category_label, terminology_category_url, subcategory, comments, replaces). Of course, the first three I have listed may not be needed as I will also be ingesting the mapping of the morphology_term_ids to HP IDs with the mapping file that Nicole V and Ariel B created in August.

**Comment by nlwashington** [comment]
we don't want the upper-level categories, i don't think.

**Comment by bryanlaraway** [comment]
@mbrush @nlwashington I have updated the concept map for this resource and believe I have everything mapped correctly, but it needs review. The latest ttl output file is also in the DropBox.

Two key questions I need answered:
-Is the Monarch_phenotype the correct subclass for morphology terms, or do we want GENO:0000348 - phenotype?
-Is the foaf:page the correct predicate for a link to a web page (morphology_term_id, foaf:page, morphology_term_url)?

**Comment by nlwashington** [comment]
@cmungall or @mbrush are there properties for definitions?  EOM has two categories of definitions:  "subjective" which is more descriptive and "objective" which are often measurement based.  Not all terms have both, but some do.  I don't see any appropriate things in IAO to use.  (We are currently placing some additional text into the definition itself to say what kind it is, but I don't like that solution long term.)

For example:
http://elementsofmorphology.nih.gov/index.cgi?tid=03f02219fe5521b4

**Comment by cmungall** [comment]
We use IAO_0000115 but how would we use these? The HP definition should be primary

**Comment by nlwashington** [comment]
Yes, of course. I would just add them to the EOM term, but not to HP.

**Comment by mbrush** [comment]
@nlwashington I think you presently have split the subjective and objective definitions into separate IAO:0000115 annotations on an eom class. It is considered poor form to have more than one definition for a term, so I would suggest merging into one IAO:0000115 annotation.

@bryanlaraway Don't use the GENO:phenotype class for anything.  It was just a placeholder from way back when.  Apologies, but there are many of these that I need to clean up in a refactoring session. Not entirely sure what the MONARCH:phenotype class is, but it looks like Nicole's latest version of the ttil file does not create a link to a phenotype class anyway. I would assume this is because the equivalence mapping to HP IRIs will allow inferred classification as a human phenotype.

**Comment by nlwashington** [comment]
yes, i got rid of any hierarchical classification of EOM - we aren't building an ontology here, just making the equivalences. (and yes, @bryanlaraway, i'm removing that from any data ingests that i see it in...we generally aren't putting things in with superclasses except for genes.)

@mbrush bryan originally had it combined, but then i've split it out.  i wonder if we might suggest some kind of subclasses of IAO:0000115 that would permit us to have two different definitions? (that combined make up the full definition.)?  happy to combine it again, but am kinda hating on including the "subjective" or "objective" phrasing in the text of the definition.

**Comment by nlwashington** [comment]
i've merged the two definitions into a single one.  i have opted to remove the "subjective" and "objective" tags.

**Comment by nlwashington** [comment]
this is nearly finished.  awaiting https://github.com/SciCrunch/SciGraph/issues/94 for final testing.
