### ISSUE TITLE
Add Source: SGD

### ISSUE THREAD

**Issue by mbrush** [monarch-initiative/dipper#550]
**Source Name:**  Saccharomyces Genome Database, https://www.yeastgenome.org/
  
**Source Data Description:**  MOD for yeast. "The Saccharomyces Genome Database (SGD) provides comprehensive integrated biological information for the budding yeast Saccharomyces cerevisiae along with search and analysis tools to explore these data, enabling the discovery of functional relationships between sequence and gene products in fungi and higher organisms."
  
**Scope of Ingest:** Only gene/locus-to-phenotype associations for first pass.
   
**Source Data Location:**  https://downloads.yeastgenome.org/curation/literature/phenotype_data.tab
   
**Source Documentation:**   https://downloads.yeastgenome.org/curation/literature/phenotype_data.README
     
**Additional Notes:**
    Data dumps lack identifiers for many key entities (alleles, genomic backgrounds) - need to follow up with SGD to see if they have or could provide ids for these.  Also, phenotypes are post-composed from APO terms.  We should collaborate to implement a pipeline similar to ZFIN for generating pre-composed phenotype ontology terms. 

Additional Ingest and QA Notes here:  https://downloads.yeastgenome.org/curation/literature/phenotype_data.README

cmap of target model for ingest is here:  https://github.com/monarch-initiative/ingest-artifacts/tree/master/sources/SGD

**Comment by kshefchek** [comment]
https://github.com/monarch-initiative/dipper/pull/552
