### ISSUE TITLE
GENO URI oddities in rdf store

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/dipper#554]
http://rdf.monarchinitiative.org/sparql/

```
SELECT * WHERE {
  ?x rdfs:label "C57BL/6J (f)" ;
      ?r ?p
}
```

it looks like some GENO CURIEs are not expanded, e.g.

```
<https://monarchinitiative.org/.well-known/genid/MPD-strain7-f-genotype>	GENO:0000650	<https://monarchinitiative.org/.well-known/genid/MPD-strain7-genotype>
<https://monarchinitiative.org/.well-known/genid/MPD-strain7-f-genotype>	rdf:type	GENO:0000647
<https://monarchinitiative.org/.well-known/genid/MPD-strain7-f-genotype>	rdfs:label	C57BL/6J (f)
```

the latest mpd.ttl seems ok to me though, not sure if this is a blazegraph load issue cc @yy20716 or in the dipper export

**Comment by yy20716** [comment]
I think it is the dipper issue because that curie is not expanded in mpd.ttl file but represented as literal, i.e. each line looks like this:

> <https://monarchinitiative.org/.well-known/genid/MPD-strain7-f-genotype> a OBO:GENO_0000647 ;

**Comment by kshefchek** [comment]
All looks fine to me on the dipper side, the OBO:GENO_ is just a rdflib quirk, see https://github.com/RDFLib/rdflib/issues/632.

**Comment by yy20716** [comment]
I am sorry if you saw my previous comment. I ran that query again and checked the result. The blazegraph properly expanded the curie in the result as well.
