### ISSUE TITLE
Investigate loss of variant phenotype data from flybase

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/dipper#561]
Theres a drop in variant data in the latest ingest of flybase:
https://archive.monarchinitiative.org/201801/ttl/flybase.nt

Edges (only indexed edges, all sources):
is_expression_variant_of: 168690 (-26389)

Variant Phenotype
Drosophila melanogaster:  0 (-50360)

Gene Phenotype
Drosophila melanogaster: 189374 (-26184)

In the meantime I have reverted flybase back to our December ingest.

**Comment by matentzn** [comment]
There was a new major FB release on Dec 31, but it was mainly frontend, @dosumis believes the schema should not have changed, but, it could have. We will poke them and come back to you.

**Comment by kshefchek** [comment]
There have been no changes to the script, but in the latest load:

Edges (only indexed edges, all sources):
is_expression_variant_of: 187220 (-7955)

Variant Phenotype
Drosophila melanogaster: 47021 (-3339)

Gene Phenotype
Drosophila melanogaster: 217731 (+2186)

Will still revert back to the old file until this is fixed, but interesting that a chunk of it came back.  Diff files:
https://data.monarchinitiative.org/qc/data-diff-201804090219/relations/is_expression_variant_of.tsv
https://data.monarchinitiative.org/qc/data-diff-201804090219/variant_phenotype_associations/drosophila_melanogaster.tsv

**Comment by kshefchek** [comment]
Fixed with https://github.com/monarch-initiative/dipper/pull/760
