### ISSUE TITLE
Parse sex-specific phenotypes in dipper

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/dipper#583]
@pnrobinson is implementing a parser for MGI_Pheno_Sex.rpt from http://www.informatics.jax.org/downloads/reports/index.html

URL: http://www.informatics.jax.org/downloads/reports/MGI_Pheno_Sex.rpt

Should we re-use this? File seems fairly trivial to perhaps two parsers and coordinate on modeling?

Shall we have dipper follow the biolink model?

We already have a qualifier for sex:

https://biolink.github.io/biolink-model/docs/GenotypeToPhenotypicFeatureAssociation.html
https://biolink.github.io/biolink-model/docs/sex_qualifier.html

@mbrush can you quickly review? I assume me map M/F to http://purl.obolibrary.org/obo/PATO_0001894 subclasses?

**Comment by cmungall** [comment]
Example row:

```
         Genotype ID: MGI:2167486
                 Sex: M
               MP ID: MP:0001147
             MP Term: small testis
 Allelic Composition: Kit<W-42J>/Kit<+>
   Background Strain: C57BL/6J-Kit<W-42J>/J
Sex-specific Normal Y/N: N
```

We have this already without an explicit sex qualifier (tho this can obv be inferred for this phenotype)
https://monarchinitiative.org/genotype/MGI:2167486#phenotypes

**Comment by TomConlin** [comment]
other qualifiers I have come across recently include  

 - Sex unspecified
 - Sex ambiguous
 - Mixed sex

**Comment by pnrobinson** [comment]
Our goal is to have a parser that will ingest the main MGI file, the sex-specific file, and the IMPC data to create an overall view of phenotype and sex specificity. So we would like to create one ingest tool in phenol that would just work with the main MGI data (this is the main use case) and have a second option that would allow use to combine this with the additional files.
Here is an issue (that needs to be tofu'd out)
https://github.com/monarch-initiative/phenol/issues/78

**Comment by TomConlin** [comment]
related: https://github.com/monarch-initiative/phenol/issues/94

**Comment by kshefchek** [comment]
Added with #595, #602
