### ISSUE TITLE
refactor synonyms in various sources

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#59]
For genes in NCBIGene, and any other source that we add synonyms, we should follow the more-standardized synonym model as outlined here:
https://github.com/obophenotype/uberon/wiki/Using-uberon-for-text-mining

we should consider adding synonym as it's own python class to standardize this.

**Comment by kshefchek** [comment]
We are using hasRelatedSynonym for gene synonyms in NCBI gene.  Model.addSynonym allows for implementing the uberon model.
