### ISSUE TITLE
Use ClinVar curated gene to disease file for G2P associations

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/dipper#593]
ClinVar provides a curated gene to disease file here:
ftp://ftp.ncbi.nlm.nih.gov/pub/clinvar/gene_condition_source_id

This will help resolve cases where a variant affects more than one gene, where one or more genes should not be propagated to the disease:
https://www.ncbi.nlm.nih.gov/clinvar/docs/faq/#manygenes

Example issues with the current implementation
MIR3606 incorrectly associated with EDS type 4: https://monarchinitiative.org/disease/MONDO:0007524#genes
https://github.com/monarch-initiative/monarch-app/issues/1591

We could use this file to infer that a variant should be associated with a gene via the has_affected_feature relation versus has_reference_part, although perhaps this is a modelling hack (@mbrush can you advise?).  Alternatively, we could use this file to link genes and diseases directly, and adjust our gene to disease inferences through variants.

Ideally we would have a source of variant to gene associations so we would not need to make this inference.  We should explore if such a source is available.

**Comment by pnrobinson** [comment]
Interesting! 
Does anyone know what the relation is to OMIM-based resources? It looks like the ClinVar resource has more, but is it a strict superset of mim2gene_medgen?

**Comment by kshefchek** [comment]
The last time I looked into it there were conflicts between OMIM and ClinVar, see https://github.com/monarch-initiative/monarch-cypher-queries/issues/23#issuecomment-345119000

**Comment by kshefchek** [comment]
Added with #602

**Comment by kshefchek** [comment]
This isn't quite fixed - see https://monarchinitiative.org/disease/MONDO:0007947#gene-other

**Comment by kshefchek** [comment]
fixed with https://github.com/monarch-initiative/dipper/pull/729
