### ISSUE TITLE
Namespace models, sources, and utils packages

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/dipper#60]
Since we may reuse our dipper packages elsewhere (mckb, phenologs), it may make sense to namespace these packages under dipper.  This way we can build the project with setup.py (or pip3), which is a bit easier than updating the python path, or manually moving the directory into a lib dir.

With python3, we just need to move everything into directory named dipper.  This is redundant since everything is already housed in a dipper directory, but it appears the setup.py needs to be placed in the parent directory of dipper to make this work (see https://github.com/RDFLib/rdflib/tree/master/rdflib as an example).

We should wait to do this when we pause development (branches merged, etc.) to avoid conflicts.

**Comment by kshefchek** [comment]
This is finished, @nlwashington @bryanlaraway are we at a place where you guys can stash any changes, or have all changes been committed?  This will likely be hard to merge.

**Comment by nlwashington** [comment]
i'll be committing a few changes shortly.

**Comment by kshefchek** [comment]
Okay I will hold off for now.  Your last few commits merged with few conflicts suprisingly.
Here is a summary of the changes:
1. Everything except the main launcher has been moved into a package called dipper
2. raw and out directories need to be moved here as well for now.  conf, tests, and docs should live in the parent directory.
3. I refactored curie_map.py and the yaml file into their own package since these are needed to most (all?) of the models classes.  I also updated this so the yaml file is opened relative to the curie_map.py so this will work when loaded as an external library or when launching unit tests.
4.  All imports have the format "from dipper.package.module import class".

**Comment by kshefchek** [comment]
I've updated the structure slightly - config and curie_map are now modules in the dipper package.  So the conf file will also live in the dipper package directory.  This is the same structure we started with minus having an official dipper package.
