### ISSUE TITLE
Test that we can generate ternary relationships between drugs and phenotypes

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/dipper#61]
We need to test, either at the RDF graph level (sparql) or neo4j (cypher) that we can generate relationships between a drug and phenotype given the triples:
drug -> relationship -> disease
disease -> relationship -> phenotype

Tasks for dipper testing:
- update test utils to import turtle from multiple sources
- generate official test? Not sure if needed but can be done

**Comment by mbrush** [comment]
Not sure I see a ternary relationship here?  The triples you show above  capture binary relationships.  What would the three participants be in a ternary relationship here?  And what is the 'sentence' that describes this relationship.  For example, with the G-P-E ternary relation, we say something like "genotype G causes phenotype P in environment E".

**Comment by kshefchek** [comment]
Maybe my terminology is off, this is the query:
?drug (:MONARCH_treats|:MONARCH_causes) ?dis . ?dis OBO:RO_0002200 ?phenotype

**Comment by kshefchek** [comment]
This is the output for this command:
dipper.py --sources ctd,hpoa --query 'SELECT * WHERE { ?drug (:MONARCH_treats|:MONARCH_causes) ?dis . ?dis OBO:RO_0002200 ?phenotype }'

http://purl.obolibrary.org/obo/MESH_C066024, http://purl.obolibrary.org/obo/OMIM_146850, http://purl.obolibrary.org/obo/HP_0002715
http://purl.obolibrary.org/obo/MESH_C037913, http://purl.obolibrary.org/obo/OMIM_146850, http://purl.obolibrary.org/obo/HP_0002715
http://purl.obolibrary.org/obo/MESH_D014810, http://purl.obolibrary.org/obo/OMIM_146850, http://purl.obolibrary.org/obo/HP_0002715
http://purl.obolibrary.org/obo/MESH_D028321, http://purl.obolibrary.org/obo/OMIM_146850, http://purl.obolibrary.org/obo/HP_0002715
http://purl.obolibrary.org/obo/MESH_D001205, http://purl.obolibrary.org/obo/OMIM_146850, http://purl.obolibrary.org/obo/HP_0002715
http://purl.obolibrary.org/obo/MESH_D010972, http://purl.obolibrary.org/obo/OMIM_146850, http://purl.obolibrary.org/obo/HP_0002715
http://purl.obolibrary.org/obo/MESH_C098607, http://purl.obolibrary.org/obo/OMIM_146850, http://purl.obolibrary.org/obo/HP_0002715
http://purl.obolibrary.org/obo/MESH_D008627, http://purl.obolibrary.org/obo/OMIM_146850, http://purl.obolibrary.org/obo/HP_0002715
http://purl.obolibrary.org/obo/MESH_C029662, http://purl.obolibrary.org/obo/OMIM_146850, http://purl.obolibrary.org/obo/HP_0002715
http://purl.obolibrary.org/obo/MESH_D016572, http://purl.obolibrary.org/obo/OMIM_146850, http://purl.obolibrary.org/obo/HP_0002715
http://purl.obolibrary.org/obo/MESH_D002117, http://purl.obolibrary.org/obo/OMIM_109730, http://purl.obolibrary.org/obo/HP_0001647
http://purl.obolibrary.org/obo/MESH_D002117, http://purl.obolibrary.org/obo/OMIM_109730, http://purl.obolibrary.org/obo/HP_0001650
http://purl.obolibrary.org/obo/MESH_D003520, http://purl.obolibrary.org/obo/OMIM_102530, http://purl.obolibrary.org/obo/HP_0012205
http://purl.obolibrary.org/obo/MESH_D003520, http://purl.obolibrary.org/obo/OMIM_102530, http://purl.obolibrary.org/obo/HP_0000789

As you can see where not getting a ton of results.  I think the issue is that the majority of the CTD annotations are made to MESH as opposed to OMIM, and most (all?) of the HPO annotations are to OMIM.  So this should be fixed upstream when we add the MESH->OMIM equivalence mappings.

**Comment by kshefchek** [comment]
Also the MESH and OMIM URI's are not resolving, is this expected?

**Comment by mbrush** [comment]
HI Kent.  I see now.  Yes, this is not what we would call a ternary relation.  You are just querying across two links in the graph (from drug to disease, and then disease to phenotype).  It is true that three objects are returned (drug, disease, phenotype), but the relationship between them is not ternary.  Its just a join of two binary relationships across a disease node.

One thing to note about SPARQL is that if you dont use an optional command, the query terminates when it encounters a missing value.  So if there is a drug related to a disease that has no phenotypes, the drug and disease are not returned (and it is possible that the query terminates at this point as well - not sure here)  Try to add OPTIONAL qualifier on the disease to phenotype clause and see what happens, e.g. 

     OPTIONAL {?dis OBO:RO_0002200 ?phenotype}.

See what you get, and this should tell you how sparql handles missing values if no OPTIONAL qualifier is stated (does it just not show the result, or does it terminate the query).

**Comment by kshefchek** [comment]
I tried this:
SELECT ?drug ?dis ?phenotype WHERE { ?drug (:MONARCH_treats|:MONARCH_causes) ?dis . OPTIONAL {?dis OBO:RO_0002200 ?phenotype} }

And got back 86892 rows that contained a null, and 14 rows without nulls, so I think the above is behaving as expected
