### ISSUE TITLE
add taxon flags to panther, ncbigene, biogrid, ucscbands

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#63]
Panther, NCBIGene, BioGrid all have a hard-coded filter on taxon.  this should be a command-line parameter passed specific for these sources.

I think other sources might need their own source-specific filters, which can be documented, but these should all have a taxon filter.

Can you add command line options for taxon constraints for these sources?  And, perhaps a default taxon if none are specified?  (like, default to human if none are specified?)

We will also want this configurability for ucsc as well, though at the moment we currently only support human as an option.

For example, if we wanted to run NCBIGene filtering for human & mouse, it would be:

dipper.py --sources ncbigene --filter tax 9606,10090

where the filter has a filter-type followed by possible values.

**Comment by nlwashington** [comment]
help functions would show the user the allowable filters per source

**Comment by kshefchek** [comment]
Added for panther, ncbigene, biogrid.  UCSCBands looks to be a little different.  Should this only handle 1 taxon and throw an error if two are passed as command line options?

**Comment by nlwashington** [comment]
eventually UCSC will handle additional taxa; only human 9606 is currently configured.
