### ISSUE TITLE
refactor dictionary lookups

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#66]
we've got lots of repeated code of how to map source-specific dictionaries to identifiers.

need to refactor the mapping method into some util, and then just pass it a source-defined dictionary.  then all dictionaries for each class can be declared closer to the top of the class, and get rid of redundant code.  the default is an optional parameter that the user can set to be the default class to map to.

def map_to_id(dict, term, default=None)

**Comment by kshefchek** [comment]
Fixed with @TomConlin's translation table refactor, https://github.com/monarch-initiative/dipper/pull/609 amongst others
