### ISSUE TITLE
Replace ECO FIXMEs with IDs

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/dipper#662]
https://github.com/monarch-initiative/dipper/blob/faee349fdaa2d8479e9d6a6147698b7a4b9e3d4f/dipper/sources/HPOAnnotations.py#L74-L83

 1. [ ] @nicolevasilevsky will request terms for each of these codes from ECO
 2. [ ] Fix FIXME and replace placeholder ECO ID with new one in HPOAnnotations code

**Comment by nicolevasilevsky** [comment]
Not sure I understand the request.

- IEA "ECO:0000501" is 'evidence used in automatic assertion'
- ECO_0000269 is 'experimental evidence used in manual assertion'
- ECO:0000304  is 'author statement supported by traceable reference used in manual assertion'
- ECO_0000053 is 'computational combinatorial evidence'

Where is the HPOAnnotations code?

**Comment by cmungall** [comment]
the quoted codes, ITM, PCS, ICE.

**Comment by nicolevasilevsky** [comment]
I think the IDs are wrong
PCS = ECO_0006017 author statement from published clinical study used in manual assertion
ICE= ECO_0006019 inference based on individual clinical experience used in manual assertion

ITM is not in ECO, is this still a proper code?
Should I request that ECO create a code for this abbreviation? What is it intended to mean?

(sorry, still a bit confused)

**Comment by TomConlin** [comment]
Hi Nicole hoping to provide records for context of where these codes are being used   


`ICE` is used in the context of (only) these rows:
```
OMIM	103300	HYPOGLOSSIA-HYPODACTYLIA		HP:0000190	OMIM:103300	ICE				OHPO:skoehler[2009-09-17]	
OMIM	105830	ANGELMAN SYNDROME		HP:0002136	OMIM:105830	ICE		HP:0040281		OHPO:iea[2009-02-17]	HP:0040281
OMIM	105830	ANGELMAN SYNDROME		HP:0002312	OMIM:105830	ICE		HP:0040281		OHPO:iea[2009-02-17]	HP:0040281
OMIM	105830	ANGELMAN SYNDROME		HP:0003745	OMIM:105830	ICE		HP:0040282		IHPO:iea[2009-02-17]	HP:0040282
OMIM	115150	CARDIOFACIOCUTANEOUS SYNDROME 1		HP:0000006	OMIM:115150	ICE				IHPO:iea[2009-10-09]	
OMIM	115150	CARDIOFACIOCUTANEOUS SYNDROME 1		HP:0003577	OMIM:115150	ICE				CHPO:iea[2009-10-09]	
OMIM	168885	PAROXYSMAL TONIC UPGAZE, BENIGN CHILDHOOD, WITH ATAXIA		HP:0002131	OMIM:168885	ICE	OHPO:skoehler[2009-09-17]	
OMIM	256000	LEIGH SYNDROME		HP:0000407	OMIM:256000	ICE				O		HPO:iea[2009-08-31]	
OMIM	301835	#301835 ARTS SYNDROME; ARTS;;MENTAL RETARDATION, X-LINKED, SYNDROMIC, ARTS TYPE; MRXSARTS;;ATAXIA, FATAL X-LINKED, WITH DEAFNESS AND LOSS OF VISION;;MENTAL RETARDATION, X-LINKED, SYNDROMIC 18; MRXS18		HP:0002719	OMIM:301835	ICE				O		HPO:skoehler[2009-09-17]	
OMIM	301845	BAZEX SYNDROME		HP:0001047	OMIM:301845	ICE				O		HPO:sdoelken[2009-07-31]	

```

`PCS` is used in  5,224 rows,    a random sample of 10 of them are:  
 
```
OMIM	300422	#300422 FG SYNDROME 4; FGS4MENTAL RETARDATION, X-LINKED, WITH OR WITHOUT NYSTAGMUS, INCLUDED		HP:0001250	PMID:19200522	PCS		HP:0040284		O		HPO:probinson[2013-02-17]	5/8
OMIM	612301	#612301 OSTEOPETROSIS, AUTOSOMAL RECESSIVE 7; OPTB7;;OSTEOPETROSIS, OSTEOCLAST-POOR, WITH HYPOGAMMAGLOBULINEMIA		HP:0006532	PMID:18606301	PCS				O		HPO:probinson[2013-04-04]	
OMIM	201000	#201000 CARPENTER SYNDROME 1; CRPT1;;CARPENTER SYNDROME;;ACROCEPHALOPOLYSYNDACTYLY TYPE II;;ACPS II	HP:0002970	ISBN-13:978-0721606156	PCS				O		HPO:iea[2012-02-25]	
OMIM	266265	CONGENITAL DISORDER OF GLYCOSYLATION, TYPE IIC		HP:0010529	PMID:24403049	PCS		HP:0040284		O		HPO:lccarmody[2017-06-21]	1/2
OMIM	612577	AMYOTROPHIC LATERAL SCLEROSIS 11		HP:0000006	PMID:19118816	PCS			IHPO:probinson[2013-01-09]	
OMIM	612390	#612390 PONTOCEREBELLAR HYPOPLASIA, TYPE 2C; PCH2C		HP:0000007	PMID:18711368	PCS	IHPO:probinson[2013-04-14]	
OMIM	613820	NEPHRONOPHTHISIS 12		HP:0000090	PMID:21258341	PCS				O	HPO:probinson[2013-08-10]	
OMIM	129500	#129500 CLOUSTON SYNDROME;;ECTODERMAL DYSPLASIA 2, CLOUSTON TYPE; ECTD2;;ECTODERMAL DYSPLASIA, HIDROTIC, AUTOSOMAL DOMINANT;;CLOUSTON HIDROTIC ECTODERMAL DYSPLASIA;;ECTODERMAL DYSPLASIA, HIDROTIC, 2, FORMERLY; HED2, FORMERLYHP:0002164	OMIM:129500	PCS				O		HPO:iea[2009-02-17]	
OMIM	610017	MULTIPLE SYNOSTOSES SYNDROME 2		HP:0000006	PMID:16532400	PCS				IHPO:probinson[2013-03-31]	
OMIM	162200	NEUROFIBROMATOSIS, TYPE I		HP:0007565	PMID:10204844	PCS		HP:0040284	OHPO:iea[2018-03-13]	383/442
OMIM	606640	AMYOTROPHIC LATERAL SCLEROSIS 3		HP:0000006	PMID:11706389	PCS				IHPO:probinson[2017-06-25]	
```

`ITM` does _not_ occur in the current ingest.

Perhaps this will let you choose better terms for the codes

**Comment by nicolevasilevsky** [comment]
Ah, thanks @TomConlin.
I know we use PCS a lot in the HPO annotations, and I think it makes sense to use this code.

I think ICE was used previously, and from what I understand, we are trying to get away from it. Should I update those records that use the ICE code?

Should we not worry about ITM for now?

**Comment by nicolevasilevsky** [comment]
I can update the records with ICE.
Yes, the diseases annotated to PCS look fine.

**Comment by pnrobinson** [comment]
The HPO has stopped using ICE altogether. ITM is also no longer used. At least for now, the HPO only has PCS, IEA, and TAS. 
If you are finding records with ITM or ICE, then something is wrong, please let's look into it!

**Comment by nicolevasilevsky** [comment]
My guess it is it is just legacy data. I was going to review these records and update the annotations (if needed) and add references and the code PCS - does that sound okay, @pnrobinson?

**Comment by pnrobinson** [comment]
Could we please put these annotations on the tracker -- PCS requires a PubMed id to support the statement, and the ICEs are "individual clinical experience", which on hindsight was probably never a good idea. I was pretty sure I had reannotated all of the ICEs about 9 months ago and am surprised there are any left--are you sure you have the very latest version of the annotations?

**Comment by TomConlin** [comment]
data is pulled from   
    http://compbio.charite.de/hudson/job/hpo.annotations/lastStableBuild/artifact/misc//phenotype_annotation.tab

**Comment by kshefchek** [comment]
fixed with https://github.com/monarch-initiative/dipper/pull/671
