### ISSUE TITLE
Remove text-mined biolark annotations to non-common diseases

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/dipper#663]
The text-mined biolark annotations are causing some issues: #661 

We could remove these altogether, but then we end having no annotations for common diseases.

Instead we can remove annotations to diseases that we would otherwise have higher-quality annotations for coming from the monogenic/HPOA pipeline.

We can do a one-time filter of the biolark annotations (these are static). We could do this in the hpoa annotations directory or move to mondo

**Comment by cmungall** [comment]
OK, a simpler approach. When this is merged, load common-disease-mondo rather than common-disease:

https://github.com/monarch-initiative/hpo-annotation-data/pull/235

**Comment by TomConlin** [comment]
text-mined biolark annotations have been removed from HPO ingest
