### ISSUE TITLE
Add category for entities exported by dipper

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/dipper#669]
Currently add entities have a direct rdf:type or rdfs:subClassOf (depending on whether they are modeled as a class or instance).

It would be useful to have an additional triple describing the high level category, so that consumers of the file do not have to walk equivalence and subClassOf graphs to find out broadly what type of entity.

**Comment by TomConlin** [comment]
I there a Biolink data file which maps the types dipper has to categories we want to tag them with for a data driven approach. 
That is,  can the information to be shared not be buried in code.

**Comment by cmungall** [comment]
All in the bl yaml, recommend using the py module, can provide more deets later

**Comment by kshefchek** [comment]
replaced with https://github.com/monarch-initiative/dipper/issues/745
