### ISSUE TITLE
add orphadata pipeline

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#67]
We need to bring in some of the orphanet data in from http://www.orphadata.org/data/xml/ :

the data we leveraged before included:
en_product1.xml  # disease defs and xrefs
en_product2_ages.xml  #inheritance, age of onset, age of death
en_product2_prev.xml    #prevelance and incidence
en_product4.xml  #  clinical signs and symptoms
en_product6.xml  #disease-to-gene relationships

similar to omim, we can build the vocabulary without the hierarchy, making the orphanet classes with their labels and definitions.
then we can add any annotations to the diseases, using the D2PAssoc and G2PAssoc models.

There is a new classification scheme that has been introduced, to place each orpha disease under a single parent.  @tudorgroza are these the classifications you speak of?  they have some [documentation here] (http://www.orpha.net/orphacom/cahiers/docs/GB/Orphanet_linearisation_rules.pdf).  That is http://www.orphadata.org/data/xml/en_product7.xml.

**Comment by nlwashington** [comment]
@pnrobinson or @drseb what parts of the orphadata to you pull into the HPO phenotype annotation set, so that we can best manage any overlaps?

**Comment by tudorgroza** [comment]
Yes - the actual data is here http://www.orphadata.org/cgi-bin/inc/product3.inc.php
Personally, I would maintain the multiple inheritance, if that is possible / desired.

**Comment by nlwashington** [comment]
ah, but that product3 is basically the ontology, no?  and i believe there are some issues (that i don't quite understand) about merging orphanet classification hierarchy and the disease ontology.  perhaps best addressed through discussion here https://github.com/obophenotype/human-disease-ontology/issues/15 ?

**Comment by tudorgroza** [comment]
Not sure if it is the ontology per se ... or it goes beyond that - I would have to look into that. Thanks.

**Comment by drseb** [comment]
Hi,

I have SAX-parsers for the following Orphanet-files:
- Diseases cross-references (I need the OMIM-ref): http://www.orphadata.org/data/xml/en_product1.xml
- The clinical signs of the diseases: http://www.orphadata.org/data/xml/en_product4.xml
- Disease-gene mapping: http://www.orphadata.org/data/xml/en_product6.xml

I currently use the orphanet-symptom mapping from us, but I saw, that they now have produced another mapping. Not sure how they constructed this; does anybody know? 


Seb

**Comment by tudorgroza** [comment]
I will be in Paris next week and try to get the latest version of the clinical signs to HPO mapping. I'll also produce parsers for the entire dataset - including epidemiology data and classifications - in max. 2 weeks.

**Comment by nlwashington** [comment]
examples for triples might include:
<pre>
_:somevariantofAGA a SO:0001059  #sequence_alteration
	RO:has_phenotype Orphanet:93
	GENO:is_sequence_variant_of NCBIGene:AGA
annotid:### a Annotation
	hasSubject _:somevariantofAGA 
	hasPredicate RO:has_phenotype
	hasObject Orphanet:93
	dc:source PMID:11309371
	RO:ageOfOnset HP:childhood
	dc:evidence ECO:#####  #some evidence code for known disease-causing mutation
Orphanet:93 has_phenotype HP:0001999
annotid:### a Annotation
	hasSubject Orphanet:93
	hasPredicate RO:has_phenotype
	hasObject HP:0001999
	hasFrequency HP:VeryFrequent  #could leave this out
_:somevariantofGNPTAB a SO:0001559   #LOF variant
	RO:has_phenotype Orphanet:576
	GENO:is_sequence_variant_of NCBIGene:GNPTAB
Orphanet:576 RO:has_phenotype HP:0000280
annotid:### a Annotation
	hasSubject _:somevariantofAGA 
	hasPredicate RO:has_phenotype
	hasObject Orphanet:576
	dc:source PMID:18425436
	RO:ageOfOnset HP:neonatal
	dc:evidence ECO:#####  #some evidence code for known disease-causing mutation	
annotid:### a Annotation
	hasSubject Orphanet:576
	hasPredicate RO:has_phenotype
	hasObject HP:0000280
	hasFrequency HP:VeryFrequent  #could leave this out
_:somevariantofEFHC1 a SO:0001059     #sequence_alteration
	monarch:increased_susceptibility_to_phenotype Orphanet:1941
	GENO:is_sequence_variant_of NCBIGene:EFHC1
annotid:### a Annotation
	hasSubject _:somevariantofEFHC1 
	hasPredicate monarch:increased_susceptibility_to_phenotype
	hasObject Orphanet:1941
	dc:source PMID:17159113
	RO:ageOfOnset HP:childhood
	dc:evidence ECO:#####  #some evidence code for “assessed” disease-association	
_:somevariantofJRK a SO:0001059   #sequence_alteration   
	monarch:associated_with Orphanet:307
	GENO:is_sequence_variant_of NCBIGene:JRK
annotid:### a Annotation
	hasSubject _:somevariantofJRK 
	hasPredicate monarch:associated_with
	hasObject Orphanet:307
	dc:source PMID:11463517
	RO:ageOfOnset HP:adolescent
	dc:evidence ECO:#####  #some evidence code for “not-yet-assessed” candidate disease-association	
</pre>
the examples above all have an anonymous node that is a sequence_variant or sequence_alteration of the listed gene, with a link to the gene via the GENO:is_sequence_variant_of relationship.  please use a gene identifier for the gene listed (NCBI/Entrez gene preferred, prefixed with NCBIGene, but i'll take whatever you can give.)
each 
we clearly need some new predicates here.  i've asked (and shall add) some new RO terms for associated_with and increased_susceptibility_to_phenotype.  temporarily you can add those predicates prefixed with monarch.
ageOfOnset terms are in HP, here: http://purl.obolibrary.org/obo/HP_0011007
evidence codes probably need to be expanded.  we may consult with @cmungall for those, once we get the rest of the triples nailed down.

**Comment by nlwashington** [comment]
@drseb parsers in python?  if so, can you point us to the repo?

**Comment by drseb** [comment]
nope. all in java.

**Comment by nlwashington** [comment]
Orphanet qualifies their disease-gene associations to be "assessed" vs "not yet assessed".  Unfortunately, they don't really provide the evidence of the gene-disorder associations in the association file, and the website is very opaque about what it means to be "assessed".  so i don't really understand how to map this to either an ECO code or something else.

Some options about what we can do with this flag:

1.  choose a proper ECO code to delineate what is "assessed" vs "unassessed".  two that seem relevant are:
    * ECO_0000322: imported manually asserted information used in automatic assertion
    * ECO_0000323: imported automatically asserted information used in automatic assertion
2.  attach a qualifier to the association itself, which is different from the evidence code.  we haven't ever done this before.  there isn't a good quality in PATO (as they are phenotypic qualities, not qualities of information), and the closest is the "[reviewed](http://semanticscience.org/resource/SIO_001034)" quality in SIO, but there is no parallel quality for "unreviewed". 
3.  change the type of Association to be some kind of "reviewed association" vs "unreviewed association".  again, i don't really know what this means.

**Comment by nlwashington** [comment]
@drseb what fraction of the clinical signs to you pull into the HPO pipeline?  would there be a reason for me to get these associations from Orphanet directly?

**Comment by nlwashington** [comment]
Initial implementation processes the disease-gene associations, using the association type to determine the relationship.  for the first pass i'm using the ECO:0000322/3 codes as described above.

**Comment by drseb** [comment]
Regarding the disease-gene association I can only give you the hint that you should pay attention to the cases where one Orphanet disease maps to multiple MIM diseases. 
This does not work well with the disease gene associations. For example if an Orphanet entry O maps to multiple genes G and multiple MIM diseases M, we cannot transfer all information (e.g. G) of the O to all M. I only merge Orphanet entries with OMIM entries if it is 1:1. 
This discussion might be more important for the [human-disease-ontology project](https://github.com/monarch-initiative/human-disease-ontology)

**Comment by drseb** [comment]
For the signs&symptoms, I use a mapping file we generated some time ago (Orphanet never commented on). It is available [here](http://compbio.charite.de/svn/hpo/trunk/src/mappings/onet_hpo.tsv).

I have no idea what mapping Orphanet uses or suggest to use. @tudorgroza mentioned he wanted to discuss this with the Orphanet-people. Any information?

**Comment by tudorgroza** [comment]
They have a newer version I think (when was this one generated?) ... I can send it to you via email if it helps (just need to dig it out). From a process perspective, afaik they switched to using HPO exclusively for phenotype annotations - there's even a paper about this in Phenotype Day this year: http://phenoday2015.bio-lark.org/pdf/10.pdf. I'll have more info in 2-3 weeks.

**Comment by nlwashington** [comment]
@drseb thanks for the hints. i am attempting to keep the annotations (disease-gene) to the originally annotated entities, so will keep the associations to only the Orphanet disease.  Propagation across equivalences of disease will be made based on the ontology equivalence axioms, which I leave to the ontologists to sort out.  :)  additionally, i'm making sure to use the appropriate relationship identifiers based on the association type listed (which isn't always a "causative" link).

i can certainly process the phenotypes they produce, but perhaps this is a larger consortium discussion?

**Comment by nlwashington** [comment]
as a followup, the "mapping" file on their website is out of date (2013), and relationships between orpha signs and HPO are only XREFs... i would hesitate to use these as of now.  perhaps something will come out of the PhenoDay meeting.  for now, i will not process the signs/symptoms, and rely on @drseb's processing of the Orphanet phenotypes.  (will pull them in directly in a new ticket when the data becomes available.)

**Comment by nlwashington** [comment]
![screen shot 2015-06-26 at 4 40 25 pm](https://cloud.githubusercontent.com/assets/5124411/8389240/1370a570-1c22-11e5-8a83-8a9e0e9d03f9.png)
