### ISSUE TITLE
chr, chr collection, and genome build

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#68]
how to model chromosomes and their relationship to a genome build?
for each species, there is a versioned genome (reference genome) with an identifier, that it's chromosomal coordinates are based on.

i can make the "hg19" an instance of SO:reference_genome, but what is the relationship between it and the chromosomes that are part of that build?  RO:is_subsequence_of doesn't seem quite right.  maybe member_of?

**Comment by nlwashington** [comment]
furthermore, what should i connect the taxon to?  the build?  each chromosome?

**Comment by mellybelly** [comment]
do we need an uber-genome concept ? basically a summary level description of a genome build, where the builds themselves are versions?

**Comment by mbrush** [comment]
I agree that member_of is more appropriate than subsequence_of. Another option is has_reference_part, but this property may only be needed if we have reasoning implications to consider for the data (e.g. defining property chain definitions over specific relations to support things like phenotype propagation), and I don’t think this is the case here.
 
This raises a couple points.  First, being able to look at the data is always useful to provide context in which to make modeling decisions. There are always many approaches to take, and only in considering the data and use cases can we determine which is best.  Lets look at the data here on our next call. And generally we should try to indicate the data source behind a modeling questions (and if relevant describe or give examples/links to the data)?

Second, the has_subsequence has popped up in several threads now. I will explore the origin and semantics of this relation, if and when it should be used in our data, and what is its relationship to part_of relations in GENO or RO such as has_variant_part, has_reference_part, and has_member.

**Comment by mbrush** [comment]
I think it is sufficient to attach the taxon to the genome build (or the genome if we have an uber genome).  We can infer an association between each chromosome with a rule or property chain - depending on the relation and design patterns we use here.

As for the uber genome, it seems this could be a class, and each build an instance of the class. e.g.

    'NCBI human genome'   a    owl:class
    'NCBI human genome' subclassOf  'genome'
    'build hg19'   a   'NCBI human genome'

**Comment by nlwashington** [comment]
@mbrush close if satisfied.
