### ISSUE TITLE
IRIs in hpoa.ttl are mistakenly string values

### ISSUE THREAD

**Issue by balhoff** [monarch-initiative/dipper#681]
I downloaded `https://data.monarchinitiative.org/ttl/hpoa.ttl`. It can't load properly as OWL, because (like other dipper files) it states that `dc:source` is an object property, however there are many `dc:source` values in this file which are strings.

I assume all these strings are supposed to actually be IRIs:

```turtle
:MONARCH_b00012161a6f63bad72e a OBAN:association ;
    OBO:RO_0002558 OBO:ECO_0000501 ;
    dc:source "http://omim.org/entry/148050" ;
    OBAN:association_has_object OBO:HP_0008438 ;
    OBAN:association_has_predicate OBO:RO_0002200 ;
    OBAN:association_has_subject OBO:OMIM_148050 .
```

The `dc:source` property has IRI values in other dipper files.

cc @shalsh23

**Comment by kshefchek** [comment]
@balhoff is there an owltools, robot (or some other tool) command to verify if our properties are used correctly.  This could be a useful qc step.

**Comment by balhoff** [comment]
Oh, one thing that could be confusing in my post—the problem is not that it says `dc:source` is an object property. It's that it's an object property and has string values.

Being an object property could conflict with how `dc:source` is used in other ontologies, but that's not the problem here.

Loading into robot and saving in another format would likely demonstrate this error.

**Comment by TomConlin** [comment]
Likely object as literal is defaulting to True in an association class. 
I almost done (hours?) with all the furniture moving refactoring I can stand.
this should be easy enough to run down then

**Comment by cmungall** [comment]
Historically frequency has been a mix of free text and ontology classes, but I think it should always be ontologized now?

**Comment by pnrobinson** [comment]
No -- ontology terms are the least useful form a frequency information because they are the least exact -- the ontology should should be used only as a last resort (if all we know is that some feature is "rare" or whatever)!

**Comment by TomConlin** [comment]
I made a comment when reviewing Peter's HPO annotation format change  I will paraphrase here:

```
    What would make the Ontology identifiers useful here is a way to make them even approximately comparable with the proper rationals.
```

**Comment by TomConlin** [comment]
https://github.com/monarch-initiative/dipper/pull/691 closed original issue

**Comment by balhoff** [comment]
@TomConlin I still see this problem in the latest `hpoa.ttl` data file dated `2019-01-05`. Should the fix have made it out by now?

**Comment by TomConlin** [comment]
I do see improvement across the board where objects not specifically flagged as literals are considered as curies / IRI before defaulting to literals as they were before. 

I will look more closely at hpoa. either an object explicitly flagged as a literal is incorrect or my test needs more relaxing (has already become more permissive than regulation curies)

**Comment by TomConlin** [comment]
We have several bad PubMed data entries which could not be helping

"PMID:9557891PMID:9557891" .
"PMID:12687501:PMID:17918734" .
"PMID:PMID:10668560" .

the others are 
    434 "ISBN-13
       8 "ISBN-10

As these are in the curie map I am going to go with rdflib limitations 
recognising them as valid curies (since they are not valid qnames with the hyphens).
There have been some long standing issues open on rdflib around recognising curies.

I seem to have them in curie_map.yaml under the heading  "# more bogus IRIs"

The PMIDs I can and fix no problem.

And I would have no problem dropping the hyphens in the curie prefixes
but expect wailing and gnashing of teeth downstream.

I will note that explicitly adding 'dc:source' as literals  was done deliberately 
(and before my time).

https://github.com/monarch-initiative/dipper/issues/225 

makes me worry something awful may be relying on this behaviour

**Comment by balhoff** [comment]
The problems I found look like unusual cases, for example:

```turtle
:MONARCH_b0b44b0227c66d930f6c a OBAN:association ;
    OBO:RO_0002558 OBO:ECO_0000269 ;
    dc:source "PMID:9557891PMID:9557891" ;
    OBAN:association_has_object OBO:HP_0000993 ;
    OBAN:association_has_predicate OBO:RO_0002200 ;
    OBAN:association_has_subject <http://omim.org/entry/130000> .
```

```turtle
:MONARCH_b7bc9d847b72776825a0 a OBAN:association ;
    OBO:RO_0002558 OBO:ECO_0000269 ;
    dc:source "PMID:12687501:PMID:17918734" ;
    OBAN:association_has_object OBO:HP_0004209 ;
    OBAN:association_has_predicate OBO:RO_0002200 ;
    OBAN:association_has_subject <http://omim.org/entry/607872> ;
    :frequencyOfPhenotype "12/30" .
```

**Comment by balhoff** [comment]
Since `dc:source` is stated to be an `owl:objectProperty`, it must not have literal values in this file.

**Comment by balhoff** [comment]
Perhaps the answer is to just declare it to be an `owl:annotationProperty`? I'm not sure what purpose it serves for it to be an object property. I think it is most frequently used as an annotation property.

**Comment by pnrobinson** [comment]
@TomConlin I recently did a cleanup of some these errors -- do you have the latest version of the annotation data?

**Comment by pnrobinson** [comment]
Please let me know the issues and I will fix

**Comment by TomConlin** [comment]
from above

 - "PMID:9557891PMID:9557891"  

Is two PubMed curies with nothing between them.
Previous format choices all resulted in a  single line for a single item
I do not recall if the column "Pub" was one that came up already  
but my recommendation would be to split the row with this Siamese "Pub"  
into two rows each with a single curie


 - "PMID:12687501:PMID:17918734"  
Siamese curies sharing a colon ... 
same as the last after amputating the common colon


- "PMID:PMID:10668560"   

The latter curie either absorbed it's sibling curie  
or  experienced a prefix duplication event.  
Recommend one row with the second curie  
snip and cauterize the former prefix.   
We must prevent prefix duplication from spreading to the greater curie population.

**Comment by pnrobinson** [comment]
I have repaired the three affected small files. This should be OK now in the next release.

**Comment by TomConlin** [comment]
@balhoff  Hi Jim,  there should be a new `hpoa.ttl` file in place with out any literals for sources

ref https://github.com/monarch-initiative/dipper/pull/697

**Comment by balhoff** [comment]
Thanks @TomConlin!

**Comment by TomConlin** [comment]
I think this can be closed. 
Peter's dataset improvements should show up unfiltered next release
