### ISSUE TITLE
Quality control on gene-disease assocs

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/dipper#685]
Many of these are wrong
https://monarchinitiative.org/disease/MONDO:0007947#genes

@kshefchek to fill in details

**Comment by cmungall** [comment]
One of these are due to https://github.com/monarch-initiative/mondo/issues/560, but not all

**Comment by pnrobinson** [comment]
?There are multiple problems and this should be discussed on zoom asap.



Peter Robinson
Professor and Donald A. Roux Chair, Genomics and Computational Biology
The Jackson Laboratory for Genomic Medicine
860.837.2095 t | peter.robinson@jax.org | https://robinsongroup.github.io/
Peter Robinson
________________________________

**Comment by kshefchek** [comment]
Theres not too much to do until we can push the latest data and version of mondo.  In the meantime I've removed CTD is_marker_for associations on production.

**Comment by cmungall** [comment]
I still see the is_marker_fors?

When will the next data release be? Should we patch in the interim?

**Comment by kshefchek** [comment]
I realized that filtering on relation is not always reliable, https://github.com/SciGraph/golr-loader/issues/35

I think the better solution is to require one more sources for each association, eg is_defined_by(omim OR omia ...), our sources and counts are [here](https://solr.monarchinitiative.org/solr/golr/select/?q=*%3A*&facet=true&facet.method=enum&fq=subject_category%3Agene&fq=object_category%3Adisease&facet.limit=3000&rows=0&wt=json&facet.mincount=1&indent=on&facet.sort=count&facet.field=is_defined_by).  Happy to specify omim as a requirement for all associations.
