### ISSUE TITLE
add licensing info to current sources

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#69]
all of our sources need to keep the licensing info around.  

this should probably be documented in each source parser and/or embedded with in the dataset object.  it looks like from the [HCLSdatasetDescriptions](https://github.com/joejimbo/HCLSDatasetDescriptions/blob/master/Overview.html), this can be linked using a dct:license to the IRI of the license.  I would love if we'd be able to get to either the license description at the source's page, or a public one like this:
http://creativecommons.org/licenses/by-sa/3.0/

**Comment by bryanlaraway** [comment]
I've added some information for all of our current sources (see below). 

BioGrid: Has a [terms & conditions](http://wiki.thebiogrid.org/doku.php/terms_and_conditions) page available, linked as the license.

ClinVar: Links to the [NCBI Copyright and Disclaimers] page as the license. Indicated as public domain, so I linked to the [Public Domain Mark 1.0](https://creativecommons.org/publicdomain/mark/1.0/) page in CreativeCommons.org as the rights.

Coriell: In NIF/DISCO, they link this [MTA](http://ccr.coriell.org/Sections/Support/Global/AFSG.aspx?PgId=210) page, which seems a little strange as we're using the data as opposed to the actual materials/cell lines. There is a [legal notice](https://www.coriell.org/legal-notice) page for the Coriell website itself. Do we have a license on file, or should I make a request through our contacts?

CTD: Linked to the [Legal Notices](http://ctdbase.org/about/legal.jsp) page.

EOM: Linked to the [NHGRI Copyright](http://www.genome.gov/copyright.cfm) page. Indicated as public domain, so I linked to the [Public Domain Mark 1.0](https://creativecommons.org/publicdomain/mark/1.0/) page in CreativeCommons.org as the rights.

GeneReviews: Linked to the [Copyright Notice and Usage Disclaimer](http://www.ncbi.nlm.nih.gov/books/NBK138602/) page as the license.

HPOAnnotations: Added link to [legal issues](http://www.human-phenotype-ontology.org/contao/index.php/legal-issues.html) page as the license.

IMPC: Added link to the [Apache license](https://raw.githubusercontent.com/mpi2/PhenotypeArchive/master/LICENSE) linked from the IMPC homepage.

MGI: Added link to the [Warranty Disclaimer and Copyright Notice](http://www.informatics.jax.org/mgihome/other/copyright.shtml) page, indicating data provided "as is."

NCBIGene: Links to the [NCBI Copyright and Disclaimers] page as the license. Indicated as public domain, so I linked to the [Public Domain Mark 1.0](https://creativecommons.org/publicdomain/mark/1.0/) page in CreativeCommons.org as the rights.

OMIM: Added a link to the [Use Agreement](http://omim.org/help/agreement) page as the license. There is also a  [Copyright](http://omim.org/help/copyright) page available, but not currently linked.

Panther: Added a link to the [Disclaimer}(http://www.pantherdb.org/terms/disclaimer.jsp) page as the license, which covers liability and warranties, but not necessarily license information.

UCSCBands: Added link to [license](http://genome.ucsc.edu/license/) page, which indicates the Genome Browser binaries and source code as freely available for academic, nonprofit, and personal use.

ZFIN:Added link to the [Warranty](http://zfin.org/warranty.html) page, which covers restrictions, warranty (none), and limitation of liability info.

In going through these resources, I see requests for citations and/or acknowledgements. Shall I add these somewhere? I see that there is a [DCTerms:bibliographicCitation](http://dublincore.org/documents/dcmi-terms/#terms-bibliographicCitation) property, but not an "acknowledgements" property. Perhaps the [publisher](http://dublincore.org/documents/dcmi-terms/#terms-publisher) property? Example acknowledgement would be something like "Courtesy: National Human Genome Research Institute."

**Comment by nlwashington** [comment]
the triples look like:
<pre>
source_id a dctypes:Dataset ;
    dct:license http://www.human-phenotype-ontology.org/contao/index.php/legal-issues.html ;
</pre>
for many of the ones you list above, you are linking to some legalish-text, but not an actual license (seeing as that might be all that is provided).  i wonder if we need to track down the exact licenses? @mellybelly or @cmungall should comment here.  and/or, should most of the things above instead be linked via a [dct:RightsStatement](http://udfr.org/docs/onto/dct_RightsStatement.html)?

i've also opened a [separate ticket](#115) about the citation info.
