### ISSUE TITLE
add data source ClinVar

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#7]
We need to add ClinVar as a data source:

ftp://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/ClinVarFullRelease_00-latest.xml.gz

**Comment by nlwashington** [comment]
we can start with the easy tab-delimited parsing of the clinvar flat file.  we won't get everything, but it'll be a start.

http://ftp.ncbi.nlm.nih.gov/pub/clinvar/tab_delimited/variant_summary.txt.gz

details on the format:
http://ftp.ncbi.nlm.nih.gov/pub/clinvar/tab_delimited/README

**Comment by nlwashington** [comment]
@bryanlaraway you can go ahead and work on the flat-file version to see how far we get.

**Comment by bryanlaraway** [comment]
If we haven't already tried pulling in an XML-based resource, Orphanet would be good for practice. The data is divided across multiple XML files, and the schema for each file is not as complicated/nested as the full XML file from ClinVar.

**Comment by nlwashington** [comment]
need to write a few tests, refine the cmap, and then this is finished.

**Comment by nlwashington** [comment]
updated cmap.  example here is for an association for one of the variants of BRCA.  and the other is modeling the location information.
![screen shot 2015-07-01 at 5 08 59 pm](https://cloud.githubusercontent.com/assets/5124411/8467497/e7db2930-2013-11e5-9415-df0f1232d804.png)
![screen shot 2015-07-01 at 5 08 54 pm](https://cloud.githubusercontent.com/assets/5124411/8467498/e8018120-2013-11e5-97e7-423501f2a2c3.png)

**Comment by nlwashington** [comment]
there is still data missing due to the fact that we are processing the flat file instead of the xml (for example, if there's >1 affected gene, we are not getting those), nor are we getting the evidence/publication information for the associations.  that will come in the next phase.

**Comment by nlwashington** [comment]
processing the xml for the additional data will come in a subsequent issue #155
