### ISSUE TITLE
OMIM phenotypic series IRIs incorrect

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/dipper#701]
Currently: OMIM:PS1234, which expands to

https://www.omim.org/entry/PS309530

They should link to:
https://www.omim.org/phenotypicSeries/PS309530

Perhaps we should have a new entry in the curie map,
OMIMPS: https://www.omim.org/phenotypicSeries

**Comment by cmungall** [comment]
MONDO uses OMIMPS

**Comment by TomConlin** [comment]
Here is OMIM  output from my fork.  OMIMPS is represented over towards the right. 
Comments are welcome for a while and I will make a PR tomorrow most likely.
Thoughts/Concerns/Wishes on other aspects are also welcome.  
  
[omimps.pdf](https://github.com/monarch-initiative/dipper/files/2834654/omimps.pdf)
