### ISSUE TITLE
NCBI gene parser linking human genes to yeast (taxon)

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/dipper#704]
The latest scigraph load contains a lot of genes with >1 taxa:
[gene >1 query](https://scigraph-data-dev.monarchinitiative.org/scigraph/cypher/execute.json?cypherQuery=MATCH+(taxon1)%3C-[%3ARO%3A0002162]-(n%3Agene)-[%3ARO%3A0002162]-%3E(taxon2)+WHERE+taxon1+%3C%3E+taxon2+AND+taxon1.iri+%3E+taxon2.iri+RETURN+COUNT(DISTINCT(n))+as+genes)

Diving deeper this appears to be coming from ncbi gene:
[gene with isDefinedBy](
https://scigraph-data-dev.monarchinitiative.org/scigraph/cypher/execute.json?cypherQuery=MATCH+(taxon1)%3C-[tax1%3ARO%3A0002162]-(n%3Agene)-[tax2%3ARO%3A0002162]-%3E(taxon2)+WHERE+taxon1+%3C%3E+taxon2+AND+taxon1.iri+%3E+taxon2.iri+RETURN+n.iri+as+genes,taxon1.iri,taxon2.iri,tax1.isDefinedBy,tax2.isDefinedBy)

Could also be clique merging gone wrong

**Comment by cmungall** [comment]
odd.. clique merge seems most likely?

**Comment by kshefchek** [comment]
It looks like it's coming from the ncbi gene output:

    $ grep -A 10 'gene\/157657' ncbigene.ttl

    <https://www.ncbi.nlm.nih.gov/gene/157657> a owl:Class ;
        rdfs:label "C8orf37" ;
        OBO:RO_0002162 OBO:NCBITaxon_559292 ;
        OBO:RO_0002525 OBO:CHR_9606chr8q22.1 ;
        dc:description "chromosome 8 open reading frame 37" ;
        oboInOwl:hasDbXref ENSEMBL:ENSG00000156172 ;
        oboInOwl:hasExactSynonym "chromosome 8 open reading frame 37" ;
        oboInOwl:hasRelatedSynonym "BBS21",
            "Bardet-Biedl syndrome 21",
            "CORD16",
            "RP64",

**Comment by TomConlin** [comment]
it is not being said in the ncbi gene info file (from Dec 16th abnyway)

    zgrep  "[[:space:]]157657[[:space:]]" raw/ncbigene/gene_info.gz 
    9606	157657	C8orf37	-	BBS21|CORD16|RP64|smalltalk	MIM:614477|HGNC:HGNC:27232|Ensembl:ENSG00000156172	8	8q22.1	chromosome 8 open reading frame 37	protein-coding	C8orf37	chromosome 8 open reading frame 37	O	protein C8orf37|Bardet-Biedl syndrome 21	20181207	-

**Comment by TomConlin** [comment]
On my local machine after fixing I now see:
```
<https://www.ncbi.nlm.nih.gov/gene/157657> a owl:Class ;
    rdfs:label "C8orf37" ;
    OBO:RO_0002162 "NCBITaxon::9606" ;
    OBO:RO_0002525 OBO:CHR_9606chr8q22.1 ;
    dc:description "chromosome 8 open reading frame 37" ;
    oboInOwl:hasDbXref ENSEMBL:ENSG00000156172 ;
    oboInOwl:hasExactSynonym "chromosome 8 open reading frame 37" ;
    oboInOwl:hasRelatedSynonym "BBS21",
        "Bardet-Biedl syndrome 21",
        "CORD16",
        "RP64",
```
will make a PR & rerun

**Comment by kshefchek** [comment]
> OBO:RO_0002162 "NCBITaxon::9606" ;

Looks wrong - the curie is being treated as a literal and there are two colons.  Perhaps a unit test is in order?

**Comment by TomConlin** [comment]
Is literal because double colon makes an invalid curie
started with   `'prefix:' + lclid`  but switched to  `':'.join(('prefix',  lclid))`  to match existing
and neglected to strip the trailing colon.

**Comment by kshefchek** [comment]
With this fix we have 45936 genes in >1 taxon, up from 0 from the last release.  The first 1000 are here:
https://scigraph-data-dev.monarchinitiative.org/scigraph/cypher/execute.json?cypherQuery=MATCH+(taxon1)%3C-[tax1%3ARO%3A0002162]-(n%3Agene)-[tax2%3ARO%3A0002162]-%3E(taxon2)+WHERE+taxon1+%3C%3E+taxon2+AND+taxon1.iri+%3E+taxon2.iri+RETURN+n.iri+as+genes,taxon1.label,taxon2.label,tax1.isDefinedBy,tax2.isDefinedBy&limit=1000

Excepting the first, the rest look okay.  Theres nothing wrong with connecting to genes to species and strains, but we'll have to update our QC to check is the two taxa are some distance from each other (>1 subClassOf edge).

**Comment by kshefchek** [comment]
I've adjusted the query:

MATCH (taxon1)<-[:RO:0002162]-(n:gene)-[:RO:0002162]->(taxon2)
WHERE taxon1 <> taxon2 AND NOT (taxon1)-[:subClassOf]-(taxon2)
RETURN COUNT(DISTINCT(n)) as genes

Which returns one gene:
https://www.ncbi.nlm.nih.gov/gene/112445582

Which is a pseudo gene, I think we're okay :+1:
