### ISSUE TITLE
OMIM gene treated as a sub class of 'disease'

### ISSUE THREAD

**Issue by deepakunni3** [monarch-initiative/dipper#711]
Ran into this issue when ingesting the latest [omim.ttl](https://data.monarchinitiative.org/ttl/omim.ttl), for NCATS Translator user-case, where OMIM:147090 is considered as a subClassOf MONDO:0000001 (disease) which seems unusual.

```ttl
<http://omim.org/entry/147090> a owl:Class ;
    rdfs:label "IGLP2" ;
    dc:description "Immune Response to Synthetic Polypeptide--Irglphe 2" ;
    oboInOwl:hasDbXref UMLS:C3887957 ;
    oboInOwl:hasExactSynonym "IMMUNE RESPONSE TO SYNTHETIC POLYPEPTIDE--IRGLPHE 2; IGLP2" ;
    oboInOwl:hasRelatedSynonym "IGLP2" ;
    rdfs:subClassOf OBO:MONDO_0000001 .
```

File timestamp:
```
omim.ttl                                           14-Feb-2019 19:49            87195027
```

CC'ing @cmungall @kshefchek @TomConlin

**Comment by TomConlin** [comment]
Interesting I ave one from four days before than and it is not there

**Comment by kshefchek** [comment]
Looks like we're potentially making subClassOf assertions here:
https://github.com/monarch-initiative/dipper/blob/9a90930/dipper/sources/OMIM.py#L458

I think as a general rule we should avoid any disease classification in dipper, since we have MONDO.  For other class/individual types we sometimes need this.

**Comment by TomConlin** [comment]
Omim.py makes a single explicit class/subclass  assertion 
and that is between OMIM  and PhenotypicSeries
https://github.com/monarch-initiative/dipper/blob/9a90930/dipper/sources/OMIM.py#L1038

Within `model.addClassToGraph()`
by https://github.com/monarch-initiative/dipper/blob/9a90930047a68d500c94b701b9f4288e30438ae9/dipper/models/Model.py#L50

we should be able to avoid the automatic subclass generation
by not including the `class_type` parameter

Note: `model.addClassToGraph` is called at least a hundred times in over thirty files 
reasoning about  each is going to be required.

**Comment by TomConlin** [comment]
In my test file I now see:  

```
<http://omim.org/entry/147090> a owl:Class ;
    rdfs:label "IGLP2" ;
    dc:description "Immune Response to Synthetic Polypeptide--Irglphe 2" ;
    oboInOwl:hasDbXref UMLS:C3887957 ;
    oboInOwl:hasExactSynonym "IMMUNE RESPONSE TO SYNTHETIC POLYPEPTIDE--IRGLPHE 2; IGLP2" ;
    oboInOwl:hasRelatedSynonym "IGLP2" .

```
