### ISSUE TITLE
Investigate dropping g2p data from flybase

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/dipper#716]
The dipper build on the FB2018_06  ftp://ftp.flybase.net/releases/FB2018_06/ release resulted in a large decrease in gene to phenotype data:

Drosophila melanogaster: 88953 (-_126592_) 

For the FB2019_01 build the only phenotype left is FBcv_0001347, which is not a meaningful association:

Drosophila melanogaster: 11374 (-_204171_)

    grep -oP 'FBcv_\d+' flybase.nt | sort -u
    FBcv_0001347

**Comment by TomConlin** [comment]
I'm away now but would start with:
https://github.com/monarch-initiative/dipper/blob/master/dipper/sources/FlyBase.py#L855

**Comment by kshefchek** [comment]
I ran it with 41a5e2d and the data looked better, so I suspect a translation table or bnode pruning update may have broken something.  In any case, this ingest is in need of a rewrite or overhaul.

**Comment by kshefchek** [comment]
Fixed with https://github.com/monarch-initiative/dipper/pull/760
