### ISSUE TITLE
Change ORPHANET to Orphanet and fix URI prefix

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/dipper#73]
Ideally this would be at source (HPO).

The ordo owl files uses http://www.orpha.net/ORDO/Orphanet_nnn

**Comment by nlwashington** [comment]
you want the prefix to be http://www.orpha.net/ORDO/Orphanet_nnn rather than http://purl.obolibrary.org/obo/Orphanet_nnnn ?

**Comment by nlwashington** [comment]
orphanet ids are referenced in HPO annots, OMIM, and ClinVar.

**Comment by cmungall** [comment]
Yes, that's the URI form used in the original ORDO OWL

**Comment by cmungall** [comment]
Yes, the CURIEs should be Orphanet:nnn, ie Orphanet maps to  http://www.orpha.net/ORDO/Orphanet_

**Comment by nlwashington** [comment]
this is now complete.
