### ISSUE TITLE
omim.ttl contains URIs with comma-separated IDs

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/dipper#742]
E.g.

```
###  http://purl.obolibrary.org/obo/OMIM_PS614080,PS308350
<http://purl.obolibrary.org/obo/OMIM_PS614080,PS308350> rdf:type owl:Class .
```

**Comment by justaddcoffee** [comment]
Where did you see this? Can't find this erroneous triple [here](https://data.monarchinitiative.org/ttl/omim.ttl), and can't reproduce this bad triple or any like it running this:
dipper-etl.py -s omim
from current [master branch of dipper](https://github.com/monarch-initiative/dipper/blob/master/dipper-etl.py)

**Comment by kshefchek** [comment]
fixed with https://github.com/monarch-initiative/dipper/pull/725
