### ISSUE TITLE
Do not ingest HGNC regions (e.g. HOXA@)

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/dipper#743]

**Comment by TomConlin** [comment]
Eliminating 'region' still leaves  the last four.
```
cut -f 2,5  raw/hgnc/hgnc_complete_set.txt | grep "@" | cut -f2 | dist
     31 withdrawn
      6 region
      3 gene with protein product
      1 RNA, cluster
```

**Comment by TomConlin** [comment]
Eliminating 'region' removes many symbols without an "@" suffix.

```
cut -f 2,5  raw/hgnc/hgnc_complete_set.txt | grep "region"  |grep -v "@"
AMLCR2	region
ANCR	region
BVR1	region
C3CER1	region
CECR	region
DCR	region
DEFA1A3	region
DGCR	region
EBVM1	region
ERDA1	region
LOH1CR1	region
LOH19CR1	region
MT7SDNA	region
MTATT	region
MTCSB1	region
MTCSB2	region
MTCSB3	region
MTHPR	region
MTHSP1	region
MTHSP2	region
MTLSP	region
MTOHR	region
MTOLR	region
MTRNR3	region
MTTAS	region
MTTER	region
MTTFH	region
MTTFL	region
MTTFX	region
MTTFY	region
PABX	region
PABY	region
TCL4	region
WBSCR2	region
WHCR	region
XIC	region

```

**Comment by cmungall** [comment]
Thanks. Curious what the 3 "gene with protein product" remaining ones are. Not necessarily wrong to have the `@` but seems unusual.

Regardless of gene names, it's not really clear what value region, RNA cluster or withdrawn bring to us. If we do include these, we should ensure that these are clearly marked in search. But I am leaning towards exclusion. We can discuss on next data call.

Not sure if we have a way of marking tickets for discussion on these calls, I put into the question category for now

**Comment by TomConlin** [comment]
```
PCDHA@	gene with protein product
PCDHB@	gene with protein product
PCDHG@	gene with protein product

```

It would be easy to filter records with an '@'  on the end of the symbol  
but you know the law of unintended consequences and all that

The withdrawn  get a "Deprecated Class" designation and that is about all.

**Comment by cmungall** [comment]
Thanks, interesting.

HGNC has a page for gene groups:
https://www.genenames.org/data/genegroup/#!/group/20

When you view on NCBI you see the spatial arrangement of members:
https://www.ncbi.nlm.nih.gov/gene/56117

**Comment by TomConlin** [comment]
These are all filtered now cloosed by #777
