### ISSUE TITLE
Transgenes from flybase are showing up as genes in autocomplete

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/dipper#744]
E.g. `Drer\{foo}`

**Comment by kshefchek** [comment]
This should be fixed with https://github.com/monarch-initiative/dipper/pull/760, will leave open until we do a full ingest and it's confirmed on beta.

**Comment by kshefchek** [comment]
See https://beta.monarchinitiative.org/ for the latest updates

We still have some genes prefixed with Drer showing up, for example this engineered fusion gene, http://flybase.org/reports/FBgn0022337

Should these be filtered out from either the ingest or the autocomplete index?  If the former we may need to query this out of the relational db as I don't think the flat files have this resolution.

**Comment by kshefchek** [comment]
@cmungall your thoughts on engineered fusion genes showing up in search still?  I'm curious which gene you originally queried that brought up the transgene and if that has been fixed.
