### ISSUE TITLE
Dipper should categorize entities using biolink during ingest

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/dipper#745]
As discussed at hackathon. This will provide 

 1. a simple way to query the ttl file in isolation without joining on an ontology source
 2. summary stats e.g. source S brings in N disease-gene links

We also discussed doing this as a post-processing step; however, the challenge is that the source may use new IDs that are not yet in the ontology which would leave things uncategorized

**Comment by cmungall** [comment]
Note: need to be careful with G2PAssoc.py, this is used by OMIM.py to represent G2D, not G2P

**Comment by kshefchek** [comment]
Would slight disagreement with the biolink model suffice?  As you know we've not yet adopted it in scigraph and the biolink-api.  It would mean:

- phenotype instead of phenotypic feature
- anatomy instead of anatomical entity

**Comment by kshefchek** [comment]
see also https://github.com/monarch-initiative/dipper/issues/745

**Comment by TomConlin** [comment]
I changed Kent's link from pointing to this issue to the PR that still does not have
 a pointer to publicly accessible living document (yaml or json) containing these "categories" along with the rules/limits describing the domains and ranges  of what is in a particular biolink catagory.

**Comment by justaddcoffee** [comment]
Should this issue be merged with #746? They seem very similar, although perhaps some nuance is lost on me. Also, have we decided to record biolink categories for subject and objects during ingest, or just the rdf type of subject and objects (which I think was suggested as an alternative)?

**Comment by TomConlin** [comment]
Merged or nuanced they depend on a coherent statement of biolink category.

**Comment by kshefchek** [comment]
We don't have 100% coverage but between https://github.com/monarch-initiative/dipper/pull/746 and https://github.com/monarch-initiative/dipper/pull/950 going to call this closed
