### ISSUE TITLE
Clarify semantics of Version

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/dipper#753]
We are working on https://github.com/monarch-initiative/monarch-ui/issues/58

We now have version showed on the data sources page, but it's not clear what it means. Source version or version of monarch ingest?

From this it seems like:

https://github.com/monarch-initiative/dipper/blob/b2c20cdcd60cfd4b482a7fed36ec381edf74d7c7/dipper/sources/Source.py#L198-L200

source version is used UNLESS not present THEN ingest version/date is used?

**Comment by justaddcoffee** [comment]
addressed by #809
