### ISSUE TITLE
ClinvarVariant  of type GENO:0000848

### ISSUE THREAD

**Issue by TomConlin** [monarch-initiative/dipper#759]
Although assigned to 83 ClinVar variants in Monarch
`GENO:0000848` has been obsoleted according to OntoBee 
(OLS  also has the term if you tick the obsolete checkbox)

http://www.ontobee.org/ontology/GENO?iri=http://purl.obolibrary.org/obo/GENO_0000848
reason given is:

```
has obsolescence reason:Not required at this poitn, so marked
        exploratory and obsoleted. 
```
no replacement term is supplied.

we generate it via:   

"protein only"  -->  "coding sequence alteration"  --> "GENO:0000848"

an alternative term is required
note: the vast majority of Variant types are translated to SO terms.

edit: candidate terms

 - protein_altering_variant  SO:0001818
 - protein_coding_gene  SO:0001217
 - coding_transcript_variant  SO:0001968

**Comment by kshefchek** [comment]
my vote is,
in the global yaml:

    - coding sequence alteration: "GENO:0000848"
    + coding_transcript_variant: "SO:0001968"
    + protein_altering_variant: "SO:0001818"

in clinvar

    - protein only: "coding sequence alteration"
    + protein only: "protein_altering_variant"

And everywhere else replacing coding sequence alteration with coding_transcript_variant
example: https://www.ncbi.nlm.nih.gov/clinvar/variation/375610/

**Comment by TomConlin** [comment]
Note: also replacing global   
 - "microsatellite": "GENO:0000847"
with
 - "microsatellite": "SO:0000289"

as the former term has apparently been repurposed

**Comment by kshefchek** [comment]
@TomConlin this looks like it's all in the master version of global_terms, closing but reopen if theres still more to be done

**Comment by TomConlin** [comment]
+!
