### ISSUE TITLE
node 'main.html' coming from Panther injest

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/dipper#76]
We're accidentally making a node called main.html while ingesting Panther.  See http://rosie.crbs.ucsd.edu:9000/scigraph/dynamic/homologs.json?gene_id=6469&homolog_id=RO_HOM0000000 as an example

**Comment by nlwashington** [comment]
i don't see this node any more in this specific query.

but i do see somethings oddly when i look for 'main.html': http://rosie.crbs.ucsd.edu:9000/scigraph/vocabulary/id/main.html

i will open that as a separate ticket; this should get taken care of at the SciGraph level.

**Comment by nlwashington** [comment]
you can follow https://github.com/SciGraph/SciGraph/issues/116 for more information.
