### ISSUE TITLE
Latest GO ingest missing human data

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/dipper#766]
Comparing 
http://data.monarchinitiative.org/ttl/go.ttl
to
https://archive.monarchinitiative.org/201902/ttl/go.ttl

It looks like we've lost some data.  We no longer have any NCBIGene or  ENSEMBL curies so it's possible the drop is coming from the human data.

**Comment by TomConlin** [comment]
Have re factored, 
included two new taxon mould & fungi

It is now returning NCBIGene and ENSEMBL curies. 

It is casting some curies as literals via `has_exact_synonym`  will try to address
