### ISSUE TITLE
Fix label for identifiers from GARD

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/dipper#785]
When exploring the results for the term 'polysyndactily,' found that the identifier for an equivalent ID from GARD is incorrectly labeled as `OBO:GARD_0001616,` where it should be `GARD:0001616`

<img width="308" alt="Screen Shot 2019-05-13 at 9 22 29 AM" src="https://user-images.githubusercontent.com/1714621/57637691-e7561780-7560-11e9-8760-52ae1a885293.png">

@deepakunni3 - could you please add more detail here?

**Comment by monicacecilia** [comment]
@pnrobinson - I've transferred the issue to the dipper repo. 
Above, from @kshefchek: Adding GARD and COHD to the curie_map in the dipper repo should fix this.

**Comment by kshefchek** [comment]
This is fixed with https://github.com/monarch-initiative/dipper/pull/788

It should be visible once disease pages are fixed in beta, but for now you can see the fix in the api-dev url above.
