### ISSUE TITLE
IAO_nnnnnnns are typically AnnotationProperties

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/dipper#79]
omim.ttl has:
```
OBO:IAO_0000115 a owl:ObjectProperty .

OBO:IAO_0100001 a owl:ObjectProperty .
```

Should be APs

**Comment by cmungall** [comment]
Looks like this may have been fixed, we just need to regen omim.ttl on nif-crawler?

**Comment by nlwashington** [comment]
yes, this was changed in the global relationship configuration; all properties were being modeled as object properties but now are divided into annotation, data, and object where appropriate.  data sources not on automatic running so regenerating omim now.

**Comment by nlwashington** [comment]
should be fixed; please reopen if it isn't.
