### ISSUE TITLE
refactor morbidmap/omim to link disease to (anonymous) gene-variant instead of gene

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#80]
From morbid map, we currently create annotations like:

geneX has_phenotype Disease

but this really isn't true.  it's actually that:

(some variation of) geneX has_phenotype Disease.

we need to refactor our data and queries to reflect this.

**Comment by cmungall** [comment]
the 'has phenotype' relation is intended as a massive grab bag grouping, with rules such as:

```
G has-phenotype S
G is a gene
S is an abnormal state (disease or abnormal phenotype)
==>
exists some V, V variant-of G,
V gives-rise-to S
```

We could break things down to more specific relations, this would require making a few ontological commitments (which could potentially make things fragile). Provided it's possible to map from the grouping relation to the specific relation chain using domain and range, then we're not really losing anything by using them. However, I can see how relying on domain and range could make certain kinds of queries inefficient.

**Comment by selewis** [comment]
Hi Chris,

You didn't mention "gives-rise-to" when we had our whiteboard discussion on
this. It seems likes there may be some gotcha-s doing it this way. Wouldn't
it be better to simply allow (at multiple levels of genomic granularity)
the phenotype/disease to be associated as closely as the degree of
knowledge allows. Then use the SO partonomy to figure out which gene are
included appropriately for querying?

**Comment by cmungall** [comment]
Yes, we should associate at the deepest level of granularity. For OMIM morbidmap, this is gene to disease.  Of course we could do something like create an anonymous genotype node and say:

    NCBIGene:nnnn --[has part]--> _:1 --[TBD]--> OMIM:nnn

But I think this complicates things

**Comment by nlwashington** [comment]
we could create some anonymous node for a gene-variant (aka allele or variant locus).  for example,
if the morbidmap has an association between:
OMIM:607102 (WT1 gene)  OMIM:608978 (Meacham syndrome)

We can create an anonymous node like:
<pre>
[ a OBO:GENO_0000002 ;
            rdfs:label "some variant of WT1 that causes Meacham syndrome" ;
            OBO:GENO_0000408 OBO:OMIM_607102 ;
            OBO:RO_0002200 OBO:OMIM_608978 ]
</pre>
so that the whole association is like:
<pre>
MONARCH_ffcf68c3e4a71ba5c7325367d8975aa3 a Annotation: ;
    dc:evidence OBO:ECO_0000220 ;
    :hasObject OBO:OMIM_608978 ;
    :hasPredicate OBO:RO_0002200 ;
    :hasSubject [ a OBO:GENO_0000002 ;
            rdfs:label "some variant of WT1 that causes Meacham syndrome" ;
            OBO:GENO_0000408 OBO:OMIM_607102 ;
            OBO:RO_0002200 OBO:OMIM_608978 ]
</pre>

this permits us to use the same pattern for the morbidmap data as we do for genotype-to-phenotype association, because in both patterns we would include some gene-variant.

but i do think that it is a good idea to additionally have an "associated with" kind of relationship, particularly for things like GWAS.  it's entirely possible that here it would be better to use the "associated with" relation, perhaps like https://code.google.com/p/obo-relations/issues/detail?id=47 and the related
 https://code.google.com/p/obo-relations/issues/detail?id=31.
