### ISSUE TITLE
Remove gene to disease ingest from CTD and KEGG

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/dipper#814]
Remove gene to disease data from CTD and KEGG ingests

**Comment by TomConlin** [comment]
Is this part of a broader policy? 
As in; some ingests are authoritative for particular type of assertion and others are not even it they happen to include such statements?   

Is it possible (or even desirable) to  "down grade" human disease statements 
to phenotype statements when the source is not chosen as authoritative?

**Comment by cmungall** [comment]
Yep, we want high-quality data. NSWYM by downgrade to phenotype
