### ISSUE TITLE
Dipper should minimize downloading of ingested files from sources

### ISSUE THREAD

**Issue by justaddcoffee** [monarch-initiative/dipper#817]
We are often being throttled or blocked during our Dipper runs, because of repetitive/frequent downloads of ingested files (OMIM is one example). 

We should minimize downloading of files from source databases by storing cached versions of downloaded resources with preserved download dates (possibly using git lfs or some such), and only downloading files when the cached copy is stale/outdated. 

@kltm curious how the GO solves this problem

**Comment by cmungall** [comment]
we always keep the source file. However, each pipeline run always fetches
the upstream source. It's not a big deal as we are pulling a file eg from
ftp, not hammering an API

**Comment by justaddcoffee** [comment]
Thanks, Chris! Duly noted. 

However, our OMIM ingest for example queries the APIs repeatedly (and in parallel during the Jenkins run), and it seems to have perturbed OMIM enough to block us temporarily today. 

Also, doesn't look like our Jenkins pipeline currently keeps a copy of downloaded files (i.e. the `raw` directory) for subsequent runs to take advantage of...

**Comment by TomConlin** [comment]
To be clear the API  should not be called in parallel (nor by any ingest but OMIM)
Only the `mimTitles.txt` file should have be fetched in parallel by the new pipeline.
(before Kent fixed them to run in serial today)

**Comment by cmungall** [comment]
Yes, for Monarch caching is crucial

**Comment by cmungall** [comment]
Is there any generic mechanism that can be used? E.g.
https://stackoverflow.com/questions/20198274/how-do-i-clear-cache-with-python-requests

**Comment by justaddcoffee** [comment]
I'd say DipperCache ticks this box, closing (but feel free to re-open if anyone disagrees)
