### ISSUE TITLE
clinvar turtle is using incorrect xref property

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/dipper#822]
ttle has triples like:

```
http://www.ncbi.nlm.nih.gov/clinvar/variation/137029    oio:hasdbxref   http://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?rs=76764016
```

the correct URI is oio:hasDbXref (URIs are case sensitive)

Also: this is not a good semantic web URI. Use id.org instead?

**Comment by kshefchek** [comment]
hasDbXref is fixed in https://archive.monarchinitiative.org/201909//ttl/clinvar.nt via https://github.com/monarch-initiative/dipper/pull/819

**Comment by kshefchek** [comment]
fixed in latest release and the old clinvar.ttl has been removed from data.monarch, we are using ntriples for this source now.
