### ISSUE TITLE
Rename ClinVar module and update docs

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/dipper#823]
Trying to figure out clinvar ingest from dipper docs.

It points to:

https://dipper.readthedocs.io/en/latest/dipper.sources.ClinVarXML_alpha.html

Generally not a good idea to embed release state in the file/module name.

Docs say:

_clinvarxml_alpha First pass at converting ClinVar XML into RDF triples to be ingested by SciGraph. These triples conform to the core of the SEPIO Evidence & Provenance model 2016 Apr_

this doesn't look so good if we are pointing people at our docs to figure out our modeling

**Comment by TomConlin** [comment]
>Generally not a good idea to embed release state in the file/module name.


https://github.com/monarch-initiative/dipper/pull/819/files#r317832863
