### ISSUE TITLE
refactor to only add properties and curies that are actually used into each ttl

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#83]
we currently add all properties and the whole curie_map to the graph for every resource.  while not terrible, it ends up bulking up the graph and makes it somewhat unreadable.  it would be better (cleaner) to add the properties and curie definitions to a list of those only if they are used, and then add those to the graph once at the end.  (maybe there should be a "finishing" function added to each source that takes care of things like that?

**Comment by kshefchek** [comment]
This was added some time ago.  For turtle files we now dynamically add prefix mappings as curies are added to the graph, https://github.com/monarch-initiative/dipper/blob/fd99358e5944b2e309e684c15f8f029b6581923f/dipper/graph/RDFGraph.py#L105
