### ISSUE TITLE
THAS is not a gene

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/dipper#859]
## Describe the problem

https://beta.monarchinitiative.org/disease/MONDO:0010742#variant

A clear and concise description of what the issue is.

The variant tab on this site is calling THAS a variant but it is the abbreviation for the disease.

**Comment by pnrobinson** [comment]
Note that the Gene entry has Gene type: UNKNOWN, which is a clue that we should treat this differently from most other Gene entries

**Comment by kshefchek** [comment]
we do, we type it as a heritable phenotypic marker instead of a protein coding gene: http://www.sequenceontology.org/browser/current_svn/term/SO:0001500 or is there a better SO typing?

**Comment by pnrobinson** [comment]
We should filter out these "genes" from being considered as variants/genotypes

**Comment by kshefchek** [comment]
I'll fix at this at the scigraph/neo4j level

**Comment by kshefchek** [comment]
this is fixed in our beta database, which will be pushed to production when our server issues are resolved, marking this as closed

https://beta.monarchinitiative.org/disease/MONDO:0010742
