### ISSUE TITLE
Unable to access HPO data repository

### ISSUE THREAD

**Issue by Prakash2403** [monarch-initiative/dipper#868]
Unable to run for `hpoa` source. Tries to clone a private repo. How to fix this issue? @cmungall @justaddcoffee @balhoff

**Comment by justaddcoffee** [comment]
Hi Prakash - could you please run:
`git show`
and
`./dipper-etl.py -s hpoa`
and copy/paste the output?

**Comment by kshefchek** [comment]
we previously ingested text mined common disease to phenotype associations from a private repo, since we no longer use this we should remove it from the ingest

**Comment by kshefchek** [comment]
looking a little closer at this, the hpoa file is returning a 404:
http://compbio.charite.de/jenkins/job/hpo.annotations.2018/lastSuccessfulBuild/artifact/misc_2018/phenotype.hpoa

@pnrobinson @drseb has this file been rehomed or renamed?

**Comment by pnrobinson** [comment]
Sorry, yes the new address is
http://compbio.charite.de/jenkins/job/hpo.annotations.current/lastSuccessfulBuild/artifact/misc_2018/phenotype.hpoa

I also have asked @drseb to change this to 

http://compbio.charite.de/jenkins/job/hpo.annotations.current/lastSuccessfulBuild/artifact/current/phenotype.hpoa

or even
http://compbio.charite.de/jenkins/job/hpo.annotations.current/lastSuccessfulBuild/artifact/phenotype.hpoa

but I do not think he has had time yet/

**Comment by kshefchek** [comment]
looks like this was updated already and I was just running an old version of dipper, sorry for the false alarm!

@Prakash2403 I'm not able to replicate the issue, unless you are modifying the code slightly to fetch the common disease annotations.

**Comment by Prakash2403** [comment]
@kshefchek @justaddcoffee Just figured out the issue. Was installing dipper using `pip install dipper` which installs version 0.2.32( ~ 2 years older version). Installing from source fixed it.

Thanks for all the help :)

**Comment by kshefchek** [comment]
sorry about this! we'll update the package on pypi
