### ISSUE TITLE
split chr class models from instances

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#87]
We currently process the UCSC band data, and build the chromosomal band/maps for both a specific build and generally for the organism in the same file.

We should separate out the class-level chromosomal band hierarchy from the instance-level for a given build (hg19).  Under consideration is if this should be two outputs of the same job, or two distinct jobs for each organism.

**Comment by nlwashington** [comment]
@cmungall or @mellybelly what license should we use for the ontology?  should it be CC BY-SA ?

**Comment by mellybelly** [comment]
not sure what @cmungall preference is these days.        
Probably:
<dc:rights rdf:resource="http://creativecommons.org/licenses/by/4.0/"/>

**Comment by nlwashington** [comment]
link to http://creativecommons.org/licenses/by/4.0/legalcode or human-readable http://creativecommons.org/licenses/by/4.0/ ?

**Comment by mbrush** [comment]
**An issue that arose on 5-13 call re: what things we classify as 'bands':**  
The ucsc data only reports features that have specific staining intensities associated with them - i.e. chr10p11.22.  Intuitively this is what most people may think of as a 'band' (something that has a discrete staining intensity). We create instances of all features between this chr10p11.22 band reported in the data and the full chromosome, and type them as indicated below:
	
    --> chr10p11.2 (band), chr10p11(band), chr10p1(region), chr10p (arm). 
	
As you can see above, we presently type all chromosome features smaller than regions as bands (e.g.chr10p1 is a region, and anything with additional numerals are bands - chr10p11, chr10p11.2, chr10p11.22). But chr10p11 and chr10p11.2 don’t have discrete/asserted staining patterns reported in the source data.  This raises the question of whether it is proper to call them bands - should the term 'band' be reserved for features with discrete experimentally defined staining intensities, or any feature that is smaller than the region level according to the syntax for naming the feature (i.e anything with more numerals than chr10p1).
	
Some Proposals for what we might do here: 
	
Proposal 1: keep classification and labels as they are (all are bands, don’t distinguish bands that have discrete experimental staining from those that are created in our parsing and have no experimentally defined staining)
	
Proposal 2: keep asserted classification as it is, but create a defined class ('stained band' to collect all bands with staining intensities from the original data)
	
Proposal 3: type the parsed features we create as bands but have no staining intensities as 'chromosomal regions', and only those with staining intensities as bands.
	

Other proposals?

**Comment by mbrush** [comment]
A few other things to consider:

Note that we could infer/calculate staining intensities for all chromosomal features based on the intensities of the bands that comprise them. And some of these historically may have been bands - back when the quality of staining and microscopy techniques was less precise.  So this could be an argument for keeping our classification approach as it is.
	
Consider also that there are cases where there is only one band in a given region, so the region and the band are the same thing.  At present we create separate instances, but should have same as links between them. 
	
Finally, consider that if this is to be a community ontology, we should try to align our labels and classification approach with how domain experts thing about things.

**Comment by cmungall** [comment]
+1

**Comment by nlwashington** [comment]
@mbrush close if satisfied.
