### ISSUE TITLE
add data source OMIA

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#9]
OMIA data can be accessed via downloading/hosting mysql or xml here:
http://omia.angis.org.au/download/

(it has about 10 tables, and we access them all)

**Comment by nlwashington** [comment]
disclaimer and copyright: http://sydney.edu.au/disclaimer.shtml

**Comment by nlwashington** [comment]
for reference, the views in NIF were:
http://beta.neuinfo.org/mynif/search.php?q=*&t=indexable&nif=nif-0000-03215-2
http://beta.neuinfo.org/mynif/search.php?q=*&t=indexable&nif=nif-0000-03215-1

**Comment by nlwashington** [comment]
i believe the xml is of mixed-encoding types (ascii for control characters, and then possibly utf-8 or iso-8859-? or maybe others).  this makes it very hard to run any kind of xml parser on the file without having to wrap everything in a try/catch to test for multiple encodings.  i've requested the data provider dump the data with a uniform encoding strategy.

**Comment by nlwashington** [comment]
@jmcmurry i've got this started in the ```omia``` branch.  note that the xml has some control-b chars in it, which required hand-editing at the moment to remove (can be done in vim) for processing/testing.

**Comment by nlwashington** [comment]
@cmungall there are relationships between breeds and diseases, in that as a class they are susceptible toward / have an increased incidence of a disease.  what would be the appropriate relationship here?  is_marker_for is the closest, but isn't quite right.

**Comment by mellybelly** [comment]
I think you probably need new property, susceptibility_toward
Would be useful for humans too, no?

**Comment by nlwashington** [comment]
@mellybelly what if we just used "is model of" for now?  in that a given breed is a model of disease ?

**Comment by nlwashington** [comment]
ok.  so the data is an association between an animal breed and a species-specific disease/phenotype ssD (which i made as a subclass of the generic disease gD):
so for now i can say:
animal breed B has_phenotype species-specific-disease ssD
(this is still not ideal - it really ought to be a susceptibility_toward property.  (yes, it would be great in humans!)

and then, we have a mapping between the generic animal disease and an omim disease (gD-hD).  i hesitate to make those equivalent (i will let @cmungall do that in the disease-ontology pipeline), but i given the omim mappings, i can say:
animal breed B is_model_of human-disease hD.
in our pipeline, then add a description to say something like:
"High incidence of Campus syndrome in Pietrain (domestic pig) suggests it to be a model of disease OMIM:160500"

**Comment by nlwashington** [comment]
first pass on this complete.  we may need to review / reconsider the omia-omim mappings, and how we utilize them in the automated processes.  also the predicate between a breed and phenotype should be changed from has_phenotype to susceptibility_toward, or somesuch (#194).
