### ISSUE TITLE
add kegg disease-gene associations

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#90]
add the kegg disease gene associations. 

to get the full set into the graph, we'd need to have the kegg disease id to MONDO mappings (https://github.com/monarch-initiative/human-disease-ontology/issues/3)

for now, just add the kegg disease ids as linked to genes; we'll take care of the disease id mappings outside of this ticket.

disease identifiers:
http://rest.genome.jp/list/disease

also, it would seem that the KEGG disease DB is open and unrestricted. this can get us some links between diseases and genes.
ftp://ftp.genome.jp/pub/kegg/medicus/disease/disease

**Comment by nlwashington** [comment]
you can get the disease-gene associations from 
http://rest.kegg.jp/link/disease/hsa
and ncbi gene id mappings:
http://rest.kegg.jp/conv/ncbi-geneid/hsa

**Comment by nlwashington** [comment]
due to the 1:many mappings for kegg disease : omim we may wish to approach this progressively:
  1. only use those disease ids that have a 1:1 mapping (filter out any disease-gene associations where there is >1 kegg disease : omim id).  toss any other annotations.  this will dramatically reduce the amount of data, but will keep it clean
  2. make sure to filter out any omim ids that are not diseases (based on the prefix flag) from the disease : omim id map first, then filter the annotations.  (this will probably get us a few more associations.)
  3. use kegg disease ids directly (this will require loading in the kegg diseases as classes and integrating them into MONDO via https://github.com/monarch-initiative/human-disease-ontology/issues/3)

we can't get more than triples from KEGG, so we can't create the full Association structure with proper evidence.  We can make the assumption that they are "has_phenotype", but we should verify by spot checking some of the references from the KEGG website.

**Comment by nlwashington** [comment]
we want to make sure that grouping diseases don't get the direct gene associations.  for example: ds:H00493 is a grouping class for "[Heparan sulfate proteoglycan gene defects](http://www.kegg.jp/dbget-bin/www_bget?ds:H00493)", which by the definition on the page includes:
Dyssegmental dysplasia, Silverman-Handmaker type;
Schwartz-Jampel syndrome;
Simpson-Golabi-Behmel syndrome, type 1;
Omodysplasia 1;
Multiple exostoses

each of the subtypes listed here has it's own disease-gene association, but we don't get access to that.  the file we have is just the grouping classes to the gene.  and we wouldn't want to directly associate all five genes to the grouping class.  this would be an example of one we'd filter out.

however, i did just find that you might be able to use:
http://rest.genome.jp/link/omim/hsa
to bypass having to do the mappings via kegg disease ids.  this includes a direct mapping to one of the subclasses above (for Schwartz-Jampel syndrome): 
```
hsa:3339	omim:255800	reverse
```
but these should be carefully reviewed, and perhaps even compared to the other method.

**Comment by bryanlaraway** [comment]
My latest [commit](https://github.com/monarch-initiative/dipper/commit/25e1c8d252d2f692e6ba562094c7cc6a2a958f97) should have most of this wrapped up, pending review. 

On the last bit, using the http://rest.genome.jp/link/omim/hsa file, I split the handling of the row based on the link_type column, with "equivalent" mapping as an OMIM gene to KEGG gene, "reverse" mapping as an OMIM disease to KEGG gene, and skipped "original" for now, as it contains bot diseases and genes for the OMIM column. Will want to review these, as you indicated.

**Comment by nlwashington** [comment]
how do we want to handle the curie mapping for KEGG stuff...

KEGG identifiers can all resolve with a url like:
<pre>
http://www.kegg.jp/dbget-bin/www_bget?IDENTIFIER
</pre>
where the IDENTIFIER is something like:
ds:H00147
hsa:3339
ko:K00070

we can either make one curie mapping like:
<pre>
KEGG:   http://www.kegg.jp/dbget-bin/www_bget?
</pre>
but then we're stuck with a colon in the "numeric" part of the local identifier.

or we can make several mappings (as per the id paper we are just on), prefixing with ```KEGG.```(dot) like:

KEGG.ds:H00147
KEGG.hsa:3339
KEGG.ko:K00070

i like the latter; the only problem is that they have different prefixes for each species, like "hsa", "mmu", "dre", etc., so we might pollute our curie map.  thoughts @cmungall ?

**Comment by micheldumontier** [comment]
For Bio2RDF, i ended up stripping prefixes that did not change the uniqueness attribute of the identifier 
e.g. ko:K00070 -> kegg:K00070
http://beta.openlifedata.org/kegg:K00070
while those that need the prefix e.g. hsa:3339, became hsa_3339
http://beta.openlifedata.org/kegg:hsa_3339

**Comment by nlwashington** [comment]
disease-gene associations use is_marker_for because i don't know enough about the relationship between the entities:
![screen shot 2015-06-23 at 5 26 11 pm](https://cloud.githubusercontent.com/assets/5124411/8320229/fc23fb94-19cc-11e5-93f1-82e4b48a7793.png)
