### ISSUE TITLE
Missing OMIMPS subClassOfs in omim ttl?

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/dipper#921]
```
<http://omim.org/entry/128200> a owl:Class ;
    rdfs:label "Episodic Kinesigenic Dyskinesia 1" ;
    OBO:IAO_0000142 <http://www.ncbi.nlm.nih.gov/pubmed/10091631>,
        <http://www.ncbi.nlm.nih.gov/pubmed/10403218>,
        <http://www.ncbi.nlm.nih.gov/pubmed/10577923>,
        <http://www.ncbi.nlm.nih.gov/pubmed/10636137>,
        <http://www.ncbi.nlm.nih.gov/pubmed/10737119>,
        <http://www.ncbi.nlm.nih.gov/pubmed/12076558>,
        <http://www.ncbi.nlm.nih.gov/pubmed/12210861>,
        <http://www.ncbi.nlm.nih.gov/pubmed/13928397>,
        <http://www.ncbi.nlm.nih.gov/pubmed/17387577>,
        <http://www.ncbi.nlm.nih.gov/pubmed/19667324>,
        <http://www.ncbi.nlm.nih.gov/pubmed/22101681>,
        <http://www.ncbi.nlm.nih.gov/pubmed/22120146>,
        <http://www.ncbi.nlm.nih.gov/pubmed/22399141>,
        <http://www.ncbi.nlm.nih.gov/pubmed/22744660>,
        <http://www.ncbi.nlm.nih.gov/pubmed/23535490>,
        <http://www.ncbi.nlm.nih.gov/pubmed/6066074>,
        <http://www.ncbi.nlm.nih.gov/pubmed/6067487>,
        <http://www.ncbi.nlm.nih.gov/pubmed/718486>,
        <http://www.ncbi.nlm.nih.gov/pubmed/7206405>,
        <https://monarchinitiative.org/.well-known/genid/OMIM128200ref11>,
        <https://monarchinitiative.org/.well-known/genid/OMIM128200ref15> ;
    oboInOwl:hasDbXref UMLS:C4552000,
        <http://www.orpha.net/ORDO/Orphanet_98809> .
```

See https://omim.org/entry/128200

I would expect a subClassOf to OMIMPS:PS128200

**Comment by cmungall** [comment]
Also: would it be possible to link from https://dipper.readthedocs.io/en/latest/dipper.sources.OMIM.html to some kind of data model documentation

**Comment by kshefchek** [comment]
devils advocate - why should dipper add these axioms? Or is it that we had these before and they've been removed.  I would think any disease subClassOf axioms would come via Mondo.

This connection appears to be intact in scigraph: OMIM:128200 equivalent to MONDO:0007494 - subclass of MONDO:0044202 - equivalent to OMIMPS128200

**Comment by cmungall** [comment]
of course any we have curated will be available in mondo and thus scigraph

however, mondo relies on the dipper translation of omim as a source input and seed for new diseases!

See the Makefile
https://github.com/cmungall/diseases2owl/tree/master/sources/omim

Maybe we should cut dipper out the loop here, we'd have to reimplement some code, but it can be simpler having shorter ETL chains.

this is a big decision on a complex issue cc @matentzn @mellybelly @deepakunni3

**Comment by cmungall** [comment]
we do need to get something sorted out in the short term as we are way behind on omim in the mondo release

**Comment by cmungall** [comment]
it looks like we also lost synonyms?

**Comment by kshefchek** [comment]
Looking at the code, the intention is to add these subClassOf predicates between OMIMPS and OMIM ids, so I'll take a closer look to see what is going wrong.  I'm unsure on synonyms but will check that out too.  @TomConlin your qc might reveal some of this as well?

**Comment by kshefchek** [comment]
these are all added back but struggling to find the specific commits/prs
