### ISSUE TITLE
announce changes to data file locations

### ISSUE THREAD

**Issue by balhoff** [monarch-initiative/dipper#922]
The paths and file names of the Monarch RDF downloads have changed several times during the past year. I only notice this when my pipeline breaks. The latest was moving `https://archive.monarchinitiative.org/latest/rdf/mgi_slim.ttl` to `https://archive.monarchinitiative.org/latest/rdf/mgislim.ttl` Could we have announcements of these changes posted somewhere? My apologies if I am not subscribed to the right thing. Please let me know how to stay up to date.

**Comment by TomConlin** [comment]
Hi Jim, The changes are me making the dipper automation process smoother, 
(for example that  output file name differed from its ingest file name  with the inserted underscore which only medata files have in the output)
there will likely be a few more going forward but I will take this nudge to be sure you are pinged.
You might be interested in the `ntriples_YYYYMM.tgz` file that also went up there unannounced....

**Comment by balhoff** [comment]
Thanks Tom! I just want to make sure I am getting the right notifications, and also register a vote for a more formal announcement process once things settle down.

**Comment by TomConlin** [comment]
If you are subscribed here you could have seen  https://github.com/monarch-initiative/dipper/pull/904 but I know I do not have the bandwidth to register everything I am subscribed to so I am not sure how more notifications help unless you have someone else taking the time to curate them for you.

**Comment by matentzn** [comment]
I strongly suggest that changes to filenames/locations should be announced somehow when the data release is done.. Isnt there anything like a public Monarch mailing list?

**Comment by TomConlin** [comment]
Including "Release Notes" in the archive  would most definitely be a step in the right direction.

**Comment by matentzn** [comment]
Yeah.. still think this needs to be announced more widely to users. But yes release notes is a good first step.
