### ISSUE TITLE
CTD ingest failing because 1 or more files are behind CAPTCHA wall

### ISSUE THREAD

**Issue by justaddcoffee** [monarch-initiative/dipper#926]
[Failing thusly](https://ci.monarchinitiative.org/blue/organizations/jenkins/dipper-pipeline/detail/dipper-pipeline/129/pipeline/77) with a 403 error

```
INFO:dipper.sources.CTD:fetching 4000 (0-4000)
Traceback (most recent call last):
  File "dipper-etl.py", line 285, in <module>
    main()
  File "dipper-etl.py", line 237, in main
    mysource.fetch(args.force)
  File "/var/lib/jenkins/workspace/dipper-pipeline/dipper/sources/CTD.py", line 178, in fetch
    self._fetch_disambiguating_assoc()  # api ferch
  File "/var/lib/jenkins/workspace/dipper-pipeline/dipper/sources/CTD.py", line 386, in _fetch_disambiguating_assoc
    resp = urllib.request.urlopen(req)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
script returned exit code 1
```

Possibly this is because 1 or more files are now behind a CAPTCHA wall, for example:
http://ctdbase.org/reports/CTD_chemicals_diseases.tsv.gz

Putting these files in DipperCache would fix things (at least until the next time DipperCache needs to download them)

**Comment by TomConlin** [comment]
that was the one and only biogrid file DipperCache did pull weekly ...

**Comment by justaddcoffee** [comment]
As of this morning, at least this file http://ctdbase.org/reports/CTD_chemicals_diseases.tsv.gz is downloading normally without CAPTCHA on my local machine here and also on tartini. Possibly they removed this CAPTCHA?

**Comment by TomConlin** [comment]
That is good news.
I did find a direct email and did sent a plea. 

todday they replied

```
Hi, Tom:

Update: for now, we have turned OFF the CAPTCHA step at CTD.
However, if things become unsettled again, we may have to re-address the
situation.
Thanks
--- cheers, A.P.D.

```

the situation is not us

**Comment by justaddcoffee** [comment]
Okay, fixed for now then. 

I heard also that CTD was whitelisting some IP addresses for a time as a stopgap measure to address problem caused by their CAPTCHA wall. If this comes up again, perhaps we can get them to whitelist tartini's IP address (or whatever IP address our Jenkins pipeline appear to come from)

**Comment by TomConlin** [comment]
I will send them our IP address range just in case
