### ISSUE TITLE
Emma ingest question

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/dipper#929]
Just listened to a talk where someone was mentioning the EMMA resource/

https://www.infrafrontier.eu/emma-strains-and-rare-diseases

Are these (the variant->disease annotations) imported through the MGI pipeline (I can see lots of EMMA terms in @TomConlin s curie counts)?

**Comment by TomConlin** [comment]
7.2k  `EMMA` appear  in  the Dipper MGI ingest as `owl:sameAs` to some `MGI`

noticeable in: https://archive.monarchinitiative.org/latest/visual_reduction/release/mgi.gv 
determining if those `MGI` the `EMMA` are the same as are; variants associated with a disease would take a second deeper look. 

Would you like me to do that?

**Comment by matentzn** [comment]
Thanks for checking! Not sure you have to spent time on it; Lets keep it in mind for after the renewal perhaps?

**Comment by TomConlin** [comment]
maybe jot down your thoughts , I have just spent a bunch of time in MGI's database looking to make how we fetch from them more robust so the timing now is better than average.

**Comment by matentzn** [comment]
It was really just that I was listening to a rare disease talk in the context of the European Joint Programme of Rare Diseases, and they mentioned that they wanted to integrate with resources such as that one.

**Comment by kshefchek** [comment]
solr is also great for queries like these, but I wasn't able to turn anything up in any association that we index.http://www.informatics.jax.org/strain/MGI:2655911 has the most edges connected to it, but looks like mostly GENO model construction.

**Comment by matentzn** [comment]
Maybe if this source (EMMA) turns out interesting, we can consider making it a primary ingest after renewal approval.
