### ISSUE TITLE
Searching of OWL Axioms across dipper

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/dipper#938]
As a follow up on todays data call, could we figure out the uses of the following expressions (with simple regex search its fine), perhaps broken down by source?

- ObjectIntersectionOf
- ObjectUnionOf
- ObjectComplementOf
- ObjectOneOf
- ObjectSomeValuesFrom
- ObjectAllValuesFrom
- ObjectHasValue
- ObjectHasSelf
- ObjectMinCardinality
- ObjectMaxCardinality
- ObjectExactCardinality
- DataSomeValuesFrom
- DataAllValuesFrom
- DataHasValue
- DataMinCardinality
- DataMaxCardinality
- DataExactCardinality

If this is too much work, these are the most important ones:

- DataSomeValuesFrom 
- ObjectComplementOf 
- ObjectIntersectionOf 
- ObjectAllValuesFrom 

@TomConlin let me know if that works for you :)

**Comment by TomConlin** [comment]
easier that I would have guessed.
there are none in the dipper RDF
if you are seeing some coming from this direction 
they must be a scigraph thing

**Comment by matentzn** [comment]
Which makes sense! There will be millions of course in the monarch.owl ingest :) but yeah, good to know. Thanks for checking!
