### ISSUE TITLE
Get Mondo curies from ClinVar ingest

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/dipper#952]
ClinVar is starting to use Mondo, eg https://www.ncbi.nlm.nih.gov/clinvar/RCV000005180.3/, however the identifiers are double prefixed

Currently our ingest drops these (ironically) with the log
```RCV000874767 UNKNOWN DISEASE DB:	MONDO:MONDO:0013476```

**Comment by TomConlin** [comment]
elsewhere in dipper we have standardized on keeping only the penultimate prefix
foo.split(':')[-2:]
