### ISSUE TITLE
omim dipper for mondo missing some classes

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/dipper#954]
I am using
https://data.monarchinitiative.org/experimental/omim.ttl

to seed mondo

I get some triples such as

```
<http://omim.org/entry/180860> <https://w3id.org/biolink/vocab/category> <https://w3id.org/biolink/vocab/Disease> .
```

but I have no rdfs:label triple for https://omim.org/entry/180860

**Comment by kshefchek** [comment]
try https://data.monarchinitiative.org/dev/omim.ttl, this is the output from the master branch weekly runs

OMIM:180860 a owl:Class ;
    rdfs:label "Silver-Russell Syndrome 1" ;
    ...
