### ISSUE TITLE
Diseases which are also Genes

### ISSUE THREAD

**Issue by rgb4268** [monarch-initiative/dipper#961]
I have found some instances of diseases, e.g. MONDO:0020119 which have a child which is actually a gene - in this case ZC4H2. There are a few more.

**Comment by kshefchek** [comment]
this is coming from HGNC:24931 being declared an equivalentClass to OMIM:300897, usually HGNC properly xrefs to OMIM genes but this looks like an exception

**Comment by TomConlin** [comment]
We do have the data structures on hand to "trust but verify"  HGNC's assertion that their OMIM dbxref  is in fact to what we also believe is a gene

**Comment by kshefchek** [comment]
false alarm on HGNC, still trying to trace this one

**Comment by kshefchek** [comment]
closer look, this looks like an NCBIGene issue:
<https://www.ncbi.nlm.nih.gov/gene/55906> owl:equivalentClass <http://omim.org/entry/309605>

and this is equivalent to MONDO:0010666

**Comment by TomConlin** [comment]
A bit more context 
omim:309605 has been subsumed into  
omim:314580 which is for WIEACKER-WOLFF SYNDROME  but the original
may have had a different role when it was assigned to  NCBIGene:55906

Dipper does handle the replacement & classifies it as a disease

Also we no longer create an equivalence class as it no longer falls through with `continue`

**Comment by pnrobinson** [comment]
Note also this entry
https://omim.org/entry/301041
I think it is confusing to separate the diseases into XLR and XLD as is being done here

**Comment by TomConlin** [comment]
close w/ #964
