### ISSUE TITLE
omim.ttl has a broken dc:description declaration (illegal punning)

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/dipper#970]
```
dc:description a owl:AnnotationProperty,
        owl:DatatypeProperty .
```

You cannot be an annotation and a data property at once!

Using this file: https://archive.monarchinitiative.org/alpha/rdf/omim.ttl

Making a quick test edit, replacing the above with just:

```
dc:description a owl:AnnotationProperty .
```

Will be sufficient.

**Comment by kshefchek** [comment]
these are autogenerated at the end of every dipper run from upstream ontologies, so the error is from one of these (https://github.com/monarch-initiative/dipper/blob/master/dipper/utils/GraphUtils.py#L63)

i'd like to experiment with removing this entirely, there was the idea that this is needed for [scigraph](https://github.com/monarch-initiative/dipper/blob/master/dipper/utils/GraphUtils.py#L63) but I've always wondered if scigraph or the owlapi can figure out if an object is a literal or IRI based on its type.

**Comment by TomConlin** [comment]
+1*10^999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999

**Comment by matentzn** [comment]
Dipper should not make such assumptions at all... The ontology layer should take care of that. I would be surprised if anything would change if you just removed this code.

**Comment by TomConlin** [comment]
+2*10^999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999

**Comment by kshefchek** [comment]
@matentzn this axiom comes from SEPIO in case you want to fix there as well, https://github.com/monarch-initiative/SEPIO-ontology/blob/master/src/ontology/sepio.owl#L1706

**Comment by kshefchek** [comment]
See this ticket for more info - https://github.com/monarch-initiative/dipper/issues/316
