### ISSUE TITLE
Disease-gene mixups for biolink:categories in OMIM ingest

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/dipper#972]
@deepakunni3 is reporting that the KGX ingest found 161 OMIM ids that are both diseases and genes:
[errant-omim.txt](https://github.com/monarch-initiative/dipper/files/5172205/errant-omim.txt)

**Comment by TomConlin** [comment]
a bit more including which ingests say what 
[errant_blcat.txt](https://github.com/monarch-initiative/dipper/files/5172709/errant_blcat.txt)

**Comment by kshefchek** [comment]
for the september data I've removed the bl categories that come from dipper in the ntriples file, but they can be fetched from the inferred files - https://archive.monarchinitiative.org/202009/rdf/blshim/omim.nt or https://archive.monarchinitiative.org/202009/rdf/blcategories/omim.nt

**Comment by kshefchek** [comment]
fixed with https://github.com/monarch-initiative/dipper/pull/973
