### ISSUE TITLE
OMIA uses obsolete disease class

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/dipper#998]
![image](https://user-images.githubusercontent.com/50745/99471154-ea228d00-28fa-11eb-8cef-955e76a221c2.png)

uses this obsolete class http://purl.obolibrary.org/obo/DOID_2214

**Comment by cmungall** [comment]
https://github.com/monarch-initiative/dipper/blob/fcbe342a7de4a2bf0ef9ce3b0f6daec304461d3b/translationtable/GLOBAL_TERMS.yaml#L80

**Comment by TomConlin** [comment]
OMIAs  string `"group_category:4"` is what dipper translated to 
"inherited blood coagulation disease".

I do not find  the string "group_category:4" in OMIAs data file now
and think the best would be to drop the local and global tt mappings.

Eagerly dropping mappings is probably the best course; we can always revisit adding them back if they show up again and be party to the decisions



https://github.com/monarch-initiative/dipper/blob/master/translationtable/omia.yaml#L43

**Comment by TomConlin** [comment]
noting this solution has been sitting in the omia local translation table
commented out for the latt couple of years with the question; is the  MONDO term too specific.

https://github.com/monarch-initiative/dipper/blob/79c9735f0120d0309ab446d9f9a93e2d88f4a0e3/translationtable/omia.yaml#L41

**Comment by kshefchek** [comment]
fixed with #999
